(function(D){D.execute(function(){(function(g){document.createElement("header");var a=function(b){function d(a,b,d){a[d]=function(){c._replay.push(b.concat({m:d,a:[].slice.call(arguments)}))}}var c={};c._sourceName=b;c._replay=[];c.getNow=function(a,b){return b};c.when=function(){var a=[{m:"when",a:[].slice.call(arguments)}],b={};d(b,a,"run");d(b,a,"declare");d(b,a,"publish");d(b,a,"build");return b};d(c,[],"declare");d(c,[],"build");d(c,[],"publish");d(c,[],"importEvent");a._shims.push(c);return c};
a._shims=[];if(!g.$Nav)g.$Nav=a("rcx-nav");if(!g.$Nav.make)g.$Nav.make=a})(window)})})(function(){var D=window.AmazonUIPageJS||P,g=D.attributeErrors;return g?g("NavAuiShim"):D}());
/* ******** */
(function(A){A.execute(function(){function j(c){function a(){var a=Date.now();return{uid:a,suggestionsReadyForDisplay:{name:"suggestionsReadyForDisplay-"+a},suggestionsReady:{name:"suggestionsReady-"+a},suggestionsRendered:{name:"suggestionsRendered-"+a},updateSearchBox:{name:"updateSearchBox-"+a},selectionChange:{name:"selectionChange-"+a},dropdownHidden:{name:"dropdownHidden-"+a},updateSearchTerm:{name:"updateSearchTerm-"+a},suggestionClicked:{name:"suggestionClicked-"+a},suggestionsNeeded:{name:"suggestionsNeeded-"+
a},a9SuggestionsNeeded:{name:"a9-suggestionsNeeded-"+a},noSuggestions:{name:"nosuggestions-"+a},searchBoxFocusIn:{name:"searchBoxFocusIn-"+a},searchBoxFocusOut:{name:"searchBoxFocusOut-"+a},keydown:{name:"keydown-"+a},hideDropdown:{name:"hidedropdown-"+a},focusOnParent:{name:"focusOnParent-"+a},parentFocused:{name:"parentFocused-"+a},parentLostFocus:{name:"parentLostFocus-"+a},searchTermChanged:{name:"searchTermChanged-"+a},suggestionsDisplayed:{name:"suggestionsDisplayed-"+a},upArrowPressed:{name:"upArrowPressed-"+
a},downArrowPressed:{name:"downArrowPressed-"+a}}}return{globals:{issLoaded:{name:"issLoaded"},suggestionsRendered:{name:"suggestionsRendered"},initializeNavSearchBox:{name:"initializeSearchBox"}},createInstance:function(){return new a},createEvent:function(a,g){var e=g;g.hasOwnProperty("name")?e=g.name:typeof g==="string"?e=g:c.logDebug('Format of "event" parameter is not a string or an event object',g);return a+"-"+e}}}window.$Nav.when("$","nav.inline").run(function(c){window.$Nav.declare("config.blackbelt",
c("#nav-belt").length>0)});window.$Nav.when("config.blackbelt").run(function(c){c?window.$Nav.when("searchApi").run(function(a){window.$Nav.declare("sxSearchApi",a)}):window.$Nav.declare("sxSearchApi")});window.$Nav.when("$","sxSearchApi","sx.iss.DomUtils").build("NavDomApi",function(c,a,b){var g,e,h;function i(){return j?o().find('input[type="text"]'):(typeof l==="undefined"&&(l=c(g)),l)}function d(){return j?a.flyout.elem():(typeof q==="undefined"&&(q=c(s),o().after(q)),q)}function f(){return j?
a.options().parents("select"):(typeof v==="undefined"&&(v=c(e)),v)}function o(){return j?a.options().parents("form"):c(h)}function k(){var a=n(),b=d();d().is(":visible")&&!(b.html().length<1)&&b.css({left:a.offset().left,width:a.width()})}function n(){r===void 0&&(r=c("#nav-iss-attach"));return r}var j=a!==void 0;g="#twotabsearchtextbox";e="#searchDropdownBox";h="#nav-searchbar";var l,m,q,v,r,s='<div id="search-dropdown" class="search-dropdown"></div>',u=/search-alias\s*=\s*([\w-]+)/;a===void 0&&
c(window).resize(k);return{getAliasDropdown:f,getSearchBox:i,getSearchBoxId:function(){return g},getSearcchSuggestions:function(){typeof m==="undefined"&&(m=c("#srch_sggst"));return m},getKeyword:function(){var d;d=a!==void 0?a:i();return b.getKeyword(d)},setKeyword:function(b){if(a!==void 0)a.val(b);else return i().val(b)},getAliasFromDropdown:function(){var a=f().val();return(a=a&&a.match(u))?a[1]:void 0},getCategoryNameFromDropdown:function(a){var b="";a?(a=f().find('option[value$="search-alias='+
a+'"]'),b=a.length>0?c(a[0]).text():b):b=f().find("option:selected").text();return c.trim(b)},getDropdown:d,showDropdown:function(b){j?(typeof b!=="undefined"&&a.flyout.elem().html(b),a.flyout.show()):(typeof b!=="undefined"&&d().hide().html(b),b=n(),d().css({left:b.offset().left,width:b.width()}).show())},hideDropdown:function(){j?a.flyout.hide():d().hide()},getOption:function(a){if(!a)return f().find("option:selected");a=f().find('option[value$="search-alias='+a+'"]');return a.length>0?c(a[0]):
c()},getForm:o,getIssPrefixElem:function(){return c("#issprefix")},getSuggestions:function(){return c(".s-suggestion")},submitForm:function(){o().submit()},getOriginalSearchTerm:function(){return o().data("originalSearchTerm")},getOriginalAlias:function(){return o().data("originalAlias")},isSearchBoxFocused:function(){return i().get(0)===document.activeElement},activateSearchBox:function(){o().addClass("nav-active")},deactivateSearchBox:function(){o().removeClass("nav-active")},getSearchApi:function(){return a}}});
window.$Nav.build("sx.iss.TemplateEngine",function(){var c={};return function b(g,e){var h=/^[a-zA-Z0-9_-]+$/.test(g)?c[g]=c[g]||b(document.getElementById(g).innerHTML):new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push('"+g.replace(/[\r\t\n]/g," ").replace(/'(?=[^#]*#>)/g,"\t").split("'").join("\\'").split("\t").join("'").replace(/<#=(.+?)#>/g,"',$1,'").split("<#").join("');").split("#>").join("p.push('")+"');}return p.join('');");return e?h(e):h}});window.$Nav.when("$").build("sx.iss.TemplateInstaller",
function(c){function a(a,c){var e=document.createElement("script");e.setAttribute("type","text/html");e.setAttribute("id",a);e.text=c;return e}c("body");return{init:function(){var b=document.createDocumentFragment();b.appendChild(a("s-suggestion",'<div id="<#= suggestionId #>"class="s-suggestion"data-alias="<#= alias #>"data-keyword="<#= keyword #>"data-store="<#= store #>"data-isSc="<#= isSpellCorrected #>"data-isFb="<#= isFallback #>"data-type="<#= type #>"><#= bprefix #><span class="s-heavy"><#= prefix #></span><#= suffix #><# if (typeof storeHtml === "string") { #> <#= storeHtml #><# } #></div>'));
b.appendChild(a("suggestions-template",'<div id="suggestions-template"><# if (typeof suggestionTitle !== "undefined") { #><div id="suggestion-title"><#= suggestionTitle #></div><# } #><div id="suggestions"><# if (typeof suggestions !== "undefined") {for(var i=0; i < suggestions.length; i++) {var displayString = suggestions[i].display; #><#= displayString #><# }} #></div></div>'));b.appendChild(a("s-separator",'<div id="s-separator"><div class="s-separator"></div></div>'));b.appendChild(a("s-department",
'<div id="<#= suggestionId #>" class="s-suggestion s-highlight-primary"data-alias="<#= alias #>"data-keyword="<#= keyword #>"data-store="<#= store #>"data-type="<#= type #>">Shop the <#= beforePrefix #><span class="s-heavy"><#= prefix #></span><#= suffix #> store</div>'));b.appendChild(a("s-option",'<option value="<#= value #>"><#= store #></option>'));b.appendChild(a("s-minimal",'<div class="s-suggestion s-custom" data-url="<#= url #>"><#= bprefix #><span class="s-heavy"><#= prefix #></span><#= suffix #></div>'));
b.appendChild(a("s-storeText",'<span class="<#= cssClasses #>"><#= store #></span>'));b.appendChild(a("s-corpus",'<div class="s-suggestion" id="<#= suggestionId #>"data-alias="<#= alias #>"data-url="<#= url #>"data-type="<#= type #>"data-keyword="<#= keyword #>"><# if (typeof primeText !== "undefined") { #><span class="s-highlight-primary">[<#= primeText #>] </span><# } #><#= bprefix #><span class="s-heavy"><#= prefix #></span><#= suffix #></div>'));document.body.appendChild(b)}}});window.$Nav.when("sx.iss.DebugUtils",
"sx.iss.DomUtils").build("sx.iss.EventBus.instance",function(c,a){return new function(){function b(a){var b=typeof a,d="";b==="object"&&a.hasOwnProperty("name")?d=a.name:b==="string"&&(d=a);return d}var g={},e={};this.listen=function(e,i,d){var f,o="";if(a.isArray(e)){for(f=0;f<e.length;f++)o=e[f],this.listen(o,i,d),c.logDebug("Listening for: "+o);return this}o=b(e);g[o]||(g[o]=[]);g[o].push({f:i,o:d});c.logDebug("Listening for: "+o);return this};this.trigger=function(a,e){var d=b(a);c.logDebugWithTrace("Trigger: "+
d,e);var d=g[d],f;if(d){for(f=0;f<d.length;f++)d[f].f.call(d[f].o,e);return this}};this.triggerThrottledEvent=function(a,i,d){var f=b(a);c.logDebugWithTrace("Trigger (throttled): "+f,i);var o=g[f],a=e[f];if(o)return d===void 0&&(d=100),a&&(clearTimeout(a),delete e[f]),a=setTimeout(function(){var a;for(a=0;a<o.length;a++)o[a].f.call(o[a].o,i);delete e[f]},d),e[f]=a,this}}});window.$Nav.when("$","sx.iss.utils","sx.iss.Events","NavDomApi","sx.iss.DebugUtils","sx.iss.IssContext").build("sx.iss.PublicApi",
function(c,a,b,g,e,h){function i(a){g.getSearchBox().focus(a)}function d(a){a===void 0?g.getSearchBox().blur():g.getSearchBox().blur(a)}var f=/node\s*=\s*([\d]+)/,o=/bbn\s*=\s*([\d]+)/,k=/^me=([0-9A-Z]*)/,n=/^\s+/,j=/\s+/g;return{searchAlias:function(){return g.getAliasFromDropdown()},searchNode:function(){var a=g.getAliasDropdown().val().match(f);return a?a[1]:null},bbn:function(){var a=g.getAliasDropdown().val().match(o);return a?a[1]:null},merchant:function(){var a=g.getAliasDropdown().val().match(k);
return a?a[1]:null},encoding:function(){var a=g.getForm().find('input[name^="__mk_"]');if(a.length)return[a.attr("name"),a.val()]},keyword:function(a){return a!==void 0?g.setKeyword(a):g.getKeyword().replace(n,"").replace(j," ")},submit:function(a){e.logDebugWithTrace("Attaching the submit event handler to the form...");g.getForm().submit(a)},suggest:function(d){a.eventBus.listen(b.globals.suggestionsRendered,function(a){var b=[];c.each(a.suggestions,function(a,d){d.type!=="separator"&&b.push(d)});
d(a.searchTerm,b)})},onFocus:i,onBlur:d,focus:i,blur:d,keydown:function(a){var b="#"+g.getSearchBox().attr("id");g.getForm().delegate(b,"keydown",a)},setupFastLab:function(a){e.logDebugWithTrace("Fastlab",a);h.setFastlabs(a)}}});window.$Nav.when("$","NavDomApi","sx.iss.utils","sx.iss.DebugUtils","sx.iss.IssContext").build("sx.iss.Weblab",function(c,a,b,g,e){return function(a,c){function d(d,c){var i={keywords:c?c.searchTerm:void 0,alias:b.suggestionUtils.getAliasWithDeepNodeAliasBacked(a.deepNodeISS),
fastlabs:e.getTriggeredFastlabs().join("|")};e.clearTriggeredFastlabs();a.hasOwnProperty(d)&&(a[d](i),g.logDebug("Triggering: "+d+" weblabs"))}b.eventBus.listen(c.keydown,function(a){d("doCTWKeydown",a)});b.eventBus.listen(c.suggestionsRendered,function(a){d("doCTWDisplay",a)})}});window.$Nav.when("sx.iss.DebugUtils","sx.iss.DomUtils").build("sx.iss.IssContext",function(){var c,a,b=[];return{getFastlabs:function(){return a},setFastlabs:function(b){a=b},getTriggeredFastlabs:function(){return b},clearTriggeredFastlabs:function(){b=
[]},addTriggeredFastlabs:function(a){b=b.concat(a)},getConfiguration:function(){return c},setConfiguration:function(a){c=a}}});window.$Nav.when("$","sx.iss.utils","sx.iss.SuggestionTypes","NavDomApi","sx.iss.ReftagBuilder","sx.iss.DebugUtils").build("sx.iss.Reftag",function(c,a,b,g,e,h){return function(b,d,f){function c(a){return(new e).build(a,f.hasOwnProperty("shouldAddImeTag")&&f.shouldAddImeTag())}function k(a){if(a.suggestions===void 0||a.searchTerm===void 0)h.logDebug('"suggestions" or "searchTerm" is undefined',
a);else{for(var b=e.CONSTANTS.noSearchTermMatchInResults,d=a.searchTerm,a=a.suggestions,f=0;f<a.length;f++)if(d===a[f].keyword){b=e.CONSTANTS.searchTermMatchInResults;break}l(b)}}function n(){l(e.CONSTANTS.noResults)}function j(a){a.suggestion===void 0||a.searchTerm===void 0?h.logDebug('"suggestion" or "searchTerm" is undefined',a):l(c(a))}function l(a){var b=/(ref=[\-\w]+)/,d=/(dd_[a-z]{3,4})(_|$)[\w]*/,f=g.getForm(),c=f.attr("action");b.test(c)?c=d.test(c)?c.replace(d,"$1_"+a):c.replace(b,e.CONSTANTS.reftagBase+
a):(c.charAt(c.length-1)!=="/"&&(c+="/"),c+=a);f.attr("action",c)}d===void 0&&(d={});f===void 0&&(f={});a.eventBus.listen(b.selectionChange,j);a.eventBus.listen(b.suggestionsRendered,k);a.eventBus.listen(b.noSuggestions,n);return{create:c,updateReftagAfterRender:k,updateReftagAfterSelection:j,updateReftagAfterNoSuggestions:n,updateFormActionWithReftag:l}}});window.$Nav.when("$","sx.iss.SuggestionTypes","sx.iss.DataAttributes","NavDomApi","sx.iss.DebugUtils").build("sx.iss.ReftagBuilder",function(c,
a,b,g,e){function h(){function d(a){a!==void 0&&n.push(a);return this}function f(a){var a=g.getOption(a.data("alias")).val(),b=a.indexOf("=");if(b===-1)return"";var a=a.substr(b+1),b=a.indexOf("-"),d=a.substr(0,3);return b?d:d+a.charAt(b+1)}function h(c,o){var m=c.suggestion,j=c.searchTerm,v=c.previousSearchTerm;e.isDebugModeOn()&&e.logDebugWithTrace("Build reftag for search term: "+j+" pre term:"+v,m);var r=k(m),s=r.reftag;d(i.base);o&&d(i.ime);var u;if(m.data(b.fallback.name)===!0)u=i.fallback;
else if(m.data(b.spellCorrected.name)===!0)u=i.spellCorrected;u!==void 0?d(u):(m.data("type")===a.department.name&&(d(a.a9Xcat.reftag),d(m.data("alias"))),d(s));s!==a.a9.reftag&&s!==a.a9Corpus.reftag?d(0):(r=r.name,r=g.getDropdown().find('.s-suggestion[data-type="'+r+'"]').index(m)+1,d(r));m===void 0?(d(i.undefinedSugg),m=f(m),d(m)):d(v?v.length:j.length);return n.join(i.separator)}function k(b){var d=a.a9;c.each(a,function(a,f){if(b.data("type")===f.name)return d=f,!1});return d}function f(a){var a=
a.val(),b=a.indexOf("=");if(a!==""||b===-1)return"";var a=a.substr(b+1),b=a.indexOf("-")+1,d=a.substr(0,3);return b?d:d+a.charAt(b)}var n=[];return{build:h,buildFull:function(a,b){return i.reftagBase+h(a,b)}}}var i={base:"ss",fallback:"fb",spellCorrected:"sc",undefinedSugg:"dd",reftagBase:"ref=nb_sb_",noResults:"noss",searchTermMatchInResults:"noss_1",noSearchTermMatchInResults:"noss_2",ime:"ime",separator:"_"};h.CONSTANTS=i;return h});window.$Nav.when("$","NavDomApi","sx.iss.DebugUtils").build("sx.iss.suggestionUtils",
function(c,a,b){function g(a,b){return a.toLowerCase().indexOf(b.toLowerCase())}function e(a,b,d){return{bprefix:a.substr(0,b),prefix:a.substr(b,d),suffix:a.substr(b+d)}}function h(a){if(a)return a.replace(f,"")}function i(b){var d;typeof a.getAliasFromDropdown()==="undefined"&&b&&(d=b.searchAliasAccessor(c));return d}var d=/\s/,f=/#(S|E)#/g;return{getPrefixPos:g,getPrefixPosMultiWord:function(a,b){var f=a.toLowerCase().indexOf(b.toLowerCase()),e;if(f===-1)return-1;if(f===0)return 0;e=a[f-1];return e===
" "||e==="\t"||e.match(d)?f:-1},splitStringForDisplay:e,markHighlight:function(a,b){var d=g(b,a);return d>-1?(d=e(b,d,a.length),d.bprefix+"#S#"+d.prefix+"#E#"+d.suffix):b},removeHighlightMark:h,splitHighlightedString:function(a){if(a&&a.length>6){var b=a.indexOf("#S#"),d=a.indexOf("#E#");if(b>-1&&d>-1&&b+3<d)return{bprefix:h(a.substr(0,b)),prefix:h(a.substr(b+3,d-b-3)),suffix:h(a.substr(d+3))}}},getAliasWithDeepNodeAliasBacked:function(b){var d=a.getAliasFromDropdown();return d?d:i(b)},getDeepNodeAlias:i,
getDeepNodeCategoryName:function(b,d){var f;b&&(f=a.getCategoryNameFromDropdown(b)||d.searchAliasDisplayNameAccessor());return f},shouldRequestSuggestions:function(d,f){var e;if((d==="department"||d==="a9")&&f.hasOwnProperty("aliases")){var c=a.getAliasFromDropdown()||i(f.deepNodeISS);e=f.aliases==="*"||f.aliases.indexOf(c)>-1;b.logDebug("Should we request suggestions for: alias : "+c+" provider : "+d+"? "+e);return e}return!0}}});window.$Nav.when("sx.iss.TimingProvider.instance","sx.iss.EventBus.instance",
"sx.iss.suggestionUtils","sx.iss.DependenciesMet").build("sx.iss.utils",function(c,a,b){return{timingProvider:c,eventBus:a,suggestionUtils:b,now:function(){return(new Date).getTime()},escapeRegExp:function(a){return a.replace(/([.*+?\^${}()|\[\]\/\\])/g,"\\$1")}}});window.$Nav.when("$").build("sx.iss.DomUtils",function(){var c=/\+/g,a=/^\s+/;(function(){if(!Array.prototype.indexOf)Array.prototype.indexOf=function(a,c){var e=this.length>>>0,h=Number(c)||0,h=h<0?Math.ceil(h):Math.floor(h);for(h<0&&
(h+=e);h<e;h++)if(h in this&&this[h]===a)return h;return-1}})();return{isHoveredClass:"is-hovered",getKeyword:function(b){return(b=b.val())?b.replace(a,""):b},isElHoveredOver:function(a){return a.hasClass("is-hovered")},hoverOverEl:function(a){return a.addClass("is-hovered")},hoverOutEl:function(a){return a.removeClass("is-hovered")},isArray:function(a){return Object.prototype.toString.call(a)==="[object Array]"},getFormParams:function(a){for(var a=a.split("?"),g=a.length>1?a[1]:void 0,g=g?g.split("&"):
[],e=g.length,h;e-- >0;)h=g[e].split("="),g[e]={name:h[0],value:h[1].replace(c," ")};return{uri:a[0],formParams:g}},suggestionClass:".s-suggestion",hiddenInputValue:"frmDynamic",hiddenInputClass:".frmDynamic",areAnySuggestionsHoveredOver:function(a){return a.find(".is-hovered").length>0},getCursorPosition:function(a){a=a.get(0);if("selectionStart"in a)return a.selectionStart;else if(document.selection){a.focus();var c=document.selection.createRange(),e=c.text.length;c.moveStart("character",-a.value.length);
return c.text.length-e}return-1}}});window.$Nav.build("sx.iss.DebugUtils",function(){function c(a){if(a&&a.length>0)for(var a=a.substring(1).split("&"),b=0;b<a.length;b++){var d=a[b].split("=");if(d[0]==="debug"){for(var f in e)e.hasOwnProperty(f)&&(e[f]=d[1].indexOf(f)!==-1?!0:!1);break}}}function a(){return e.iss||e.isstrace}function b(){return e.isstrace}function g(b,e){a()&&window.console&&(e!==void 0?console.debug(b,e):console.debug(b))}var e={iss:!1,isstrace:!1,noiss:!1,isspolyfill:!1,isscf:!1};
c(window.location.search);return{init:c,logDebug:g,logDebugWithTrace:function(a,e){g(a,e);b()&&console.trace()},isDebugModeOn:a,isDebugModeOnWithTrace:b,isDisableISS:function(){return e.noiss},isUsingPolyFill:function(){return e.isspolyfill},isQIAEnabled:function(){return e.isscf}}});window.$Nav.build("sx.iss.ObjectUtils",function(){return{freeze:function(c){Object.freeze&&c&&Object.freeze(c)}}});window.$Nav.when("$","sx.iss.DebugUtils").run(function(c,a){a.isDisableISS()||((!c.fn.delegate||a.isUsingPolyFill())&&
c.extend(c.fn,{delegate:function(b,g,e){return this.bind(g,function(g){var i=c(g.target);if(i.is(b)||i.parents(b).length>0)return a.logDebug("delegate ",{selector:b,target:i,event:g}),e.apply(i,arguments)})}}),window.$Nav.declare("sx.iss.DependenciesMet"))});window.$Nav.when("sx.iss.DepartmentDataFormatter").build("sx.iss.DepartmentData",function(){return{getData:function(){return[]}}});window.$Nav.build("sx.iss.DepartmentDataFormatter",function(){return{format:function(c){for(var a=[],b=0;b<c.length;b++){var g=
c[b];a.push({id:g[0],alias:g[0],keyword:"",type:"department",store:g[1],name:"",triggerWords:g[2],sn:!1})}return a}}});window.$Nav.when("sx.iss.ObjectUtils").build("sx.iss.SuggestionTypes",function(c){var a={a9:{name:"a9",reftag:"i",templateId:"s-suggestion"},a9Xcat:{name:"a9-xcat",reftag:"c",templateId:"s-suggestion"},a9XOnly:{name:"a9-xcat-only",reftag:"xo",source:"xo",templateId:"s-suggestion"},a9Corpus:{name:"a9-corpus",reftag:"cp",reftagTemplate:"REF_TAG",templateId:"s-corpus"},department:{name:"department",
reftag:"deptiss",templateId:"s-department"}};c.freeze(a);return a});window.$Nav.when("sx.iss.ObjectUtils").build("sx.iss.InfoTypes",function(c){var a={actor:"actor",author:"author",director:"director",seasonTitle:"season_title",title:"title"};c.freeze(a);return a});window.$Nav.build("sx.iss.DataAttributes",function(){return{fallback:{name:"isfb"},spellCorrected:{name:"issc"}}});window.$Nav.build("sx.iss.TimingEvents",function(){return{latency:{group:"Latency",events:{timeToDisplay:"timeToDisplay"}}}});
window.$Nav.when("sx.iss.DebugUtils").build("sx.iss.Events",j);window.$Nav.when("sx.iss.ObjectUtils").build("sx.iss.Platform",function(c){var a={name:"desktop",cid:"amazon-search-ui",callback:"String",needExtraParams:!0};c.freeze(a);return a});window.$Nav.when("$").build("sx.iss.TimingProvider.instance",function(c){return new function(){var a={};this.startTimer=function(b,c){a[b]||(a[b]={});a[b][c]={start:+new Date}};this.stopTimer=function(b,c){var e=a[b]&&a[b][c];if(!e)return-1;e.end=+new Date;
return e.end-e.start};this.getTimings=function(b){return a[b]};this.getTimingStats=function(b){var g={name:b},e=0,h=0,i=void 0,d=void 0,f=0,o=0,k=[],j=0,p=0;if(a[b]){c.each(a[b],function(a,b){if(b.start&&b.end){o=b.end-b.start;k.push(o);f++;h+=o;if(!i||o<i)i=o;if(!d||o>d)d=o}});k.sort();g.n=f;g.avg=h/f;g.min=i;g.max=d;g.med=f===1?k[0]:f%2?(k[Math.floor(f/2)]+k[Math.ceil(f/2)])/2:k[f/2];for(e=0;e<f;e++)j=k[e]-g.avg,j*=j,p+=j;g.stddev=Math.sqrt(p/f);return g}};this.getTimingWithDisplayLatency=function(b,
c){var e=a[b]&&a[b][c];return!e?-1:e.end-e.start+100}}});window.$Nav.when("$","sx.iss.utils","NavDomApi","sx.iss.Events","sx.iss.SuggestionTypes","sx.iss.A9SuggestionQueryConstructors","sx.iss.A9SuggestionResultsProcessors","sx.iss.DebugUtils").build("sx.iss.A9SuggestionProvider",function(c,a,b,g,e,h,i,d){var f="a9",o=e.a9;return function(b,j,p){function l(b,h){var i=++q,o,l;v=document.getElementsByTagName("head").item(0);r="JscriptId"+i;s=document.createElement("script");s.setAttribute("type","text/javascript");
s.setAttribute("charset","utf-8");s.setAttribute("src",h);s.setAttribute("id",r);s.onload=s.onreadystatechange=function(){if(!(o||this.readyState!==void 0&&this.readyState!=="loaded"&&this.readyState!=="complete")){o=!0;if(completion!=="undefined"){var h=m(),k=!h||c.inArray(h,F)===-1?e.a9:e.a9Corpus;l=t.getResultsProcessor(k.name).processResults(b,h,completion)}this.onload=this.onreadystatechange=null;try{v.removeChild(s)}catch(j){d.logDebug(j)}a.timingProvider.stopTimer(f,i);h={searchTerm:b,suggestionSets:l};
k=g.createEvent(f,p.suggestionsReady);a.eventBus.trigger(k,h)}};a.timingProvider.startTimer(f,i);v.appendChild(s)}function m(){var k;var b="aps",b=[],b=j.aliases;return k=(b=j.implicitAlias?[j.implicitAlias]:typeof b==="string"?b.split(","):b)&&b.length===1?b[0]:a.suggestionUtils.getAliasWithDeepNodeAliasBacked(j.deepNodeISS),b=k}var q=0,v,r,s,u=new h(j),t=new i(j),F=j.issCorpus||[];a.eventBus.listen(p.a9SuggestionsNeeded,function(b){if(a.suggestionUtils.shouldRequestSuggestions(f,j))if(!b||!b.length){var b=
{searchTerm:b,suggestions:[]},d=g.createEvent(f,p.suggestionsReady);a.eventBus.trigger(d,b)}else{var d=m(),h=!d||c.inArray(d,F)===-1?e.a9:e.a9Corpus;(d=u.getUrlConstructor(h.name).constructUrl(b,d))&&l.call(this,b,d)}},this);return{getName:function(){return f},processResults:t.getResultsProcessor(o.name).processResults}}});window.$Nav.when("$","sx.iss.utils","NavDomApi","sx.iss.DomUtils","sx.iss.SuggestionTypes","sx.iss.Platform","sx.iss.DebugUtils","sx.iss.IssContext").build("sx.iss.A9SuggestionQueryConstructors",
function(c,a,b,g,e,h,i,d){return function(f){function o(a){return{constructUrl:function(){i.logDebugWithTrace("Invalid suggestion type provided: "+a+" when asking for query constructors");return""}}}function k(a){var d=g.getCursorPosition(b.getSearchBox());return d>-1?{q:encodeURIComponent(a.substring(0,d).replace(/^\s+/,"").replace(/\s+/g," ")),qs:encodeURIComponent(a.substring(d))}:{q:encodeURIComponent(a)}}function j(a){var b="?";c.each(a,function(a,d){b+=a+"="+d+"&"});return b}function p(b){var d=
{xcat:f.xcat,cf:f.cf,noCacheIE:a.now()};if(f.fb!==void 0)d.fb=f.fb;if(f.np!==void 0)d.np=f.np;if(f.issPrimeEligible&&c.inArray(b,f.issPrimeEligible)!==-1)d.pf=1,d.fb=0;d.sc=1;return d}var l=f.protocol||window.parent.document.location.protocol||"http:";l==="file:"&&(l="http:");var m={};m[e.a9.name]=new function(){var a=l+"//"+f.src,b={method:"completion",mkt:f.mkt,client:h.cid,x:h.callback};return{constructUrl:function(f,e){var g=c.extend({},b,{"search-alias":e},k(f));h.needExtraParams&&c.extend(g,
p(e));d.getFastlabs()&&c.extend(g,{w:d.getFastlabs()});return a+j(g)}}};m[e.a9Corpus.name]=new function(){var a=l+"//"+f.src.replace("/search","/v2.0"),b={"num-corpus":10,"num-query":5,client:h.cid,m:f.obfMkt,fb:1,xcat:1,method:"completion",cf:0,sc:1,conf:1,x:h.callback};return{constructUrl:function(d,f){var e=c.extend({},b,{"search-alias":f},k(d));return a+j(e)}}};return{getUrlConstructor:function(a){return m.hasOwnProperty(a)?m[a]:new o(a)}}}});window.$Nav.when("$","sx.iss.utils","NavDomApi","sx.iss.DomUtils",
"sx.iss.SuggestionTypes","sx.iss.InfoTypes","sx.iss.DebugUtils","sx.iss.IssContext").build("sx.iss.A9SuggestionResultsProcessors",function(c,a,b,g,e,h,i,d){var f;f="aps";return function(c){function k(a){return{processResults:function(){i.logDebugWithTrace("Invalid suggestion type provided: "+a+" when asking for result processing");return""}}}function j(b,d,f,e,c,g,h){var i=a.suggestionUtils.getPrefixPos(e,f),o;c||i===-1?(f=e,i=o=""):(o=a.suggestionUtils.splitStringForDisplay(e,i,f.length),f=o.bprefix,
i=o.prefix,o=o.suffix);return{type:g,isSpellCorrected:c,bprefix:f,prefix:i,suffix:o,keyword:e,isFirst:h===0,alias:b,store:d,isDeepNode:b!==void 0&&d!==void 0}}function p(a,b,d,f){a.store=b.name;a.alias=b.alias;a.type=d?e.a9XOnly.name:e.a9Xcat.name;a.isFallback=f;return a}function l(a,d,c){d.isFirst=!1;if(c)d.type=e.a9XOnly.name;else if(d.type=e.a9Xcat.name,c=b.getAliasFromDropdown(),c!==f)d.store=b.getCategoryNameFromDropdown(c),d.alias=c,a.push(m(d));d.store=b.getCategoryNameFromDropdown(f);d.alias=
f;a.push(m(d))}function m(a,d){var f={type:a.type,bprefix:a.bprefix,prefix:a.prefix,suffix:a.suffix,keyword:a.keyword,alias:a.alias||d,isSpellCorrected:a.isSpellCorrected,isFallback:a.isFallback,isDeepNode:a.isDeepNode},g;if(f.type===e.a9Xcat.name||f.type===e.a9XOnly.name||f.isDeepNode===!0){if(a.isFirst||!c.noXcats)a.store?g=a.store:a.isFirst&&(g=b.getCategoryNameFromDropdown())}else g=void 0;f.store=g;g=f.alias;var h="/s?k="+encodeURIComponent(a.keyword);typeof g!==void 0&&(h+="&i="+encodeURIComponent(g));
f.url=h;return f}var q={};q[e.a9.name]=new function(){var b=e.a9.name;return{processResults:function(f,h,i){var k=i[1],F=i[2]||[],i=i[3]||[],w=0,q=[],C=[],L,B,E;E=!1;for(var D=0;D<F.length;D++){var x=F[D];if(x.hasOwnProperty("source"))for(var x=x.source,z=0;z<x.length;z++)if(x[z]==="fb"){E=!0;break}}D=!1;for(x=0;x<F.length;x++)if(z=F[x],z.hasOwnProperty("nodes")&&z.nodes.length>0){D=!0;break}if(x=c.hasOwnProperty("cf"))if(x=c.cf){x=!1;for(z=0;z<F.length;z++){var y=F[z];if(y.hasOwnProperty("nodes")&&
y.nodes.length>0&&y.hasOwnProperty("source")&&g.isArray(y.source)&&y.source[0]==="xo"){x=!0;break}}}c.deepNodeISS&&(L=a.suggestionUtils.getDeepNodeAlias(c.deepNodeISS),B=a.suggestionUtils.getDeepNodeCategoryName(L,c.deepNodeISS));z=typeof L!=="undefined";for(y=0;y<k.length;y++){var K=j(L,B,f,k[y],F&&F[y]&&F[y].sc==="1",b,y);E||q.push(m(K,h));if(!c.noXcats&&D){!E&&y===0&&(z||l(C,K,x),(x||!z)&&q.shift());for(var I=F[y],A=I&&I.source&&I.source[0]==="fb",I=I.nodes||[],G=0;G<I.length&&w<4;G++)K=p(K,I[G],
x,A),C.push(m(K,h)),w++}}f={};f[e.a9.name]=q;f[x?e.a9XOnly.name:e.a9Xcat.name]=C;i.length>0&&i[0].hasOwnProperty("t")&&d.addTriggeredFastlabs(i[0].t);return f}}};q[e.a9Corpus.name]=new function(){function b(d,f,g,h,i,l,k){f=j(f,void 0,g,h,i,e.a9Corpus.name,k);if(g=a.suggestionUtils.splitHighlightedString(h))f.bprefix=g.bprefix,f.prefix=g.prefix,f.suffix=g.suffix;h=a.suggestionUtils.removeHighlightMark(h);f.keyword=h;f.text=h;f.url="/dp/"+d+"/"+e.a9Corpus.reftagTemplate+"?ie=utf8&keywords="+encodeURIComponent(h);
if(l)f.primeText=c.primeText;return f}function d(a){for(var b=[],f=0;f<a.length;f++)b.push(a[f].field);return b}return{processResults:function(f,g,i){var k=[],w=[],i=i.suggs,q,C;if(i.length===0)return[];for(var L=i.length,B=0;B<i.length;B++)if(i[B].hasOwnProperty("corpus")){var E=d(i[B].source);if((E.indexOf(h.title)>=0||E.indexOf(h.seasonTitle)>=0)&&i[B].corpus.length>1)i[B].alwaysShowDirector=!0}else{L=B;break}c.deepNodeISS&&(q=a.suggestionUtils.getDeepNodeAlias(c.deepNodeISS),C=a.suggestionUtils.getDeepNodeCategoryName(q,
c.deepNodeISS));for(B=L;B<i.length&&w.length<4;B++){var D=i[B];if(E=D.xcats)for(var x=E.hasOwnProperty("sc")&&E.sc!==0,z=D.hasOwnProperty("fb")&&D.fb!==0,y=0;y<E.length&&w.length<4;y++){var K=w,I=q,A=E[y],G=z,N=B-L+y,H=j(I,C,f,D.sugg,x,e.a9Xcat.name,N),H=p(H,A,!1,G);N===0&&!G&&typeof I==="undefined"?l(K,H):K.push(m(H))}}q=10-w.length;for(B=0;B<L&&k.length<q;B++){D=i[B];C=D.corpus;E=d(D.source);for(y=0;y<C.length&&k.length<10;y++){x=C[y];z=D;K=x.asin_info;I=E;A=f;G="";for(N=0;N<K.length;N++){var M=
K[N],H=M.type,M=M.value;if(H===h.title||H===h.seasonTitle)G+=a.suggestionUtils.markHighlight(A,M[0]);z.alwaysShowDirector&&H===h.director?G+=c.directedByText.replace("{director}",M[0]):I.indexOf(H)>=0&&M.indexOf(z.sugg)>=0&&(M=a.suggestionUtils.markHighlight(A,z.sugg),H===h.actor?G+=c.starringText.replace("{actor}",M):H===h.director&&(G+=c.directedByText.replace("{director}",M)))}z=G;K=x.hasOwnProperty("is_prime")&&x.is_prime===1;k.push(b(x.asin,g,f,z,!1,K,y))}}f={};f[e.a9Corpus.name]=k;f[e.a9Xcat.name]=
w;return f}}};return{getResultsProcessor:function(a){return q.hasOwnProperty(a)?q[a]:new k(a)}}}});window.$Nav.when("$","sx.iss.utils","sx.iss.DepartmentData","NavDomApi","sx.iss.Events").build("sx.iss.DepartmentSuggestionProvider",function(c,a,b,g,e){function h(h,k){function j(n){if(a.suggestionUtils.shouldRequestSuggestions(i,h)){var l={searchTerm:n,suggestionSets:{}},m=[],q=RegExp("\\b"+a.escapeRegExp(n)+"(.*)","i");if(n.length>=d&&g.getKeyword().length===n.length){var v,r,s,u;c.each(b.getData(h),
function(b,d){u=s=r="";if(q.test(d.triggerWords)||q.test(d.store)){d.position=m.length===0?0:m.length+1;var e=a.suggestionUtils.getPrefixPos(d.store,n);e===-1?u=d.store:(v=a.suggestionUtils.splitStringForDisplay(d.store,e,n.length),r=v.bprefix,s=v.prefix,u=v.suffix);d.beforePrefix=r;d.prefix=s;d.suffix=u;m.push(d);if((e=window.ue)&&e.count){var c=i+d.alias.replace("-","");e.count(c,e.count(c)+1)}}if(m.length===f)return!1})}l.suggestionSets[i]=m;var t=e.createEvent(i,k.suggestionsReady);a.eventBus.trigger(t,
l)}}(function(){var b=e.createEvent(i,k.suggestionsNeeded);a.eventBus.listen(b,j)})()}var i="department",d=3,f=3;h.prototype.getName=function(){return i};return h});window.$Nav.when("sx.iss.utils").build("sx.iss.HelpSuggestionProvider",function(c){var a=[{type:"help",pat:/^return/i,text:"Looking for help with returns? Try this.",url:""},{type:"help",pat:/^track/i,text:"Looking for help with tracking? Try this.",url:""},{type:"help",pat:/^gift[\s*]w/i,text:"Looking for help with gift wrapping? Try this.",
url:""},{type:"help",pat:/^canc/i,text:"Looking for help with order cancellation? Try this.",url:""},{type:"help",pat:/^refu[\s*]/i,text:"Looking for help with refund? Try this.",url:""},{type:"help",pat:/^passw[\s*]/i,text:"Looking for help with passwords? Try this.",url:""},{type:"help",pat:/^log(ging\s*)?o/i,text:"Looking for help with logging out? Try this.",url:""}];return function(){this.getName=function(){return"help"};c.eventBus.listen("help-suggestionsNeeded",function(b){var g,e=[];for(g=
0;g<a.length;g++)b.match(a[g].pat)&&e.push(a[g]);c.eventBus.trigger("help-suggestionsReady",{searchTerm:b,suggestions:e})},this)}});window.$Nav.when("$","sx.iss.utils").build("sx.iss.RecentSearchSuggestionProvider",function(c,a){return function(b){var g=/[^\w]/;this.getName=function(){return"recent"};var e=j.createEvent("recent",b.suggestionsNeeded);a.eventBus.listen(e,function(e){var i=[];if(window.sx&&window.sx.searchsuggest&&window.sx.searchsuggest.searchedText){var d=window.sx.searchsuggest.searchedText,
f={},o,k,n,p,l,m,q=!e||!g.test(e)?e:c("<div></div>").text(e).html();for(p=0;p<d.length;p++)if(k=d[p].keywords,o=!k||!g.test(k)?k:c("<div></div>").html(k).text(),n=a.suggestionUtils.getPrefixPosMultiWord(k,q),!f[k]&&a.suggestionUtils.getPrefixPosMultiWord(o,e)!==-1)n===-1?(n=k,m=l=""):(l=a.suggestionUtils.splitStringForDisplay(k,n,q.length),n=l.bprefix,m=l.prefix,l=l.suffix),i.push({type:"recent",spellCor:!1,bprefix:n,prefix:m,suffix:l,keyword:o,originalKeywords:k,deleteUrl:d[p].deleteUrl}),f[k]=1}d=
j.createEvent("recent",b.suggestionsReady);a.eventBus.trigger(d,{searchTerm:e,suggestions:i})},this)}});window.$Nav.when("$","sx.iss.utils","sx.iss.TemplateEngine").build("sx.iss.SuggestionDisplayProvider",function(c,a,b){return function(a,e,h){var i,d;this.getDisplay=function(a){if(i(a))return c.extend(a,h),d(a)};i=typeof a==="string"?function(b){return b.type===a}:a;d=b(e)}});window.$Nav.when("$","sx.iss.utils").build("sx.iss.SuggestionHighlightingProvider",function(c,a){return function(b){function g(a){a=
a.currentTarget.id;f&&f.removeClass(f.attr("data-selected-class"));f=c("#"+a);d=parseInt(a.substr(6));f.addClass(f.attr("data-selected-class"))}function e(a){a=a.currentTarget.id;f&&f.attr("id")===a&&(f.removeClass(f.attr("data-selected-class")),f=void 0,d=-1)}var h=this,i,d=-1,f;a.eventBus.listen(b.suggestionsDisplayed,function(a){var b;i=a;d=-1;f=void 0;for(a=0;a<i.suggestions.length;a++)b=c("#"+i.suggestions[a].suggestionId),b.bind("mouseover",h,g).bind("mouseout",h,e)},this).listen(b.upArrowPressed,
function(){i&&(f&&f.removeClass(f.attr("data-selected-class")),d--,d===-1?a.eventBus.trigger(b.suggestionSelected,{keyword:i.searchTerm}):(d===-2&&(d=i.suggestions.length-1),f=c("#issDiv"+d),f.addClass(f.attr("data-selected-class")),a.eventBus.trigger(b.suggestionSelected,i.suggestions[d])))},this).listen(b.downArrowPressed,function(){i&&(f&&f.removeClass(f.attr("data-selected-class")),d++,d===i.suggestions.length?(d=-1,a.eventBus.trigger(b.suggestionSelected,{keyword:i.searchTerm})):(f=c("#issDiv"+
d),f.addClass(f.attr("data-selected-class")),a.eventBus.trigger(b.suggestionSelected,i.suggestions[d])))},this)}});window.$Nav.when("sx.iss.utils","sx.iss.SuggestionTypes","sx.iss.TemplateEngine").build("sx.iss.IssDisplayProvider",function(c,a,b){return function(g,e,h,i,d){function f(a){c.eventBus.trigger(i.suggestionsNeeded,a)}function o(b){var f=e.sequence(b),b=b.searchTerm,g=p++;c.timingProvider.startTimer("IssDisplayProvider",g);if(f.length===0)c.eventBus.trigger(i.noSuggestions,b);else{for(var o=
h,r=0,s=0;s<f.length;s++){var u=f[s];if(u.type!=="separator")u.suggestionId="issDiv"+r,r++;var t=u,F="";F+=u.isDeepNode===!0?"s-highlight-secondary":"s-highlight-primary";t.cssClasses=F;for(var w,t=0;t<o.length;t++)if(w=o[t],w=k(w,u),w=w.getDisplay(u))break;u.display=w}o=f&&f.length>0&&f[0].type===a.a9Corpus.name&&d.hasOwnProperty("issCorpusSugText");o=j({suggestions:f,suggestionTitle:o?d.issCorpusSugText:d.hasOwnProperty("sugText")?d.sugText:""});c.timingProvider.stopTimer("IssDisplayProvider",g);
c.eventBus.trigger(i.suggestionsReadyForDisplay,{searchTerm:b,display:o,suggestions:f})}}function k(a,b){var d=a;if(a.hasOwnProperty("provider")&&a.hasOwnProperty("partials")){for(d=0;d<a.partials.length;d++){var f=a.partials[d],e=f.provider.getDisplay(b);f.hasOwnProperty("formatter")&&(e=f.formatter.string.replace(f.formatter.toReplace,e));b[f.key]=e}d=a.provider}return d}var j=b(g),p=0;(function(){c.eventBus.listen(i.suggestionsReady,o,this);c.eventBus.listen(["parentFocused","searchTermChanged"],
f,this)})();return{processPartials:k}}});window.$Nav.when("sx.iss.utils","sx.iss.Events").build("sx.iss.ArraySuggestionProvider",function(c,a){return function(b,g){function e(b){for(var e=[],b=b.toLowerCase(),j=0;j<i.length;j++){var l=i[j];if(l.toLowerCase().indexOf(b)!==-1&&e.length<f){var l={term:l,searchTerm:b,url:d[j]},m=c.suggestionUtils.getPrefixPos(l.term,l.searchTerm),m=c.suggestionUtils.splitStringForDisplay(l.term,m,l.searchTerm.length),l={type:o,bprefix:m.bprefix,prefix:m.prefix,suffix:m.suffix,
keyword:l.searchTerm,url:l.url,isExactMatch:l.term===l.searchTerm};e.push(l)}}b={searchTerm:b,suggestionSets:{array:e}};e=a.createEvent(h,g.suggestionsReady);c.eventBus.trigger(e,b)}var h="array",i=b[0],d=b[1],f=10,o="array";(function(){var b=a.createEvent(h,g.suggestionsNeeded);c.eventBus.listen(b,e,this)})();return{name:h}}});window.$Nav.when("$","sx.iss.utils","sx.iss.TimingEvents","sx.iss.TemplateEngine","NavDomApi","sx.iss.SuggestionTypes","sx.iss.ReftagBuilder").build("sx.iss.DesktopSearchBoxEventHandler",
function(c,a,b,g,e,h,i){var d=e.getSearchApi();return function(f){function o(){q=!0;r||(r=!0)}function k(){v=!0}function j(){e.activateSearchBox()}function p(){e.deactivateSearchBox()}a.eventBus.listen(f.selectionChange,function(d){l===void 0&&(l=e.getAliasFromDropdown());if(d.isScrollIntoSearchBox===!0)d=d.previousSearchTerm,e.getIssPrefixElem().remove(),m.val(d),e.getAliasDropdown().val("search-alias="+l).trigger("change");else{var f=a.timingProvider.getTimingWithDisplayLatency(b.latency.group,
b.latency.events.timeToDisplay),f=e.getKeyword()+","+e.getOriginalAlias()+","+f,h=e.getIssPrefixElem();h.length>0?h.attr("value",f):(f=c('<input type="hidden"/>').attr("id","issprefix").attr("name","sprefix").attr("value",f),e.getForm().append(f));var d=d.suggestion,i=d.attr("data-alias"),h=e.getOption(i),f=e.getAliasDropdown(),i="search-alias="+i;h.length===0?(h=d.data("store"),h!==void 0&&h!==""&&f.append(g("s-option",{value:i,store:h}))):i=h.val();f.val(i).trigger("change");e.setKeyword(d.attr("data-keyword"))}});
a.eventBus.listen(f.hideDropdown,function(b){q===!0&&v===!0&&(b.keyCode===27||b.keyCode===13)?(q=v=!1,a.eventBus.triggerThrottledEvent(f.suggestionsNeeded,e.getKeyword())):(e.hideDropdown(),e.getIssPrefixElem().remove(),l=void 0)});a.eventBus.listen(f.suggestionClicked,function(b){var d=b.suggestion;a.eventBus.trigger(f.updateSearchBox,d);b={suggestion:d,searchTerm:e.getKeyword(),previousSearchTerm:b.previousSearchTerm};a.eventBus.trigger(f.selectionChange,b);e.hideDropdown();d.attr("data-type")===
h.a9Corpus.name?(d=d.attr("data-url"),window.location=d.replace(h.a9Corpus.reftagTemplate,(new i).buildFull(b,r))):e.submitForm()});a.eventBus.listen(f.noSuggestions,function(){e.hideDropdown()});a.eventBus.listen(f.suggestionsNeeded,function(){l=e.getAliasFromDropdown()});d===void 0&&(a.eventBus.listen(f.searchBoxFocusIn,j),a.eventBus.listen(f.searchBoxFocusOut,p));d!==void 0?(d.on("compositionstart",o),d.on("compositionend",k)):c("#navbar").delegate("#twotabsearchtextbox","compositionstart",o).delegate("#twotabsearchtextbox",
"compositionend",k);var l,m=e.getSearchBox(),q=!1,v=!1,r=!1;return{getWasCompositionUsed:function(){return r}}}});window.$Nav.when("sx.iss.utils").build("sx.iss.A9SearchSuggestionEventHandler",function(c){return function(a){var b;this.getDelegateReqs=function(){return{selectors:".a9_suggestion,.suggestion_with_query_builder",events:"click"}};this.handleEvent=function(g){var e=g.target||g.srcElement,g=parseInt(g.currentTarget.id.substr(6),10);e.className&&e.className.indexOf("suggest_builder")!=-1?
c.eventBus.trigger(a.updateSearchTerm,b.suggestions[g].keyword):c.eventBus.trigger(a.suggestionClicked,{suggestion:b.suggestions[g]})};c.eventBus.listen(a.suggestionsDisplayed,function(a){b=a},this)}});window.$Nav.when("sx.iss.utils").build("sx.iss.RecentSearchSuggestionEventHandler",function(c){return function(a){function b(b){var e,d,f,g;e=location.protocol+"//"+location.host+b.deleteUrl;d=window.sx.searchsuggest.searchedText;for(f=0;f<d.length;f++)if(d[f].keywords===b.originalKeywords){g=f;break}g!==
-1&&d.splice(g,1);c.eventBus.trigger(a.focusOnParent);var k;window.XMLHttpRequest?k=new XMLHttpRequest:window.ActiveXObject&&(k=new ActiveXObject("Microsoft.XMLHTTP"));if(k&&e)try{k.open("GET",e,!0),k.send(null)}catch(j){}}var g=this,e;this.getDelegateReqs=function(){return{selectors:".recent_search_suggestion",events:"click"}};this.handleEvent=function(h){var i=h.target||h.srcElement,h=parseInt(h.currentTarget.id.substr(6),10);i.className&&i.className.indexOf("iss_sh_delete")!=-1?b.call(g,e.suggestions[h]):
c.eventBus.trigger(a.suggestionClicked,{suggestion:e.suggestions[h]})};c.eventBus.listen(a.suggestionsDisplayed,function(a){e=a},this)}});window.$Nav.when("$","sx.iss.utils","sx.iss.DomUtils","sx.iss.TimingEvents","sx.iss.TemplateEngine","sx.iss.DebugUtils").build("sx.iss.SearchBoxEventHandler",function(c,a,b,g,e,h){var i=[37,38,39,40,91,92,93,192];return function(d,f,e){function g(d){a.eventBus.trigger(e.keydown);var f=d.keyCode,i=f===40,l=f===38,k;if(r.find("#suggestions-template").is(":visible")){if(i||
l){u===void 0&&(u=b.getKeyword(s));var j=r.find(".s-suggestion"),m=j.index(c(".s-selected"));(l=m===0&&l||m+1===j.length&&i)?r.find(".s-suggestion").removeClass("s-selected"):(h.logDebug("highlighting suggestion"),k=r.find(".s-suggestion"),j=k.index(q()),m=k.length,i?(i=-1,j===-1||j===m-1?i=0:j<m&&(i=j+1)):(i=-1,j<1?i=m-1:j<=m&&(i=j-1)),k.eq(j).removeClass("s-selected"),i=k.eq(i),i.addClass("s-selected"),k=i);a.eventBus.trigger(e.selectionChange,{suggestion:k,isScrollIntoSearchBox:l,searchTerm:u,
previousSearchTerm:t});s.val()!==""&&d.preventDefault()}f===13&&(f=q(),f.length>0&&(a.eventBus.trigger(e.suggestionClicked,{suggestion:f,searchTerm:u,previousSearchTerm:t}),d.preventDefault()))}}function j(d){d=d.keyCode;d===13?m(d):d===27?m(d):(u=b.getKeyword(s),u!==t&&i.indexOf(d)===-1&&(u===void 0||u===""?(m(),t=""):(a.eventBus.triggerThrottledEvent(e.suggestionsNeeded,u),t=u)))}function p(){setTimeout(function(){return function(){m();a.eventBus.trigger(e.searchBoxFocusOut)}}(),300)}function l(){a.eventBus.trigger(e.searchBoxFocusIn)}
function m(b){u=void 0;a.eventBus.trigger(e.hideDropdown,{keyCode:b})}function q(){return r.find(".s-suggestion.s-selected")}var v,r,s,u,t;(function(){if(f!==void 0){v=f.$form;r=f.$dropdown;s=f.$searchbox;var a="#"+s.attr("id");v.delegate(a,"focusin",l).delegate(a,"focusout",p).delegate(a,"keydown",g).delegate(a,"keyup",j);t=s.val()}})()}});window.$Nav.when("$","sx.iss.utils","NavDomApi","sx.iss.DomUtils","sx.iss.DebugUtils").build("sx.iss.SuggestionEventHandler",function(c,a,b,g,e){return function(b,
i){i.delegate(".s-suggestion","click",function(d){var f=c(this);e.logDebug("Suggestion clicked",f);a.eventBus.trigger(b.suggestionClicked,{suggestion:f});d.preventDefault()}).delegate(".s-suggestion","mouseover",function(a){g.hoverOverEl(c(a.currentTarget))}).delegate(".s-suggestion","mouseout",function(a){g.hoverOutEl(c(a.currentTarget))})}});window.$Nav.when("$","sx.iss.utils","sx.iss.DebugUtils","sx.iss.DomUtils").build("sx.iss.CustomSearchBoxEventHandler",function(c,a,b,g){return function(e,h,
i){function d(a){k.hide();typeof i.manualOverride==="function"&&(a=i.manualOverride(a),a!==null&&a.length>0&&f(a));c(i.submitId).removeAttr("disabled")}function f(a){o.find(g.hiddenInputClass).remove();a=g.getFormParams(a);b.logDebug("Updating form with params.",a);o.attr("action",a.uri);for(var d="",a=a.formParams,f=0;f<a.length;f++){var e=a[f],c=decodeURIComponent(e.value);d+='<input type="hidden" class="'+g.hiddenInputValue+'" name="'+e.name+'" value="'+c+'"/>'}o.append(d)}var o,k;o=e.$form;k=
e.$dropdown;a.eventBus.listen(h.suggestionClicked,function(a){b.logDebug("Suggestion clicked",a);f(a.suggestion.data("url"));o.submit()});a.eventBus.listen(h.noSuggestions,function(a){d(a)});a.eventBus.listen(h.suggestionsReadyForDisplay,function(a){a.suggestions.length===2&&a.suggestions[1].type==="separator"&&a.suggestions[0].isExactMatch===!0?(a=k.find(g.suggestionClass).eq(0),f(a.data("url"))):a.searchTerm.length>=4?d(a.searchTerm):c(i.submitId).attr("disabled","disabled")});a.eventBus.listen(h.hideDropdown,
function(){k.hide()})}});window.$Nav.when("sx.iss.utils","sx.iss.Events","sx.iss.TimingEvents","sx.iss.MetricsLogger").build("sx.iss.SuggestionAggregator",function(c,a,b,g){return function(e,h){function i(d){c.timingProvider.startTimer(b.latency.group,b.latency.events.timeToDisplay);g.startEndToEndLogging();if(!f[d]){f[d]={remainingProviders:e.length,searchTerm:d,suggestionSets:{}};for(var i=0;i<e.length;i++){var j=a.createEvent(e[i],h.suggestionsNeeded);c.eventBus.trigger(j,d)}}}function d(a){var b=
f[a.searchTerm],a=a.suggestionSets,d;for(d in a)a.hasOwnProperty(d)&&(b.suggestionSets[d]=a[d]);--b.remainingProviders||(delete f[b.searchTerm],c.eventBus.trigger(h.suggestionsReady,b))}var f={};(function(){for(var b=0;b<e.length;b++){var f=a.createEvent(e[b],h.suggestionsReady);c.eventBus.listen(f,d,this)}c.eventBus.listen(h.suggestionsNeeded,i,this)})()}});window.$Nav.when("$","sx.iss.utils","sx.iss.SuggestionTypes").build("sx.iss.SuggestionSequencer",function(c,a,b){return function(c){var e=[b.department.name,
b.a9Corpus.name,b.a9XOnly.name,b.a9Xcat.name,b.a9.name,"array"],h={type:"separator"};this.sequence=function(a){for(var b=a.suggestionSets,a=[],f=0,o=this.isDeepNode(c),k=0;k<e.length;k++){var j=b[e[k]];if(!(typeof j==="undefined"||j.length===0)){for(var p=0;p<j.length&&f<10;p++){var l=j[p];l.dispIdx=a.length;a.push(l);f++}f>0&&!o&&a.push(h)}}o&&(a=this.sequenceDeepNodeResults(a));b=a.length;b>0&&a[b-1].type==="separator"&&a.splice(-1,1);return a};this.isDeepNode=function(b){var d,f;b.deepNodeISS&&
(d=a.suggestionUtils.getDeepNodeAlias(b.deepNodeISS),f=a.suggestionUtils.getDeepNodeCategoryName(d,b.deepNodeISS));return d!==void 0&&f!==void 0};this.sequenceDeepNodeResults=function(a){for(var d,f,e=[],c=0;c<a.length;c++)f=a[c],(d===b.a9Xcat.name||d===b.a9XOnly.name)&&f.type===b.a9.name?e.unshift(f):e.push(f),d=f.type;return e}}});window.$Nav.when("$","sx.iss.utils","sx.iss.Events","NavDomApi").build("sx.iss.MetricsLogger",function(c,a,b,g){function e(){var a=g.isSearchBoxFocused()?o:f;ue.tag(a)}
function h(){uet(j,d,l);uet(n,d,l);uex(p,d,l)}function i(){return typeof uet==="function"&&typeof uex==="function"}var d="iss-init-pc",f="iss-on-time",o="iss-late",j="cf",n="be",p="ld",l={wb:1};i()&&(a.eventBus.listen(b.globals.initializeNavSearchBox,e),a.eventBus.listen(b.globals.issLoaded,h));return{startEndToEndLogging:function(){i()&&uet("bb","iss-end-to-end-a9",l)},stopEndToEndLogging:function(){i()&&(uet(j,"iss-end-to-end-a9",l),uet(n,"iss-end-to-end-a9",l),uex(p,"iss-end-to-end-a9",l))}}});
window.$Nav.when("$","sx.iss.utils","sx.iss.TimingEvents","sx.iss.SuggestionTypes","sx.iss.SearchBoxEventHandler","sx.iss.A9SuggestionProvider","sx.iss.DepartmentSuggestionProvider","sx.iss.SuggestionAggregator","sx.iss.SuggestionDisplayProvider","sx.iss.SuggestionSequencer","sx.iss.IssDisplayProvider","sx.iss.TemplateInstaller","sx.iss.SuggestionEventHandler","sx.iss.DesktopSearchBoxEventHandler","NavDomApi","sx.iss.Events","sx.iss.Reftag","sx.iss.Weblab","sx.iss.DebugUtils","sx.iss.MetricsLogger").build("sx.iss.IssParentCoordinator",
function(c,a,b,g,e,h,i,d,f,o,j,n,p,l,m,q,v,r,s,u){return function(t){function F(a){var b={provider:new f(a.name,a.templateId)};return a===g.a9Xcat||a===g.a9XOnly?c.extend(b,{partials:[{key:"storeHtml",provider:new f(a.name,"s-storeText"),formatter:{string:t.deptText,toReplace:"{department}"}}]}):b.provider}var w,J,C=!1;s.isQIAEnabled()&&c.extend(t,{cf:1});J={$form:m.getForm(),$dropdown:m.getDropdown(),$searchbox:m.getSearchBox()};w=q.createInstance();m.getForm().data("originalSearchTerm",m.getKeyword());
m.getForm().data("originalAlias",m.getAliasFromDropdown());(function(){new e(t,J,w);n.init();var b=[(new h("desktop",t,w)).getName()],c=[F(g.a9),F(g.a9Corpus),new f("separator","s-separator"),F(g.a9Xcat),F(g.a9XOnly)];if(t.hasOwnProperty("isDigitalFeaturesEnabled")&&t.isDigitalFeaturesEnabled===1){c.push(new f(g.department.name,g.department.templateId));var s=new i(t,w);b.push(s.getName())}new j("suggestions-template",new o(t),c,w,t);new d(b,w);a.eventBus.trigger(q.globals.initializeNavSearchBox);
b=new l(w,t);new v(w,t,{shouldAddImeTag:b.getWasCompositionUsed});new p(w,m.getDropdown());new r(t,w)})();a.eventBus.listen(w.suggestionsReadyForDisplay,function(d){C&&(J.$searchbox.val().length===0?s.logDebug('Search term is empty, abort rendering for the search term "'+d.searchTerm+'"'):(m.showDropdown(d.display),a.timingProvider.stopTimer(b.latency.group,b.latency.events.timeToDisplay),u.stopEndToEndLogging(),a.eventBus.trigger(w.suggestionsRendered,d),a.eventBus.trigger(q.globals.suggestionsRendered,
d)))});a.eventBus.listen(w.hideDropdown,function(){C=!1});a.eventBus.listen(w.suggestionsNeeded,function(){C=!0})}});window.$Nav.when("$","sx.iss.utils","sx.iss.SearchBoxEventHandler","sx.iss.SuggestionAggregator","sx.iss.SuggestionDisplayProvider","sx.iss.SuggestionSequencer","sx.iss.IssDisplayProvider","sx.iss.TemplateInstaller","sx.iss.SuggestionEventHandler","sx.iss.Events","sx.iss.DomUtils","sx.iss.ArraySuggestionProvider","sx.iss.CustomSearchBoxEventHandler").build("sx.iss.CustomParentCoordinator",
function(c,a,b,g,e,h,i,d,f,o,j,n,p){return function(l){var m,q;(function(){d.init();m=o.createInstance();var a=l.searchboxId,r=c(l.formId),s=c('<div id="search-dropdown-custom" class="search-dropdown"></div>');r.after(s);q={$form:r,$dropdown:s,$searchbox:c(a)};q.$dropdown.css({width:q.$searchbox.outerWidth()});new b(l,q,m);new f(m,q.$dropdown);new p(q,m,l);l.hasOwnProperty("src")&&j.isArray(l.src)&&(a=new n(l.src,m),new g([a.name],m));a=[new e("array","s-minimal")];new i("suggestions-template",new h(l),
a,m,l)})();a.eventBus.listen(m.suggestionsReadyForDisplay,function(b){q.$dropdown.html(b.display);q.$dropdown.show();a.eventBus.trigger(m.suggestionsRendered,b)});return{dropdownId:"search-dropdown-custom"}}});window.$Nav.importEvent("jQuery",{as:"$",global:"jQuery"});window.$Nav.when("$","sx.iss.utils","sx.iss.Events","sx.iss.A9SuggestionProvider","sx.iss.DepartmentSuggestionProvider","sx.iss.A9SearchSuggestionEventHandler","sx.iss.HelpSuggestionProvider","sx.iss.RecentSearchSuggestionProvider",
"sx.iss.RecentSearchSuggestionEventHandler","sx.iss.SuggestionHighlightingProvider","sx.iss.SuggestionAggregator","sx.iss.SuggestionSequencer","sx.iss.SuggestionDisplayProvider","sx.iss.IssDisplayProvider","sx.iss.IssParentCoordinator","sx.iss.PublicApi","sx.iss.MetricsLogger","sx.iss.CustomParentCoordinator").build("sx.iss",function(c,a,b,g,e,h,i,d,f,o,j,n,p,l,m,q,v,r){g={Events:b,A9SuggestionProvider:g,DepartmentSuggestionProvider:e,A9SearchSuggestionEventHandler:h,HelpSuggestionProvider:i,RecentSearchSuggestionProvider:d,
RecentSearchSuggestionEventHandler:f,SuggestionHighlightingProvider:o,SuggestionAggregator:j,SuggestionSequencer:n,SuggestionDisplayProvider:p,IssDisplayProvider:l,IssParentCoordinator:m,CustomParentCoordinator:r,IssParentCoordinatorMobile:m,SuggestionSequencerMobile:n,isNewIss:!0};c.extend(g,g,q);a.eventBus.trigger(b.globals.issLoaded);return g});window.$Nav.when("sx.iss").run(function(c){window.$Nav.publish("sx.iss",c);window.$Nav.publish("search-js-autocomplete",c)})})})(function(){var A=window.AmazonUIPageJS||
P,j=A.attributeErrors;return j?j("RetailSearchAutocompleteAssets"):A}());
/* ******** */
(function(b){b.execute(function(){function e(d){d.searchCSL=new function(){var c=this,b=[],f=[],e,i,j,g,h=200,k;c.init=function(a,b,d){a&&b&&!e&&(e=a,c.updateRid(b),d&&(h=d))};c.updateRid=function(a){a&&i!=a&&(c.tx(),i=a,j={})};c.addWlt=function(a){if(a){if(a.call&&(a=a(),!a))return;j[a]||(b.push(a),j[a]=1,c.scheduleTx())}};c.addAmabotPrerendered=function(a){a&&a.rid&&a.selections&&a.selections.length&&(f.push(a),c.scheduleTx())};c.scheduleTx=function(){if(h==0)c.tx();else{if(!k){var a=window.onbeforeunload;
window.onbeforeunload=function(b){g&&(window.clearInterval(g),g=void 0);c.tx();k=!1;return a&&a.call?a(b):void 0};k=!0}!g&&h>0&&(g=window.setTimeout(function(){g=void 0;c.tx()},h))}};c.tx=function(){if(b.length||f.length){var a="/mn/search/csl?";b.length&&(a+="rrid="+i+"&cpt="+e+"&ctw="+b.join("|"),b=[]);if(f.length){var c="";d.each(f,function(a,b){c+=b.rid+":";d.each(b.selections,function(a,d){d&&(c+=d+(a!=b.selections.length-1?",":""))});c+=a!=f.length-1?".":""});f=[];c&&(a+=a.charAt(a.length-1)==
"?"?"":"&",a+="amabotSelections="+c)}(new Image).src=a}}};return d.searchCSL}if(window.$Nav){if(!window.$SearchJS)window.$SearchJS=$Nav.make("sx");$SearchJS.importEvent("jQuery",{as:"$",global:"jQuery"});$SearchJS.importEvent("jQuery",{global:"jQuery"});$SearchJS.when("jQuery").run("searchCSL-lib",function(b){b.searchCSL=b.searchCSL||e(b);$SearchJS.publish("search-csl",b.searchCSL)})}else b&&b.when("jQuery").execute(function(d){try{b.register("search-csl",function(){return e(d)})}catch(c){}})})})(function(){var b=
window.AmazonUIPageJS||P,e=b.attributeErrors;return e?e("RetailSearchClientSideLoggingAuiAssets"):b}());
/* ******** */
(function(c){c.execute(function(){(function(){c.register("p13n-sc-math",function(){return Math});c.register("p13n-sc-document",function(){return document});c.register("p13n-sc-window",function(){return window});c.register("p13n-sc-undefined",function(){});var b=function(){return window.P&&window.P.AUI_BUILD_DATE};b()?(c.when("jQuery").register("p13n-sc-jQuery",function(b){return b}),c.when("ready").register("p13n-sc-ready",function(){})):window.amznJQ&&(window.amznJQ.available("jQuery",function(){c.register("p13n-sc-jQuery",
function(){return window.amznJQ.jQuery})}),window.amznJQ.onReady("jQuery",function(){c.register("p13n-sc-ready",function(){})}),window.amznJQ.available("amazonShoveler",function(){c.register("p13n-sc-amznJQ-shoveler",function(){})}));c.when("p13n-sc-window").register("p13n-sc-util",function(d){var i=d.ueLogError;typeof i!=="function"&&(i=function(b,d){if(d&&d.message)throw Error(d.message);if(b&&b.message)throw Error(b.message);});var g=function(b,d){i({logLevel:b,attribution:"P13NSharedSitewideJS",
message:"[p13n-sc] "+d})};return{constants:{DATA_ATTR_P13N_FEATURE_NAME:"p13nFeatureName"},count:d.ue&&d.ue.count||function(){},isAUI:b,log:{warn:function(b){g("WARN",b)},error:function(b){g("ERROR",b)}}}})})();c.when("p13n-sc-jQuery","p13n-sc-window","p13n-sc-undefined").register("p13n-sc-heartbeat",function(b,d,i){var g=d.clearInterval,f={},l,c,a=function(){if(!l){var a=d.setInterval(function(){var b=a,d=(new Date).getTime();b!==l?g(b):((!c||d-c>200)&&h(),c=(new Date).getTime())},200);l=a}},h=function(){b.each(f,
function(a,b){b.call(d)})};return{subscribe:function(b,e){f[b]||(f[b]=e,a())},unsubscribe:function(a){f[a]&&delete f[a];var a=!0,b;for(b in f)f.hasOwnProperty(b)&&(a=!1);a&&(g(l),l=i)}}});c.when("p13n-sc-jQuery","p13n-sc-heartbeat").register("p13n-sc-call-on-visible",function(b,d){var i=[],c=b(window),f=function(){for(var b=c.scrollTop()+c.height(),f=c.scrollLeft()+c.width(),a=i.length-1;a>=0;a--){var h=i[a],j=h.callback,e=h.$element,p=h.distanceY,h=h.distanceX;if(e.parents("body").size()===0)i.splice(a,
1);else if(!e.is(":hidden")){var n=e.offset();b-p>n.top&&f-h>n.left&&(j.call(null,e[0]),i.splice(a,1))}}i.length===0&&d.unsubscribe("p13n-sc-call-on-visible")};return{register:function(l,c,a){var h=a&&typeof a.distance!=="undefined"?a.distance:0,j=a&&typeof a.distanceY!=="undefined"?a.distanceY:h,e=a&&typeof a.distanceX!=="undefined"?a.distanceX:0;b(l).each(function(){i.push({$element:b(this),callback:c,distanceY:j,distanceX:e})});d.subscribe("p13n-sc-call-on-visible",f);f()}}});c.when("A","jQuery",
"p13n-sc-call-on-visible","p13n-sc-util","p13n-sc-math").register("p13n-sc-view-trigger",function(b,d,i,g,f){var l=function(a){var h=d(a),a=h.attr("data-params"),j=h.attr("data-url");if(a&&j){var a=b.parseJSON(a),e=h.offset(),h=[e.top,e.left,h.height(),d(window).width()];a.elementRect=h.join(",");var i=0,l={cache:!0,crossDomain:!1,data:d.param(a,!1),error:function(a){a=a.status||0;i>=3||a>=400&&a<500||setTimeout(c,200*f.pow(2,i))},global:!1,url:j},c=function(){i+=1;d.ajax(l)};c()}},k=function(a){var f=
d(a);if(f.size()===1){var j=f.attr("data-params"),j=j?b.parseJSON(j):{};if(!(j.allowEmpty!==!0&&d.trim(f.text()).length===0)){var e=f.height();if(!(j.allowEmpty!==!0&&e<5)){e=0;if(typeof j.distance==="number")e=j.distance;f.attr("data-p13n-sc-vt-initialized")||(f.attr("data-p13n-sc-vt-initialized",!0),i.register(a,function(){l(a)},{distance:e}))}}}},g=function(){b.each(d(".p13n-sc-vt:not([data-p13n-sc-vt-initialized])"),function(a){k(a)})};c.execute(g);c.when("afterReady").execute("p13n-sc-view-trigger:init",
g);return{initializeElement:k}});c.when("p13n-sc-jQuery","p13n-sc-util","p13n-sc-window","p13n-sc-document","p13n-sc-ready").register("p13n-sc-logger",function(b,d,i,c){function f(a){return a.join("")}function l(a,b){var e=a.attr(b),j={};e!==void 0&&e!==null&&(j=typeof i.JSON!=="undefined"?JSON.parse(e):eval("("+e+")"));return j}function k(a,e){for(var j=[a.widget,":"],d=0;d<a.asins.length;d++){var h=a.asins[d];j.push(h.asin,"@");b.each(h,function(a,m){a!=="asin"&&j.push(a,"=",m,"|")});j.splice(j.length-
1,1);j.push(",")}a.asins.length>0&&j.splice(j.length-1,1);e&&(j.push(":","action=",a.action),b.each(a.meta,function(a,m){j.push(",",a,"=",m)}));return f(j)}function a(a,e){var j=l(b(e),"data-p13n-asin-metadata");if(j&&j.asin){var d=j.asin,f=l(b(a),"data-p13n-asin-metadata");f&&b.extend(!0,j,f[d]);return j}}function h(a,j){var h=new Image;d.count("p13n:logger:attempt",1);h.onerror=function(){e++;d.count("p13n:logger:error",1)};h.src=f(["https:"===c.location.protocol?"https://":"http://",i.ue_furl||
"fls-na.amazon.com","/1/","p13n-shared-components","/1/OP/p13n/",j,f(["?",b.param(l(b(a.featureElement),"data-p13n-global"))])])}function j(){return e>3?(p||(d.log.warn("impression image load failed too many times, no longer logging impressions"),d.count("p13n:logger:abort",1),p=!0),!0):!1}var e=0,p=!1,n={},o={},q={logAction:function(m){if(!j())if("featureElement"in m)if("action"in m){var e=b(m.featureElement);m.asins=b.map(b(m.featureElement).find(".p13n-asin").filter(":visible"),function(m){return a(e,
m)});m.meta=m.meta||{};var i=l(e,"data-p13n-feature-metadata");b.extend(!0,m.meta,i);m.widget=e.attr("data-p13n-feature-name");m.widget in n||(n[m.widget]={});for(var c=i=0;c<m.asins.length;c++)m.asins[c].asin in n[m.widget]||(n[m.widget][m.asins[c].asin]=!0,i++);m.logOnlyOnNew&&i===0||(i=f(["action/",f([m.widget,"_:",m.action,"@v=",m.eventtime||0,",impressed@v=",i]),"/",k(m,!0)]),m.replicateAsinImpressions&&(c=f(["asin/",k(m,!1)]),i=f(["batch/",i,"$",c])),h(m,i))}else d.log.warn("action missing in eventData for logAction");
else d.log.warn("featureElement missing in eventData for logAction")},logAsyncAction:function(a){var j=(new Date).getTime(),e=typeof a.initialDelay==="number"?a.initialDelay:400,f=typeof a.timeout==="number"?a.timeout:5E3,d=b(a.featureElement);a.widget=d.attr("data-p13n-feature-name");a.widget in o&&i.clearTimeout(o[a.widget]);var h=function(){var b=a.isEventComplete(),e=(new Date).getTime();if(e-j<f&&!b)o[a.widget]=i.setTimeout(h,150);else{if(!b){if(!("meta"in a))a.meta={};a.meta.err="notfinished"}a.eventtime=
e-j;delete o[a.widget];q.logAction(a)}};o[a.widget]=i.setTimeout(h,e)},eventPending:function(a){return b(a).attr("data-p13n-feature-name")in o},impressAsin:function(m){if(!j())if("featureElement"in m)if("faceoutElement"in m){var e=b(m.faceoutElement),i=b(m.featureElement);m.widget=i.attr("data-p13n-feature-name");m.asins=[a(i,e)];e=f(["asin/",k(m,!1)]);h(m,e)}else d.log.warn("faceoutElement missing in eventData for logAction");else d.log.warn("featureElement missing in eventData for logAction")}};
return q});c.when("jQuery","A","p13n-sc-call-on-visible","p13n-sc-logger","ready").register("p13n-sc-faceout-logger",function(b,d,i,c){var f=function(f,d){var a=b(f),h=b(d);a.length===1&&!a.attr("data-p13n-sc-fl-initialized")&&(a.attr("data-p13n-sc-fl-initialized",!0),i.register(a,function(){c.impressAsin({featureElement:h,faceoutElement:a})}))};d.on("p13n:faceoutsloaded",function(d){b(d).find(".p13n-asin:not([data-p13n-sc-fl-initialized])").each(function(b,a){f(a,d)})})});c.when("A","jQuery").register("p13n-sc-lazy-image-loader",
function(b,d){return{loadImages:function(i){b.executeDeferred();i.find(".p13n-sc-lazy-loaded-img").each(function(i,f){var c=d(f),k=c.find(".a-dynamic-image");k.load(function(){c.removeClass("p13n-sc-lazy-loaded-img")});b.loadDynamicImage(k)})}}});c.when("p13n-sc-jQuery","p13n-sc-util","p13n-sc-math","p13n-sc-line-truncator-settings").register("p13n-sc-line-truncator",function(b,d,i,c){function f(a){this.$element=a;this.$experimentElement=b("<div>").addClass("p13n-sc-offscreen-truncate");this.maxRows=
a.attr("data-rows");this.lineHeight=c.lineHeight;this.maxRows||d.log.error("Truncation element missing necessary line number data")}var l=/(?=[ \-\/])/,k=/[^\/\-\[\]():\s]/;f.prototype.truncate=function(){var a=this.$element.html(),a=b.trim(a);this.$element.append(this.$experimentElement);if(!this.checkLineFit(a)){var f=this.truncateByToken(a);f?(this.$element.html(f),this.$element.attr({title:a})):d.log.error("Unable to successfully truncate line "+a)}this.$experimentElement.remove()};f.prototype.checkLineFit=
function(a){this.$experimentElement.html(a);a=this.$experimentElement.get(0).clientHeight/this.lineHeight;return i.round(a)<=this.maxRows};f.prototype.truncateByToken=function(a){for(var a=a.split(this.getTokenSeparatorRegex()),b=1,j=a.length,e,f,d=0;b!==j;)if(e=i.floor((j+b)/2),f=a.slice(0,e).join("")+"&hellip;",this.checkLineFit(f)){if(j-e<=1){for(d=e;d>0&&!k.test(a[d-1]);)d--;break}b=e}else j=e;return d===0?void 0:a.slice(0,d).join("")+"&hellip;"};f.prototype.getTokenSeparatorRegex=function(){return this.$element.attr("data-truncate-by-character")?
"":l};return{truncateLines:function(a){a.find(".p13n-sc-truncate").each(function(){var a=new f(b(this));a&&(a.truncate(),b(this).addClass("p13n-sc-truncated").removeClass("p13n-sc-truncate"))})}}});c.register("p13n-sc-line-truncator-settings",function(){return{lineHeight:19}});c.when("A","jQuery","a-carousel-framework","p13n-sc-call-on-visible","p13n-sc-logger","p13n-sc-util","ready").execute("p13n-sc-carousel-logger",function(b,d,i,c,f,l){function k(a,b){var h=a.getAttr("pageNumber"),c=a.dom.$container;
c.data("p13nPreviousPage",h);f.logAsyncAction(d.extend(!0,{},{featureElement:c,isEventComplete:function(){return c.find(".a-carousel-card-empty").size()===0&&!a.getAttr("animating")},meta:{p:h},replicateAsinImpressions:!0},b))}function a(a){h(a)&&c.register(a.dom.$container,function(){k(a,{action:"view"})})}var h=function(a){return typeof a==="undefined"?!1:a.dom.$container.data(l.constants.DATA_ATTR_P13N_FEATURE_NAME)?!0:!1};b.each(i.getAllCarousels(),function(b){b.dom.$container.hasClass("a-carousel-initialized")&&
a(b)});b.on("a:carousel:init",function(b){a(b.carousel)});d(document).delegate(".a-carousel-container[data-p13n-feature-name] .a-carousel-goto-nextpage","click",function(a){a=i.getCarousel(a.target);k(a,{action:"shovel_right"})});d(document).delegate(".a-carousel-container[data-p13n-feature-name] .a-carousel-goto-prevpage","click",function(a){a=i.getCarousel(a.target);k(a,{action:"shovel_left"})});d(document).delegate(".a-carousel-container[data-p13n-feature-name] .a-carousel-restart","click",function(a){a=
i.getCarousel(a.target);k(a,{action:"start_over",meta:{op:a.dom.$container.data("p13nPreviousPage")}})});b.on("a:carousel:change:pageSize",function(a){a=a.carousel;h(a)&&a.dom.$container.hasClass("a-carousel-initialized")&&k(a,{action:"resize",logOnlyOnNew:!0})})});c.when("p13n-sc-jQuery","p13n-sc-window","p13n-sc-document","p13n-sc-call-on-visible","p13n-sc-logger","p13n-sc-util","p13n-sc-amznJQ-shoveler").register("p13n-sc-non-aui-carousel",function(b,d,i,g,f,l){var k=function(a){l.count("p13n-sc-non-aui-carousel:init",
1);var e=a.attr("data-widgetname"),h=b("#"+e+"Data");if(h.length!==1)return!1;if(a.attr("data-p13n-sc-carousel-initialized"))return!1;else a.attr("data-p13n-sc-carousel-initialized",!0);var c=h.text().split(","),i=a.find(".shoveler-content > ul"),g="input#"+e+"ShvlState",m=function(){},k=200,u=!1,w=function(){var m=k;a.find(".p13nimp, .p13n-asin").each(function(){var a=b(this).outerHeight(!0);a>m&&(m=a)});m>k&&(k=m,i.animate({height:m},200,"linear"));u||x()},x=function(){var b=k/2;a.find("a.next-button, a.back-button").css("top",
b);u=!0},r=a.find(".shoveler").shoveler(function(a,m){var e="",e=typeof d.JSON!=="undefined"?JSON.parse(h.attr("data-ajax")):eval("("+h.attr("data-ajax")+")");e.asins=c.slice(a,a+m).join(",");e.count=m;e.offset=a;e=b.param(e);return h.attr("data-url")+"?"+e},c.length,{cellTransformer:function(a){return a===null?"":a},cellChangeSpeedInMs:30,preloadNextPage:!0,prevButtonSelector:"a.back-button",nextButtonSelector:"a.next-button",startOverSelector:"span.start-over",startOverLinkSelector:"a",horizPadding:14,
state:{ready:function(){return b(g).val().length>0},get:function(){return parseInt(b(g).val(),10)},set:function(a){b(g).val(a)}},onUpdateUIHandler:function(){w();m()}}),v=0,y=function(){var a=b(d).width();v!==a&&(r.updateUI(),v=a)},t=null;a.resize(function(){t&&d.clearTimeout(t);t=d.setTimeout(y,100)});var s=function(m){f.logAsyncAction(b.extend(!0,{},{featureElement:a,isEventComplete:function(){return a.find("li.shoveler-cell.shoveler-progress").size()===0},replicateAsinImpressions:!0},m))};s({action:"view",
meta:{p:r.getCurrentPage()+1}});a.find(".back-button").click(function(){s({action:"shovel_left",meta:{p:r.getCurrentPage()+1}})});a.find(".next-button").click(function(){s({action:"shovel_right",meta:{p:r.getCurrentPage()+1}})});a.find(".start-over-link").mousedown(function(){s({action:"start_over",meta:{p:1,op:r.getCurrentPage()+1}})});m=function(){f.eventPending(a)||s({action:"resize",page:r.getCurrentPage()+1,logOnlyOnNew:!0,initialDelay:2E3})}},a=function(a){var e={distanceY:-250,distanceX:0};
b(a).find(".p13n-sc-nonAUI-carousel").andSelf().filter(".p13n-sc-nonAUI-carousel").each(function(a,d){g.register(d,function(){k(b(d))},e)})},h=function(){a(i)};h();c.when("p13n-sc-ready").execute("p13n-sc-non-aui-carousel:readyInit",h);return{init:a}});c.when("p13n-sc-jQuery","p13n-sc-util").execute("p13n-sc-carousel-initialization-setup",function(b,d){d.isAUI()?c.when("a-carousel-framework").register("p13n-sc-carousel-init",function(b){return{init:function(){b.createAll()}}}):c.when("p13n-sc-non-aui-carousel").register("p13n-sc-carousel-init",
function(b){return{init:function(d){b.init(d)}}})})})})(function(){var c=window.AmazonUIPageJS||P,b=c.attributeErrors;return b?b("P13NSharedSitewideJS"):c}());
/* ******** */
(function(c){c.execute(function(){c.when("jQuery","afterLoad","socratesEnabled").register("socr-nav-bootstrap",function(d){function e(a){d.ajax({url:"//"+a+"/gp/socrates/assets/bootstrap-digest",dataType:"json"}).done(function(b){if(b&&b.digest&&d.type(b.digest)==="string"&&(b=b.digest.trim(),b.match(f))){var e="//"+a+"/gp/socrates/assets/bootstrap";b.match(f)&&c.load.js(e+"-"+b+".js")}})}var f=/[a-z0-9]{32}/;c.execute(function(){d.ajax({url:"/gp/socrates/bootstrap/assetdomain",dataType:"json"}).done(function(a){a&&
a.domain&&d.type(a.domain)==="string"&&(a=a.domain.trim(),e(a))})})})})})(function(){var c=window.AmazonUIPageJS||P,d=c.attributeErrors;return d?d("SocratesNavBootstrap"):c}());
/* ******** */
