jQuery.imageBlockUtils=(function(){var $=jQuery,utils={},options,colorToVideo,captionTimeout,mainImageWidget,mainImage,unavailable,mainImageCaption;
function getAvailableWidth(){return(window.innerWidth||document.body.offsetWidth)-(options.altsOnLeft?0:1);
}function resizeCallback(){var size=utils.getStretchyGoodnessSize();
$(document).trigger("stretchy-goodness",{size:size});
}function fetchChildVideos(color){var obj=options.colorToAsin[color];
if(!(obj&&obj.asin)){return;
}$.ajax({url:"/gp/product/features/apparel-main-image/videos.html",data:{asin:obj.asin,productGroupID:options.productGroupID,useAiryVideoPlayer:true,useChromelessVideoPlayer:options.useChromelessVideoPlayer},dataType:"json",timeout:4000,async:false,success:function(data){if(data){colorToVideo[color]=data;
$.imageBlock.changeColor(color);
}}});
}function getImageTypeAndIndex(color,index){var type="unknown";
var numAlts=colorImages[color].length;
if(index<numAlts){type="image";
}else{index=index-numAlts;
var numVids=utils.getVideos(color).length;
if(index<numVids){type="video";
}else{index=index-numVids;
var numCIU=options.customerImages.length;
if(index<numCIU){type="ciu";
}}}return{type:type,index:index};
}utils.isArray=function(obj){return Object.prototype.toString.call(obj)==="[object Array]";
};
utils.resizeCallback=resizeCallback;
utils.getImageTypeAndIndex=getImageTypeAndIndex;
utils.getStretchyGoodnessSize=function(){var w=getAvailableWidth();
if(options.stretchyGoodnessWidth){var sz=0;
var widthLimit=options.stretchyGoodnessWidth.length;
for(;
sz<widthLimit&&w>=options.stretchyGoodnessWidth[sz];
sz++){}return sz;
}return 0;
};
utils.getVideos=function(color){if(options.useChildVideos){if(!colorToVideo[color]){colorToVideo[color]=[];
fetchChildVideos(color);
}return colorToVideo[color];
}return options.videos;
};
utils.clientScreenData=function(){var h=(typeof window.innerHeight!="undefined"?window.innerHeight:document.body.offsetHeight);
var w=(typeof window.innerWidth!="undefined"?window.innerWidth:document.body.offsetWidth);
return{browserHeight:h,browserWidth:w};
};
utils.getThumbnailIndex=function(thumb,thumbnails){if(options.alwaysIncludeVideo){var jqThumb=$(thumb);
var index=jqThumb.data("index");
if(index!=null){return index;
}index=jqThumb.attr("data-index");
if(index!=null){return parseInt(index);
}}else{return $.inArray(thumb,thumbnails);
}return null;
};
utils.splitByType=function(color,index,imageCallback,videoCallback,ciuCallback){var obj=getImageTypeAndIndex(color,index);
var type=obj.type,i=obj.index;
switch(type){case"image":return imageCallback(color,i);
case"video":return videoCallback(color,i);
case"ciu":return ciuCallback(i);
default:return{};
}};
utils.getColorFromState=function(variationsState){if(!variationsState){return;
}var colorName="";
var variationLabels=DetailPage.StateController.getState()["variation_display_labels"];
$.each(options.visualDimensions,function(i,dim){var label=(options.gIsNewTwister==1)?dim:variationLabels[dim];
if(variationsState[label]){colorName+=" "+variationsState[label];
}});
return colorName&&colorName.substring(1);
};
utils.isBuyableVariation=function(dpState){if(!dpState.current_hovered_asin){var numDims=dpState.num_variation_dimensions;
return dpState.num_dimensions_selected!=numDims&&dpState.num_dimensions_hovered!=numDims;
}return true;
};
utils.showUnavailable=function(color){if(options.numColors>1&&color&&color!=""){unavailable.show();
unavailable.find(".text-no-color").hide();
unavailable.find(".text-color").show();
unavailable.find(".color").html(color);
}else{if(options.numColors<=0){unavailable.show();
unavailable.find(".text-no-color").show();
unavailable.find(".text-color").hide();
}}unavailable.removeClass("item-not-buyable");
unavailable.find(".wrapper").removeClass("not-buyable");
unavailable.find(".item-not-available").hide();
};
utils.hideUnavailable=function(){unavailable.hide();
unavailable.find(".text-no-color,.text-color").hide();
unavailable.removeClass("item-not-buyable");
unavailable.find(".wrapper").removeClass("not-buyable");
unavailable.find(".item-not-available").hide();
};
utils.showItemUnavailable=function(allVariations){unavailable.addClass("item-not-buyable").show();
unavailable.find(".wrapper").addClass("not-buyable");
unavailable.find(".text-no-color,.text-color").hide();
unavailable.find(".item-not-available").show();
var allVariationsHtml="<br>";
for(var key in allVariations){allVariationsHtml+=key+": "+allVariations[key]+"<br>";
}unavailable.find(".all-variations").html(allVariationsHtml);
};
utils.setImageCaption=function(color,index,timeout){if(captionTimeout){clearTimeout(captionTimeout);
}captionTimeout=null;
if(timeout){captionTimeout=setTimeout(function(){utils.setImageCaption(color,index);
},timeout);
}function imageCallback(c,i){if(magnifier){if(magnifier.isEngaged()&&options.useIV){return options.staticStrings["clickToExpand"];
}else{if(options.useIV&&!options.useHoverZoom){return options.staticStrings["clickToExpand"];
}else{if(colorImages[c][i].hiRes&&options.useHoverZoom){if(options.hoverZoomIndicator&&options.useHoverZoomIpad){return"<img src='"+options.staticImages.hoverZoomIcon+"'/>&nbsp;"+options.staticStrings["touchToZoom"];
}else{if(options.useHoverZoomIpad){return options.staticStrings["touchToZoom"];
}else{if(options.hoverZoomIndicator){return"<img src='"+options.staticImages.hoverZoomIcon+"'/>&nbsp;"+options.staticStrings["rollOverToZoom"];
}else{return options.staticStrings["rollOverToZoom"];
}}}}}}}}function videoCallback(c,i){if(!options.useChromelessVideoPlayer){return options.staticStrings["playVideo"];
}}function ciuCallback(i){return options.customerImages[i].caption;
}var caption=utils.splitByType(color,index,imageCallback,videoCallback,ciuCallback)||"&nbsp;";
mainImageCaption.html(caption);
};
utils.fixIE=function(){if($.browser.msie){mainImage.get(0).className=mainImage.get(0).className;
}};
utils.init=function(opts){utils.options=options=opts;
if(options.stretchyGoodnessWidth){if(window.imageBlockSize&&window.imageBlockSize>options.stretchyGoodnessWidth.length){options.stretchyGoodnessWidth=options.widths;
}resizeCallback();
if(window.ImageBlockWeblabs&&window.ImageBlockWeblabs.swipe&&options.useHoverZoomIpad){$(window).bind("orientationchange",resizeCallback);
}else{$(window).resize(resizeCallback);
}}colorToVideo={};
colorToVideo[options.defaultColor]=options.videos;
mainImageWidget=$("#main-image-widget");
mainImage=mainImageWidget.find("#main-image");
unavailable=mainImageWidget.find("#main-image-unavailable");
mainImageCaption=mainImageWidget.find("#main-image-caption");
return utils;
};
utils.flashNotInstalled=false;
utils.embedAiryForChromelessPlayback=function(holder,videoHash,config,contextName,bindings){var foresterMetadataParams=$.extend({},config.foresterMetadataParams);
if(contextName){foresterMetadataParams.method+="."+contextName;
}var instance=Airy.embed({isShowFirstFrameWhenReadyEnabled:true,parentElement:holder[0],streamingUrls:videoHash.url,swfUrl:config.swfUrl,foresterMetadataParams:foresterMetadataParams,backgroundColor:"transparent",flashParams:{wmode:"transparent"},experiments:{supportChromelessPlayback:true},bindings:{playing:function(){holder.css("z-index",8);
},videounsupported:function(){utils.flashNotInstalled=true;
if(bindings&&bindings.videounsupported){bindings.videounsupported(contextName);
}},error:function(){if(bindings&&bindings.error){bindings.error(contextName);
}},ended:function(){instance.seek(0);
if(bindings&&bindings.ended){bindings.ended(contextName);
}}}});
return instance;
};
utils.embedAiryForChromefulPlayback=function(holder,videoHash,config,contextName,bindings){var foresterMetadataParams=$.extend({},config.foresterMetadataParams);
if(contextName){foresterMetadataParams.method+="."+contextName;
}var instance=Airy.embed({parentElement:holder[0],streamingUrls:videoHash.url,contentId:videoHash.mediaObjectId,contentMinAge:Number(videoHash.minimumAge||"")||0,contentTitle:videoHash.title,swfUrl:config.swfUrl,foresterMetadataParams:foresterMetadataParams,slateImages:{preloadSlate:videoHash.slateUrl,postMediaSlate:videoHash.slateUrl},videoAds:config.videoAds,bindings:{videounsupported:function(){utils.flashNotInstalled=true;
if(bindings&&bindings.videounsupported){bindings.videounsupported(contextName);
}},error:function(){if(bindings&&bindings.error){bindings.error(contextName);
}},ended:function(){if(bindings&&bindings.ended){bindings.ended(contextName);
}}}});
adjustAiryVolumeFromConfig(instance,config);
return instance;
};
utils.loadMediaIntoAiryAndSetVolume=function(airyInstance,videoHash,config){if(!airyInstance){return;
}if(airyInstance.getMediaSourceInfo()===videoHash.url){return;
}airyInstance.loadMedia({mediaSourceInfo:videoHash.url,contentId:videoHash.mediaObjectId,contentMinAge:Number(videoHash.minimumAge||"")||0,contentTitle:videoHash.title,slateImages:{preloadSlate:videoHash.slateUrl,postMediaSlate:videoHash.slateUrl}});
adjustAiryVolumeFromConfig(airyInstance,config);
};
function adjustAiryVolumeFromConfig(airyInstance,config){if(!airyInstance||config.volume==null){return;
}airyInstance.setVolume(config.volume);
config.volume=null;
}return utils;
})();
amznJQ.declareAvailable("imageBlockUtils");
if(!window.Softlines){window.Softlines={};
}window.Softlines.ClientLogger=function(feature,forceUpload){var self=this,data={},vips={"www.amazon.com":"fls-na","devo":"fls-devo.vipinteg"};
self.logSingleton=function(key){data[key]=1;
};
self.logHit=function(key){if(!data[key]){data[key]=1;
}else{data[key]++;
}};
self.logKeyValuePair=function(key,value){data[key]=value;
};
self.deleteKey=function(key){if(data[key]){delete data[key];
}};
self.startTimer=function(key){data[key]=+new Date();
};
self.endTimer=function(key){if(data[key]){data[key]=+new Date()-data[key];
}};
self.upload=function(){var protocol=location.protocol=="https:"?"https://":"http://",vip=vips[location.host]||vips.devo,url=protocol+vip+".amazon.com/1/softlines/1/OP/"+feature+"?"+jQuery.param(data)+"&_="+(+new Date());
(new Image()).src=url;
};
if(forceUpload){jQuery(window).unload(function(){self.upload();
});
}};
amznJQ.declareAvailable("SoftlinesClientLogger");
amznJQ.available("imageBlockUtils",function(){amznJQ.available("SoftlinesClientLogger",function(){amznJQ.available("Airy",function(){function ImageBlock(options){var $=jQuery,self=this,logger=null,utils=$.imageBlockUtils.init(options),color=options.defaultColor,variant=0,size=utils.getStretchyGoodnessSize(),mainImageWidget=$("#main-image-widget"),mainImageWrapper=mainImageWidget.find("#main-image-wrapper"),imageHolder=mainImageWrapper.find("#holderMainImage"),mainImage=mainImageWidget.find("#main-image").removeAttr("width").removeAttr("height"),thumbnails=mainImageWidget.find(".thumbs .border"),currentHolder=imageHolder,isIVAvailable=false,isMagnifierLoaded=false,videoSizes=options.videoSizes,defaultColor=options.defaultColor,useIV=options.useIV,useChromelessVideoPlayer=options.useChromelessVideoPlayer,isIpad=navigator.userAgent.match(/ipad/i),isAndroid=navigator.userAgent.match(/cloud9|android|silk-accelerated/i),thumbMouseOverTriggered=0,logMetrics=options.logMetrics?true:false,immersiveView,videoAvailLogged={},changeColorCall={},clientScreen=utils.clientScreenData(),colorClickedLogged={},videoDownloadedTriggered=0,videoPlaying=0,cfEndTimer=options.cfEndTimer,videoReadyTriggered=0,srcLogged={},numAlts=0,airyInstance=null,airyConfig=options.airyConfig,videoContainer=null;
function updateMainImage(c,index){var imageHash=colorImages[c][index],src;
if(imageHash.main[size]){src=imageHash.main[size];
}else{src=imageHash.main[imageHash.main.length-1];
}mainImage.attr("src",src);
utils.fixIE();
}function previewColor(c,index){if(index<colorImages[c].length){updateMainImage(c,index);
hideAllHolders();
imageHolder.show();
}else{magnifier.disengageMagnifier();
hideAllHolders();
if(currentHolder.hasClass("image")||currentHolder.hasClass("ciu")){currentHolder.show();
}else{if(currentHolder.hasClass("video")){changeVideoVariant(c,index);
}}}utils.setImageCaption(c,index);
}self.shakeIt=function(){var overflow=mainImageWrapper.css("overflow");
mainImageWrapper.css("overflow","hidden");
var position=imageHolder.css("position");
imageHolder.css("position","relative");
imageHolder.animate({left:"-=50px"},800,function(){imageHolder.animate({left:"+=50px"},800,function(){mainImageWrapper.css("overflow",overflow);
imageHolder.css("position",position);
});
});
};
self.showImage=function(move){if(!thumbnails.length||!(move=="next"||move=="previous")){return;
}var cst=jQuery("#thumbs-image .border.selected");
if(typeof cst==="undefined"||(cst&&cst.length==0)){return;
}var csti=$.inArray(cst[0],thumbnails);
if(csti==-1){return;
}var nsti=0;
if(move=="next"){nsti=(csti+1)%thumbnails.length;
}if(move=="previous"){nsti=(csti-1+thumbnails.length)%thumbnails.length;
}if(typeof thumbnails[nsti]!=="undefined"){$("#main-image-wrapper").animate({opacity:0},300,function(){$(thumbnails[nsti]).trigger("mouseover");
$("#main-image-wrapper").animate({opacity:1},300);
});
}};
self.changeColor=function(c){var selectedVariant=0;
if(options.autoplayVideo&&!isAndroid){c=defaultColor;
selectedVariant=colorImages[c].length;
}else{if(c==color){selectedVariant=variant;
}}if(c&&(!colorImages[c]||colorImages[c]<=0)){utils.showUnavailable(c);
color=defaultColor;
}else{utils.hideUnavailable();
color=c;
}var thumbs=mainImageWidget.find(".thumbs").empty();
var numAlts=0;
var videoSet=utils.getVideos(color);
if(logMetrics&&options.useChromelessVideoPlayer&&options.useChildVideos&&changeColorCall[color]){var obj=options.colorToAsin[color];
if(obj&&obj.asin&&!videoAvailLogged[obj.asin]){var videoStatus=(videoSet.length>0)?"videoFound":"videoMissing";
logger.logHit(videoStatus);
logger.logHit("totalVideoAsin");
if(videoSet.length>0){if(isIpad){logger.logHit("ipadVideoFound");
colorClickedLogged={};
}else{if(isAndroid){logger.logHit("andVideoFound");
colorClickedLogged={};
}}}videoAvailLogged[obj.asin]=1;
}}changeColorCall[color]=1;
if(options.alwaysIncludeVideo){var offset=0;
$.each([colorImages[color],videoSet,options.customerImages],function(i){var reservedSlots=(i<1&&videoSet.length>0?1:0);
$.each(this,function(j){var thumb=$("<img alt=''>");
thumb.load(function(){thumb.removeClass("load");
}).attr("src",this.thumb);
thumb.addClass("border load thumb"+(offset+j));
thumb.removeClass("load");
thumb.data("index",offset+j);
thumbs.append(thumb);
if(this.imageLink&&!(isIpad&&window.ImageBlockWeblabs&&window.ImageBlockWeblabs.consolidated)){thumb.wrap("<a href='"+this.imageLink+"'></a>");
}return ++numAlts<options.maxAlts-reservedSlots;
});
offset+=this.length;
return numAlts<options.maxAlts;
});
thumbnails=thumbs.find(".border").unbind("mouseover",thumbMouseOver).unbind("mouseout",thumbMouseOut).unbind("click",thumbOnClick);
thumbnails.mouseover(thumbMouseOver).mouseout(thumbMouseOut).click(thumbOnClick);
}else{$.each([colorImages[color],videoSet,options.customerImages],function(i,arr){$.each(arr,function(j,imageHash){var thumb=$("<img class='border load' alt=''>");
thumbs.append(thumb);
if(imageHash.imageLink&&!(isIpad&&window.ImageBlockWeblabs&&window.ImageBlockWeblabs.consolidated)){thumb.wrap("<a href='"+imageHash.imageLink+"'></a>");
}thumb.load(function(){thumb.removeClass("load");
});
var src=(imageHash.isVideo&&options.useChromelessVideoPlayer&&options.useChildVideos)?options.staticImages.videoThumbIcon:imageHash.thumb;
thumb.attr("src",src);
return ++numAlts<options.maxAlts;
});
return numAlts<options.maxAlts;
});
thumbnails=thumbs.find("img").unbind("mouseover",thumbMouseOver).unbind("mouseout",thumbMouseOut).unbind("click",thumbOnClick);
thumbnails.mouseover(thumbMouseOver).mouseout(thumbMouseOut).click(thumbOnClick);
}if(selectedVariant>=numAlts){selectedVariant=0;
}changeVariant(color,selectedVariant);
};
function changeVariant(c,index){variant=index;
var config=utils.splitByType(c,index,changeMainImageVariant,changeVideoVariant,changeCustomerImageVariant);
if(config){thumbnails.removeClass("selected");
var target=options.alwaysIncludeVideo?thumbnails.filter(".thumb"+variant):thumbnails.eq(variant);
target.addClass("selected").css("cursor",config.showHandCursor?"pointer":"default");
utils.setImageCaption(c,variant);
utils.fixIE();
}}function changeMainImageVariant(c,imageIndex){var imageHash=colorImages[c][imageIndex];
var imageUnavailable=mainImageWidget.find("#main-image-unavailable").is(":visible");
var src;
if(imageHash.main[size]){src=imageHash.main[size];
}else{src=imageHash.main[imageHash.main.length-1];
}hideAllHolders();
currentHolder=imageHolder.show();
if(logMetrics&&(!srcLogged[src])){srcLogged[src]=1;
logger.logHit("imgRequest");
if(imageUnavailable){logger.logHit("imgMissing");
}else{logger.logHit("imgFound");
if(imageHash.hiRes){logger.logHit("hiResFound");
}}}try{magnifier.suppressMagnifier(false);
magnifier.changeImage(src,imageUnavailable?null:imageHash.hiRes);
}catch(err){loadMagnifier();
}return{showHandCursor:!imageUnavailable&&useIV};
}function changeCustomerImageVariant(ciuIndex){var ciuImageHash=options.customerImages[ciuIndex];
var holderId=ciuImageHash.holderId;
var imageLink=ciuImageHash.imageLink;
hideAllHolders();
currentHolder=mainImageWrapper.find("#"+holderId);
if(currentHolder.length==0){var imageId="ciu_"+ciuImageHash.id;
var imageHTML="<img id='"+imageId+"'>";
if(!isIpad&&window.ImageBlockWeblabs&&(window.ImageBlockWeblabs.consolidated||window.ImageBlockWeblabs.bookLargeImage)){imageHTML="<a href='"+imageLink+"'>"+imageHTML+"</a>";
}currentHolder=$("<div id='"+holderId+"' class='holder ciu'>"+imageHTML+"</div>").appendTo(mainImageWrapper);
}currentHolder.find("img").attr("src",ciuImageHash.main[size]);
mostRecentLoadCallback=null;
magnifier&&magnifier.disengageMagnifier();
currentHolder.show();
return{showHandCursor:ciuImageHash.imageLink};
}function changeVideoVariant(c,videoIndex){var videoHash=utils.getVideos(c)[videoIndex];
createVideoHolder(videoIndex);
if(currentHolder!==videoContainer||AiryPlayerWrapper.activePlayer!=videoHash.player){hideAllHolders();
videoHash.player.showPreplay();
currentHolder=videoContainer;
}return{showHandCursor:useIV};
}function AiryPlayerWrapper(clr,idx,hash){this.color=clr;
this.index=idx;
this.playing=false;
this.data=$.extend({},hash);
}$.extend(AiryPlayerWrapper.prototype,{initialize:function(){var dims;
if(!videoSizes[size]){dims=videoSizes[videoSizes.length-1];
}else{dims=videoSizes[size];
}if(this.data.slateUrl){this.data.slateUrl=this.data.slateUrl.replace(/_SX\d+_/,"_SX"+dims[0]+"_");
}if(!airyInstance){videoContainer=$('<div id="main-video-container" class="holder video"></div>');
videoContainer.css({"width":dims[0]+"px","height":dims[1]+"px","z-index":"-1"});
if(window.ImageBlockWeblabs&&window.ImageBlockWeblabs.swipe&&!$.browser.msie){videoContainer.prependTo("#main-image-wrapper");
}else{videoContainer.prependTo("#main-image-content");
}if(!useChromelessVideoPlayer){videoContainer.addClass("chromeful-container");
}AiryPlayerWrapper.activePlayer=null;
var contextName=useChromelessVideoPlayer?"ChromelessView":"ChromefulView",airyHandlers={videounsupported:function(){if(logMetrics&&logger){logger.logKeyValuePair(contextName,"NO_FLASH_ERROR");
}},error:function(){if(logMetrics&&logger){logger.logKeyValuePair(contextName,"ERROR");
}},ended:function(){if(useChromelessVideoPlayer){changeVariant(color,0);
}}};
if(useChromelessVideoPlayer){airyInstance=utils.embedAiryForChromelessPlayback(videoContainer,this.data,airyConfig,contextName,airyHandlers);
}else{airyInstance=utils.embedAiryForChromefulPlayback(videoContainer,this.data,airyConfig,contextName,airyHandlers);
}var videoCaptionEl=$("#image-canvas-caption").clone().attr("id","video-canvas-caption");
videoCaptionEl.appendTo(videoContainer);
videoCaptionEl.find("#canvasCaption").html(options.staticStrings["playVideo"]);
}},showPreplay:function(){if(airyInstance&&AiryPlayerWrapper.activePlayer!==this){var dims;
if(!videoSizes[size]){dims=videoSizes[videoSizes.length-1];
}else{dims=videoSizes[size];
}videoContainer.css({"width":dims[0]+"px","height":dims[1]+"px","z-index":"1"});
airyInstance.show();
AiryPlayerWrapper.activePlayer=this;
utils.loadMediaIntoAiryAndSetVolume(airyInstance,this.data,airyConfig);
if(this.playing||useChromelessVideoPlayer){airyInstance.play();
}}},resizeVideo:function(w,h){if(videoContainer&&AiryPlayerWrapper.activePlayer===this){videoContainer.css({"width":w+"px","height":h+"px"});
}},hide:function(){if(airyInstance&&AiryPlayerWrapper.activePlayer===this){AiryPlayerWrapper.activePlayer=null;
videoContainer.css("z-index","-1");
this.playing=airyInstance.isPlaying();
if(this.playing){airyInstance.pause();
}airyInstance.hide();
}}});
function createVideoHolder(index){var videoHash=utils.getVideos(color)[index];
if(typeof Airy!=="undefined"&&videoHash&&!videoHash.player){videoHash.player=new AiryPlayerWrapper(color,index,videoHash);
videoHash.player.initialize();
}}function hideAllHolders(){mainImageWrapper.find(".ciu").hide();
imageHolder.hide();
if(AiryPlayerWrapper.activePlayer){AiryPlayerWrapper.activePlayer.hide();
}currentHolder=null;
}function thumbMouseOver(){var index=utils.getThumbnailIndex(this,thumbnails);
changeVariant(color,index);
thumbMouseOverTriggered=1;
var mainImageCaption=mainImageWidget.find("#main-image-caption");
if(index<colorImages[color].length){if(useIV){mainImageCaption.html(options.staticStrings["clickToExpand"]);
}else{if(colorImages[color][index].hiRes&&options.useHoverZoom){if(options.hoverZoomIndicator&&options.useHoverZoomIpad){mainImageCaption.html("<img src='"+options.staticImages.hoverZoomIcon+"'/>&nbsp;"+options.staticStrings["touchToZoom"]);
}else{if(options.useHoverZoomIpad){mainImageCaption.html(options.staticStrings["touchToZoom"]);
}else{if(options.hoverZoomIndicator){mainImageCaption.html("<img src='"+options.staticImages.hoverZoomIcon+"'/>&nbsp;"+options.staticStrings["rollOverToZoom"]);
}else{mainImageCaption.html(options.staticStrings["rollOverToZoom"]);
}}}}}}}function thumbMouseOut(){utils.setImageCaption(color,variant,100);
}function thumbOnClick(e){var index=utils.getThumbnailIndex(this,thumbnails),numColors=colorImages[color].length,numVideos=utils.getVideos(color).length,lastThumb=numColors+numVideos-1;
if(index<=lastThumb){if(index<numColors||!useChromelessVideoPlayer){showIV(e);
}if(!(colorImages[color][index]&&colorImages[color][index].imageLink)){return false;
}}}function mainOnClick(e){if(options.showLITBOnClick){if(typeof(SitbReader)!="undefined"){SitbReader.LightboxActions.openReader(options.sitbReftag);
}}else{showIV(e);
}return false;
}function bindTwisterEvents(){new function(){var func=this;
func.name="Magnifiable Image Block";
func.notify=function(event,state){var c=event=="swatch_hover"?utils.getColorFromState(state.hovered_variations):utils.getColorFromState(state.selected_variations);
if(event=="swatch_hover"){var index=0;
if(!c){color==defaultColor?utils.hideUnavailable():utils.showUnavailable();
c=defaultColor;
}else{if(!colorImages[c]||colorImages[c].length<=0){var colorName=state["variation_display_labels"]["color_name"];
utils.showUnavailable(state.hovered_variations[colorName]&&c);
c=defaultColor;
}else{if(!utils.isBuyableVariation(state)){utils.showItemUnavailable(state["hovered_variations"]);
}else{utils.hideUnavailable();
}}}var isAndroidVideoIndex=isAndroid&&useChromelessVideoPlayer&&useChildVideos&&variant==colorImages[color].length;
if(!isAndroidVideoIndex){previewColor(c,c==color?variant:index);
}}else{if(event=="initial"){self.changeColor(defaultColor);
}else{self.changeColor(c||defaultColor);
}}utils.fixIE();
};
if(typeof gIsNewTwister=="undefined"||gIsNewTwister==0){self.changeColor(color);
}amznJQ.available("dpf",function(){func.notify("initial",DetailPage.StateController.getState());
var highPriority=1;
DetailPageFramework.registerFeature(func,["child_deselect","child_select","swatch_hover"],highPriority);
});
amznJQ.available("newTwister",function(){if(typeof DetailPage!="undefined"&&DetailPage.StateController){func.notify("initial",DetailPage.StateController.getState());
}});
};
}function loadMagnifier(){if(isMagnifierLoaded){return;
}isMagnifierLoaded=true;
options.autoplayVideo=false;
if(options.showLITBOnClick){imageHolder.click(mainOnClick);
}amznJQ.available("imageMagnifier",function(){var opts={adjustment:[0,0,1,1],generalImageUrls:options.staticImages,location:"over",locationElement:".hoverZoom, .buying .brandLink, #handleBuy .dkBlueBox, #btAsinTitle, #product-title-divider,"+"#jsSwatches, #testevent, #scarcity_feature_div, #fast-track_feature_div,.qpDivTop .cBoxInner, #ob-replacement_feature_div",minHeightElement:"#main-image-widget",preload:"ready",zIndex:990,useHoverZoomIpad:options.useHoverZoomIpad,useHoverZoom:options.useHoverZoom,logMetrics:logMetrics};
if(options.isQuickview){$.extend(opts,{adjustment:[0,0,0,0],locationElement:"#quickview_ppd_layout_table td.right",minHeightElement:null,zIndex:202});
}window.magnifier=mainImage.amazonMagnifier(opts);
$(document).bind("stretchy-goodness",stretchyGoodnessCallback);
utils.resizeCallback();
if(useIV){amznJQ.available("DonsBoxJS",function(){});
amznJQ.available("immersiveView",onIVLoaded);
}else{utils.setImageCaption(color,variant);
}});
}function stretchyGoodnessCallback(e,data){if(size!=data.size){size=data.size;
if(videoContainer){var dims;
if(!videoSizes[size]){dims=videoSizes[videoSizes.length-1];
}else{dims=videoSizes[size];
}videoContainer.css({"width":dims[0]+"px","height":dims[1]+"px"});
}changeVariant(color,variant);
mainImageWidget.attr("class",mainImageWidget.attr("class").replace(/size[0-9]+/,"size"+size));
}}function onIVLoaded(){var videoSet=utils.getVideos(color);
if(!utils.isArray(videoSet)){videoSet=[];
}$.each(videoSet,function(i,videoHash){createVideoHolder(i);
});
mainImage.css("cursor","pointer");
thumbnails.unbind("click",thumbOnClick).unbind("mouseout",thumbMouseOut);
thumbnails.click(thumbOnClick).mouseout(thumbMouseOut);
imageHolder.click(mainOnClick);
utils.setImageCaption(color,variant);
$(document).bind("engaged.magnifier disengaged.magnifier",function(){utils.setImageCaption(color,variant);
});
isIVAvailable=true;
}function createIV(e,colorIndex,variantIndex,isImage){var imageSet={};
$.each(options.ivImageSetKeys,function(index){if(colorImages[index]){imageSet[options.ivImageSetKeys[index]]={images:{thumbnails:$.map(colorImages[index],function(image){return image.thumb;
}),zoomImages:$.map(colorImages[index],function(image){return image.hiRes||image.large||image.main[image.main.length-1];
})}};
}});
window.setImmersiveViewContext=function(){};
window.ivStrings=options.staticStrings;
immersiveView=$.fn.amazonImmersiveView();
var isCssLoaded=immersiveView.loadCSS();
if(!isCssLoaded){immersiveView=undefined;
return;
}if(useChromelessVideoPlayer){immersiveView.disableVideo();
}immersiveView.setAiryHelper({config:airyConfig,embedChromeful:utils.embedAiryForChromefulPlayback,loadMedia:utils.loadMediaIntoAiryAndSetVolume,getVideosBySetId:function(id){if(typeof(isTwisterPage)!=="undefined"&&isTwisterPage){var indexes=id.split("-"),colors=[];
indexes.forEach(function(e,dim){var idx=parseInt(e,10);
colors.push(options.indexToColor[dim][idx-1]);
});
return utils.getVideos(colors.join(" "));
}else{return utils.getVideos(options.indexToColor[0]);
}}});
immersiveView.setTitle(options.title);
immersiveView.setProductGroupID(options.productGroupID);
immersiveView.setMediaUrls(options.staticImages);
immersiveView.changeImageSet(imageSet);
var isTwisterDP=false;
if((typeof gIsNewTwister!="undefined"&&gIsNewTwister!=0)||(typeof goTwisterCore!="undefined"&&goTwisterCore.selectionItems)){isTwisterDP=true;
window.swatches={};
var regExp=new RegExp(amznJQ.chars.BACKSLASH+"d+");
var imgTag=$("<img/>").css("height","20px");
$(".swatchOuter").each(function(){var swatchIndex=Number($(this).children().eq(0).attr("id").match(regExp))+1;
var swatchImageContainer=$(this).find(".swatchInnerImage");
if(swatchImageContainer.length>0){var url=swatchImageContainer.css("background-image").slice(4,-1);
if(url.charAt(0)==amznJQ.chars.DQUOTE){url=url.slice(1,-1);
}swatches["color_name-"+options.indexToColor[swatchIndex]]=$("<div/>").append(imgTag.attr("src",url).removeAttr("width")).html();
}});
$(".swatches li").each(function(){var swatchIndex=Number($(this).attr("id").match(regExp))+1;
var swatchImageContainer=$(this).find("img");
if(swatchImageContainer.length>0){var url=swatchImageContainer.attr("src");
if(url.charAt(0)==amznJQ.chars.DQUOTE){url=url.slice(1,-1);
}swatches["color_name-"+options.indexToColor[swatchIndex]]=$("<div/>").append(imgTag.attr("src",url).removeAttr("width")).html();
}});
immersiveView.setVariationProperties(options.visualDimensions,swatches);
if(typeof gIsNewTwister!="undefined"&&gIsNewTwister!=0){immersiveView.setItems(options.colorToAsin);
immersiveView.setIVRepresentativeAsin(options.ivRepresentativeAsin,options.gPreferChildVideos);
}else{immersiveView.setItems(goTwisterCore.selectionItems);
}}immersiveView.setInitialIDs(colorIndex,variantIndex,isImage);
immersiveView.createImmersiveView(e,isTwisterDP);
$(window).ready(function(){$.get("/gp/product/ajax-handlers/reftag.html/ref=dp_imgs_iv");
});
}function showIV(e){if(!useIV||!isIVAvailable){return;
}var currentSelectedVariation=null;
if(typeof DetailPage!="undefined"&&DetailPage.StateController){currentSelectedVariation=utils.getColorFromState(DetailPage.StateController.getState()["selected_variations"]);
}var currentSelectedColor=currentSelectedVariation||color;
var length=colorImages[currentSelectedColor].length;
var isImage=variant<length;
var colorIndex=options.ivImageSetKeys[currentSelectedColor]||0;
var variantIndex=isImage?variant:variant-length;
if(useChromelessVideoPlayer&&!isImage){isImage=true;
variantIndex=0;
}if(airyInstance&&airyInstance.isPlaying()){airyInstance.pause();
}if(!immersiveView){createIV(e,colorIndex,variantIndex,isImage);
}immersiveView.setInitialIDs(colorIndex,variantIndex,isImage);
$.AmazonPopover.displayPopover(immersiveView.getIVPopoverOptions());
}var getDataHash=function(noRefresh,id,html){var data={};
data[id]=html;
return{noRefresh:noRefresh,content:data};
},updateMainImageMarkup=function(c){var selectedVariant=0;
if(options.autoplayVideo&&!isAndroid){selectedVariant=colorImages[c].length;
}else{if(c==color){selectedVariant=variant;
}}if(c&&(!colorImages[c]||colorImages[c]<=0)){utils.showUnavailable(c);
c=defaultColor;
}else{utils.hideUnavailable();
}if(selectedVariant>=numAlts){selectedVariant=0;
}changeVariant(c,selectedVariant);
},getMainImageMarkup=function(id,dpState){var c=utils.getColorFromState(dpState.getState()["hovered_variations"])||defaultColor;
var html='<div><script> ImageBlock.TwisterReArchModule.updateMainImageMarkup("'+c.replace(/\\/g,"\\\\").replace(/"/g,'\\"')+'"); <\/script></div>';
return getDataHash(false,"twister-main-image",html);
},initializeThumbnails=function(thumbs){thumbnails=thumbs;
variant=index=0;
var typeAndIndex=utils.getImageTypeAndIndex(color,index);
var config=null;
switch(typeAndIndex.type){case"image":config={"showHandCursor":"showHandCursor"};
break;
case"video":config={"showHandCursor":"useIV"};
break;
case"ciu":config={"showHandCursor":ciuImageHash.imageLink};
break;
}if(config){thumbnails.removeClass("selected");
if(options.alwaysIncludeVideo){thumbnails.filter(".thumb"+variant).addClass("selected").css("cursor",config.showHandCursor?"pointer":"default");
}else{thumbnails.eq(variant).addClass("selected").css("cursor",config.showHandCursor?"pointer":"default");
}utils.setImageCaption(color,index);
if(jQuery.browser.msie){mainImage.get(0).className=mainImage.get(0).className;
}}},getAltsMarkup=function(c){var numAlts=0,thumbs=mainImageWidget.find(".thumbs"),videoSet=utils.getVideos(c),thumbMarkup=jQuery("<div></div>");
if(logMetrics&&options.useChromelessVideoPlayer&&options.useChildVideos&&changeColorCall[c]){var obj=options.colorToAsin[c];
if(obj&&obj.asin&&!videoAvailLogged[obj.asin]){var videoStatus=(videoSet.length>0)?"videoFound":"videoMissing";
logger.logHit(videoStatus);
logger.logHit("totalVideoAsin");
if(videoSet.length>0){if(isIpad){logger.logHit("ipadVideoFound");
colorClickedLogged={};
}else{if(isAndroid){logger.logHit("andVideoFound");
colorClickedLogged={};
}}}videoAvailLogged[obj.asin]=1;
}}if(options.alwaysIncludeVideo){var offset=0;
jQuery.each([colorImages[c],videoSet,options.customerImages],function(i){var reservedSlots=(i<1&&videoSet.length>0?1:0);
jQuery.each(this,function(j){var thumb=jQuery("<img alt=''>");
thumb.attr("src",this.thumb);
thumb.addClass("border thumb"+(offset+j));
thumb.data("index",offset+j);
thumb.attr("data-index",offset+j);
thumbMarkup.append(thumb);
if(this.imageLink&&!(isIpad&&window.ImageBlockWeblabs&&window.ImageBlockWeblabs.consolidated)){thumb.wrap("<a href='"+this.imageLink+"'></a>");
}return ++numAlts<options.maxAlts-reservedSlots;
});
offset+=this.length;
return numAlts<options.maxAlts;
});
}else{jQuery.each([colorImages[c],videoSet,options.customerImages],function(i,arr){jQuery.each(arr,function(j,imageHash){var thumb=jQuery("<img class='border' alt='' />");
thumbMarkup.append(thumb);
if(imageHash.imageLink&&!(isIpad&&window.ImageBlockWeblabs&&window.ImageBlockWeblabs.consolidated)){thumb.wrap("<a href='"+imageHash.imageLink+"'></a>");
}var src=(imageHash.isVideo&&options.useChromelessVideoPlayer&&options.useChildVideos)?options.staticImages.videoThumbIcon:imageHash.thumb;
thumb.attr("src",src);
return ++numAlts<options.maxAlts;
});
return numAlts<options.maxAlts;
});
}var script="<div> <script> ImageBlock.TwisterReArchModule.updateAltsImageMarkup("+options.alwaysIncludeVideo+"); <\/script></div>";
return thumbMarkup.html()+script;
},updateAltsImageMarkup=function(){var thumbnails;
if(options.alwaysIncludeVideo){thumbnails=jQuery(".thumbs").find(".border").mouseover(thumbMouseOver).mouseout(thumbMouseOut).click(thumbOnClick);
}else{thumbnails=jQuery(".thumbs").find("img").mouseover(thumbMouseOver).mouseout(thumbMouseOut).click(thumbOnClick);
}initializeThumbnails(thumbnails);
},getAltsImageMarkup=function(id,dpState){var c=utils.getColorFromState(dpState.getState()["selected_variations"]);
var noRefresh=false;
var html="";
if(c!=""&&c!=color){if(c&&(!colorImages[c]||colorImages[c]<=0)){c=defaultColor;
}color=c;
html=getAltsMarkup(c);
}else{noRefresh=true;
}return getDataHash(noRefresh,"thumbs-image",html);
};
self.getTwisterReArchApis=function(){return{getAltsImageMarkup:getAltsImageMarkup,updateAltsImageMarkup:updateAltsImageMarkup,updateMainImageMarkup:updateMainImageMarkup,getMainImageMarkup:getMainImageMarkup};
};
if(logMetrics){logger=self.logger=new window.Softlines.ClientLogger("imageBlock",true);
logger.logKeyValuePair("BHeight",clientScreen.browserHeight);
logger.logKeyValuePair("BWidth",clientScreen.browserWidth);
var imageSize="size"+size;
logger.logSingleton(imageSize);
logger.logSingleton("imageSizeRequest");
if(options.autoplayVideo&&options.useChildVideos){var obj=options.colorToAsin[color];
if(obj&&obj.asin){videoAvailLogged[obj.asin]=1;
}logger.logHit("totalVideoAsin");
if(options.newVideoMissing){logger.logHit("videoMissing");
}else{logger.logHit("videoFound");
if(isIpad){logger.logHit("ipadVideoFound");
}else{if(isAndroid){logger.logHit("andVideoFound");
}}}var videoSet=utils.getVideos(color);
if(videoSet&&videoSet.length&&!isIpad&&!isAndroid){logger.logKeyValuePair("flashVideoReady",cfEndTimer);
logger.logKeyValuePair("playerLoaded",cfEndTimer);
logger.logKeyValuePair("html5VideoReady",cfEndTimer);
logger.logKeyValuePair("videoDownloaded",cfEndTimer);
}}}if(!options.autoplayVideo&&colorImages[color][0].hiRes){var hiResImage=new Image();
hiResImage.src=colorImages[color][0].hiRes;
}if(typeof(magnifier)!="undefined"&&magnifier){magnifier.destroy();
}window.magnifier=null;
thumbnails.mouseover(thumbMouseOver);
if(isIpad){videoSizes=options.ipadVideoSizes;
}bindTwisterEvents();
if(!options.autoplayVideo){updateMainImage(color,0);
loadMagnifier();
}}window.ImageBlock=ImageBlock;
amznJQ.declareAvailable("imageBlock-airy");
});
});
});
(function($){function hoverZoomBoundInDPX(){var b={left:Infinity,top:Infinity,right:-Infinity,bottom:-Infinity};
b.top=$("#centerCol").offset().top;
b.left=$("#centerCol").offset().left;
b.right=b.left+$("#centerCol").outerWidth();
b.bottom=$("#centerCol").outerHeight()+b.top;
return b;
}function hoverZoomBound(){var b={left:Infinity,top:Infinity,right:-Infinity,bottom:-Infinity};
b.top=$("#handleBuy").offset().top;
b.left=$(".productImageGrid").offset().left+$(".productImageGrid").outerWidth()+parseInt($(".productImageGrid").css("marginRight"));
b.right=$(".buyingDetailsGrid").offset().left-parseInt($(".buyingDetailsGrid").css("marginLeft"))+10;
b.bottom=$("hr.bucketDivider").offset().top-5;
return b;
}function parseMediaServerCodes(url){var m=url.match(/\._((\w|,|\.)+)_\.(gif|jpg|png)$/i);
var codes={};
if(m){var mediaServerCodes=m[1].split("_");
for(var i=0;
i<mediaServerCodes.length;
i++){var m2=mediaServerCodes[i].match(/^([A-Z]+)(\d+(\.\d+)?)$/);
if(m2){codes[m2[1]]=Number(m2[2]);
}}}return codes;
}$.fn.amazonMagnifier=function(options){var navImage=this;
var defaultOptions={adjustment:[0,0,0,0],detailImageUrl:navImage.attr("rel"),location:"over",locationElement:navImage,prelaod:"ready",zIndex:50};
options=$.extend(defaultOptions,options);
var zoomWindow=null;
var lens=null;
var cursorAt=null;
var navImageRect=null;
var preloaded={"null":1,"":1,"undefined":1};
var engaged=false;
var magnifierSuppressed=false;
var currentDetailImageUrl=options.detailImageUrl;
var isIE6=jQuery.browser.msie&&parseInt(jQuery.browser.version)<=6;
var hiddenSelects;
var hoverZoomIpad=options.useHoverZoomIpad||0;
var hoverOnLoad=0;
var urlsLogged={};
var Lens=function(){var self=this;
var size=[0,0];
var zoomRatio=(zoomWindow.detailSize&&zoomWindow.detailSize[0]||500000000)/navImageRect[2];
var zoomHtRatio=(zoomWindow.detailSize&&zoomWindow.detailSize[1]||500000000)/navImageRect[3];
if(zoomHtRatio>zoomRatio){zoomRatio=zoomHtRatio;
}var jq=$("<div id='magnifierLens' />").css({backgroundImage:"url("+options.generalImageUrls.zoomLensBackground+")",position:"absolute",cursor:"pointer"});
function updateSize(ratio){var width=Math.round(Math.min(navImage.width(),zoomWindow.rect.width/ratio));
var height=Math.round(Math.min(navImage.height(),zoomWindow.rect.height/ratio));
jq.css({width:width,height:height});
size=[width,height];
}self.updatePosition=function(){var range=[navImageRect[2]-size[0],navImageRect[3]-size[1]];
var u=range[0]<=0?0.5:Math.max(0,Math.min(1,(cursorAt[0]-size[0]/2-navImageRect[0]-self.offset.left)/range[0]));
var v=range[1]<=0?0.5:Math.max(0,Math.min(1,(cursorAt[1]-size[1]/2-navImageRect[1]-self.offset.top)/range[1]));
var x=navImageRect[0]+Math.round(u*range[0]);
var y=navImageRect[1]+Math.round(v*range[1]);
jq.get(0).style.left=x+"px";
jq.get(0).style.top=y+"px";
return[u,v];
};
self.destroy=function(){jq.remove();
};
self.offset=navImage.offsetParent().offset();
updateSize(zoomRatio);
self.updatePosition();
jq.appendTo(navImage.parent());
if(!zoomWindow.detailImage[0].complete){zoomWindow.detailImage.load(function(){var zoomRatio=zoomWindow.detailImage.width()/navImageRect[2];
updateSize(zoomRatio);
self.updatePosition();
});
}};
Lens.preload=function(){navImage.preload(options.generalImageUrls.lensBackgroundUrl);
};
var ZoomWindow=function(){var zw=this;
var adjustment=options.adjustment;
var cropWindow=$("<div id='zoomWindow' />").css({overflow:"hidden",position:"absolute",backgroundColor:"white",zIndex:options.zIndex});
function fit(){var rect=null;
if(options.location=="over"){if($("#ppd #centerCol").length>0){rect=hoverZoomBoundInDPX();
}else{if($(".productImageGrid").length>0){rect=hoverZoomBound();
}else{rect.left=0;
rect.right=0;
}}}else{if(options.location=="right"){var o=navImage.offset();
rect={left:o.left+navImage.outerWidth(),top:o.top,right:o.left+navImage.outerWidth()+400,bottom:o.top+400};
}}if(options.minHeightElement){rect.bottom=Math.max(rect.bottom,rect.top+$(options.minHeightElement).outerHeight());
}rect.bottom=Math.min(rect.bottom,$(window).scrollTop()+$(window).height());
rect.left+=adjustment[0];
rect.top+=adjustment[1];
rect.right+=adjustment[2];
rect.bottom+=adjustment[3];
rect.width=rect.right-rect.left;
rect.height=rect.bottom-rect.top;
cropWindow.css({left:rect.left,top:rect.top,width:rect.width,height:rect.height});
zw.rect=rect;
return zw;
}function updateDetailSize(img){var imageObj=new Image();
imageObj.src=img.attr("src");
if(imageObj.complete&&imageObj.width>0&&imageObj.height>0){zw.detailSize=[imageObj.width,imageObj.height];
return;
}else{if(options.detailImageSize){zw.detailSize=options.detailImageSize;
return;
}}var codes=parseMediaServerCodes(imageObj.src);
var aspectRatio=navImageRect[2]/navImageRect[3];
if(codes["SS"]||codes["AA"]){var size=codes["SS"]||codes["AA"];
zw.detailSize=[size,size];
}else{if(codes["SX"]){zw.detailSize=[codes["SX"],Math.round(codes["SX"]/aspectRatio)];
}else{if(codes["SY"]){zw.detailSize=[Math.round(codes["SY"]*aspectRatio),codes["SY"]];
}else{if(codes["SL"]){if(aspectRatio>=1){zw.detailSize=[codes["SL"],Math.round(codes["SL"]/aspectRatio)];
}else{zw.detailSize=[Math.round(codes["SL"]*aspectRatio),codes["SL"]];
}}else{zw.detailSize=[0,0];
imageObj.onload=function(){zw.detailSize=[imageObj.width,imageObj.height];
updateDetailPosition();
$(window).resize();
};
}}}}}zw.updateImage=function(src){var img=$("<img id='detailImg' src='"+src+"'/>").css("position","absolute");
zw.detailImage&&zw.detailImage.remove();
cropWindow.append(img);
$(document).trigger("updated.magnifier");
zw.detailImage=img;
updateDetailSize(zw.detailImage);
};
zw.refit=function(){fit();
updateDetailSize(zw.detailImage);
return zw;
};
zw.show=function(){cropWindow.show();
return zw;
};
zw.hide=function(){cropWindow.hide();
return zw;
};
zw.destroy=function(){cropWindow.remove();
return zw;
};
zw.updateImage(currentDetailImageUrl);
fit();
cropWindow.appendTo(document.body);
};
function updateDetailPosition(){var pos=lens&&lens.updatePosition();
if(pos&&zoomWindow.detailSize){var range=[zoomWindow.detailSize[0]-zoomWindow.rect.width,zoomWindow.detailSize[1]-zoomWindow.rect.height];
zoomWindow.detailImage.get(0).style.left=-(pos[0]*range[0])+"px";
zoomWindow.detailImage.get(0).style.top=-(pos[1]*range[1])+"px";
}}function locateCursor(e){var touch=hoverZoomIpad?(e.originalEvent.touches[0]||e.originalEvent.changedTouches[0]):"";
cursorAt=hoverZoomIpad?[touch.pageX,touch.pageY]:[e.pageX,e.pageY];
}function onMouseMove(e){if(hoverZoomIpad){e.preventDefault();
}locateCursor(e);
var offset=lens?lens.offset:navImage.offsetParent().offset();
if(cursorAt[0]<navImageRect[0]+offset.left||cursorAt[1]<navImageRect[1]+offset.top||cursorAt[0]>=navImageRect[0]+navImageRect[2]+offset.left||cursorAt[1]>=navImageRect[1]+navImageRect[3]+offset.top){disengage();
}updateDetailPosition();
}function hideSelects(){var selects=jQuery(options.locationElement).find("select:visible");
if(isIE6||jQuery.browser.safari){hiddenSelects=selects.hide();
}else{selects.blur();
}}function showSelects(){hiddenSelects&&hiddenSelects.show();
}function disengage(){if(!engaged){return;
}if($.browser.msie){$("#main-image-widget .holder.video").show();
}showSelects();
zoomWindow&&zoomWindow.hide();
if(lens){lens.destroy();
lens=null;
}engaged=false;
bindEvents();
if(hoverZoomIpad){if(window.ImageBlockWeblabs&&window.ImageBlockWeblabs.swipe){navImage.unbind("touchmove.magnifier touchend.magnifier");
}else{navImage.unbind("touchmove.magnifier touchstart.magnifier touchend.magnifier");
}$(document).trigger("disengaged.magnifier");
}else{$(document).unbind("mousemove.magnifier").trigger("disengaged.magnifier");
}}function engage(e){if(engaged||magnifierSuppressed){return;
}if(options.logMetrics){if(hoverOnLoad==0){if(window.ue){var hoverEngageTime=new Date();
var timeDiff=hoverEngageTime-window.ue.t0;
jQuery.imageBlock.logger.logKeyValuePair("hoverTime",timeDiff);
}hoverOnLoad=1;
}if(!urlsLogged[currentDetailImageUrl]){jQuery.imageBlock.logger.logHit("hoverMain");
urlsLogged[currentDetailImageUrl]=1;
}}navImageRect=[navImage.position().left,navImage.position().top,navImage.width(),navImage.height()];
if($.browser.msie){$("#main-image-widget .holder.video").hide();
}if(currentDetailImageUrl){if($.browser.msie&&!$.isReady){$("#main-image-widget .holder.video").show();
return;
}hideSelects();
locateCursor(e);
if(zoomWindow){zoomWindow.refit().show();
}else{zoomWindow=new ZoomWindow();
}lens=lens||new Lens();
updateDetailPosition();
}engaged=true;
if(hoverZoomIpad){if(window.ImageBlockWeblabs&&window.ImageBlockWeblabs.swipe){navImage.unbind("touchmove.magnifier").bind("touchmove.magnifier",onMouseMove);
}else{navImage.unbind("touchstart.magnifier touchmove.magnifier").bind("touchmove.magnifier",onMouseMove);
}$(document).trigger("engaged.magnifier");
}else{navImage.unbind("mousemove.magnifier");
$(document).trigger("engaged.magnifier").bind("mousemove.magnifier",onMouseMove);
}}function bindEvents(){if(options.useHoverZoom){if(hoverZoomIpad){if(window.ImageBlockWeblabs&&window.ImageBlockWeblabs.swipe){amznJQ.available("swipe-gesture",function(){navImage.unbind("touchstart");
disengage();
navImage.taphold(function(e){engage(e);
navImage.bind("touchmove.magnifier",engage);
navImage.bind("touchend.magnifier",disengage);
},200);
});
}else{navImage.bind("touchstart.magnifier touchmove.magnifier",engage);
}}else{navImage.bind("mousemove.magnifier",engage);
}}}navImage.preload=function(urls){var urlArray=$.makeArray(urls);
var length=urlArray.length;
for(var i=0;
i<length;
i++){if(urlArray[i] instanceof Array){navImage.preload(urlArray[i]);
}else{if(typeof urlArray[i]=="string"&&urlArray[i]&&!preloaded[urlArray[i]]){preloaded[urlArray[i]]=new Image();
preloaded[urlArray[i]].src=urlArray[i];
}}}};
navImage.changeImage=function(navImageUrl,detailImageUrl,width,height){if(engaged){disengage();
}currentDetailImageUrl=detailImageUrl;
navImage.attr("src",navImageUrl);
if(typeof width==="undefined"){width="";
}if(typeof height==="undefined"){height="";
}navImage.css("width",width);
navImage.css("height",height);
if($.browser.msie){navImage.get(0).className=navImage.get(0).className;
}navImage.preload(navImageUrl);
navImageRect=[navImage.position().left,navImage.position().top,navImage.width(),navImage.height()];
if(detailImageUrl){if(options.preload=="immediately"){navImage.preload(detailImageUrl,true);
}else{$(window).ready(function(){navImage.preload(detailImageUrl);
});
}if(zoomWindow){zoomWindow.updateImage(detailImageUrl);
}else{navImage.attr("rel",detailImageUrl);
}}};
navImage.destroy=function(){lens&&lens.destroy();
lens=null;
zoomWindow&&zoomWindow.destroy();
zoomWindow=null;
};
navImage.detailImage=function(){return zoomWindow.detailImage;
};
navImage.suppressMagnifier=function(suppress){magnifierSuppressed=suppress;
};
navImage.isEngaged=function(){return engaged;
};
navImage.engageMagnifier=engage;
navImage.disengageMagnifier=disengage;
navImage[0].complete?bindEvents():navImage.one("load",bindEvents);
navImage.preload(this.attr("src"));
if(options.preload){var url=options.detailImageUrl;
var preloadMagnifier=function(){navImage.preload(url,true);
Lens.preload();
};
var eventNames=options.preload;
if(eventNames.constructor!=Array){eventNames=[eventNames];
}for(var i=0;
i<eventNames.length;
i++){if(eventNames[i]=="immediately"){preloadMagnifier();
}else{if($(window)[eventNames[i]]){$(window)[eventNames[i]](preloadMagnifier);
}else{$(window).bind(eventNames[i],preloadMagnifier);
}}}}if(!hoverZoomIpad){$(window).bind("resize.magnifier",navImage.destroy);
}return navImage;
};
amznJQ.declareAvailable("imageMagnifier");
})(jQuery);
(function(){jQuery.fn.amazonImmersiveView=function(){var oTitle;
var oProductGroupID;
var oImageSet;
var oMediaUrls;
var oCurrentImgSetID=-1;
var oCurrentImgID=-1;
var oFullImageFit;
var oIV;
var oRightCol;
var oLeftCol;
var cursorStart=[0,0];
var initialOffset={left:0,top:0};
var oCurrentVideoSetID=0;
var oCurrentVideoID=-1;
var widthAdjustment=42;
var heightAdjustment=125;
var thumbSectionHeightAdjustment=210;
var thumbSectionWidth=220;
var videoListHeightAdjustment=30;
var oFullImageLarge;
var isLargeMode=false;
var maxOffset={};
var DEFAULT_FULL_SCREEN_MOVE_FACTOR=4;
var fullScreenMoveFactor=DEFAULT_FULL_SCREEN_MOVE_FACTOR;
var oSwatchImages;
var oVisualKeys;
var oDonsBoxes=new Array();
var oMasterDim=-1;
var isTwisterDetailPage=false;
var oSelectionVariations={};
var oFullImageHeight=0;
var oFullImageWidth=0;
var goEVDD=new EnhancedVariationsDropDown();
var isPlayingVideo=false;
var oImageLoadState={};
var useThisDPImage=0;
var oSingleton=0;
var noImageChidlASINs;
var isIVOpened=false;
var nSpinnerWidth=80;
var nSpinnerLength=104;
var isImageLoading=false;
var isVideoDisabled=false;
var videoContainer;
var availableVideos=[];
var airyInstance;
var airyHelper;
var isSupportedTablets=0;
this.setIsSupportedTablets=function(supportedTablets){isSupportedTablets=supportedTablets;
};
this.setTitle=function(title){oTitle=title;
};
this.disableVideo=function(){isVideoDisabled=true;
availableVideos=[];
updateMediaSelection();
};
this.setProductGroupID=function(productGroupID){oProductGroupID=productGroupID;
};
this.setMediaUrls=function(mediaUrls){oMediaUrls=mediaUrls;
};
this.setAiryHelper=function(helper){airyHelper=helper;
};
this.changeImageSet=function(newImages){oImageSet=newImages;
};
this.setInitialIDs=function(setID,mediaID,isImage){if(isImage){oCurrentImgSetID=oCurrentVideoSetID=new String(setID);
oCurrentImgID=mediaID;
oCurrentVideoID=-1;
}else{oCurrentImgSetID=oCurrentVideoSetID=new String(setID);
oCurrentVideoID=mediaID;
oCurrentImgID=-1;
}};
this.setVariationProperties=function(visualKeys,swatchImages){oVisualKeys=visualKeys;
oSwatchImages=swatchImages;
};
this.setItems=function(itemList){oItemList=itemList;
};
this.setIVRepresentativeAsin=function(ivRepresentativeAsin,preferChildVideos){oIVRepresentativeAsin=ivRepresentativeAsin;
oPreferChildVideos=preferChildVideos;
};
this.isIVOpen=function(){return isIVOpened;
};
var isCSSLoaded=0;
this.loadCSS=function(){if(isCSSLoaded){return isCSSLoaded;
}var DonsBoxCSS='<style type="text/css">';
jQuery.ajax({url:"/gp/twister/dynamic-update/DonsBox-css.html",dataType:"html",timeout:40000,async:false,success:function(data,status,xhr){DonsBoxCSS+=data+"</style>";
jQuery(DonsBoxCSS).appendTo("head");
isCSSLoaded=1;
}});
return isCSSLoaded;
};
this.createImmersiveView=function(e,isTwisterDP){isTwisterDetailPage=isTwisterDP&&oVisualKeys&&oVisualKeys.length>0;
doBrowserAdjustment();
oIV=jQuery('<div style="display:none;height:'+(jQuery(window).height()-heightAdjustment)+'px; width:100%; padding: 0px 15px 15px 15px;" id="IV-Main"></div>');
availableVideos=airyHelper.getVideosBySetId(oCurrentVideoSetID);
constructLeftCol();
constructRightCol();
oIV.append('<div style="clear:both"/>');
jQuery("#prodImageCell").before(oIV);
this.createIVTrigger();
oIV.find("#iv-large-image").click(function(e){if(isPlayingVideo){return;
}if(isImageLoading){return;
}if(isLargeMode){imageFit();
}else{initialOffset=getFullScreenOffset(initialOffset);
if((oFullImageWidth>=1000)||(oFullImageHeight>=1000)){var largeImage=oLeftCol.find("#iv-large-image");
largeImage.empty().append(oFullImageLarge);
oIV.find(".fullScreen").load(function(){largeMode();
positionImage(e);
});
}}});
oIV.find("#iv-first-column").mousemove(function(e){if(isLargeMode){positionImage(e);
}});
prefetchResources();
addHandlers();
};
function positionImage(e){var newLeft=initialOffset.left-(e.pageX-cursorStart[0])*fullScreenMoveFactor;
var newTop=initialOffset.top-(e.pageY-cursorStart[1])*fullScreenMoveFactor;
var newOffset=getFullScreenOffset({left:newLeft,top:newTop});
oIV.find(".fullScreen").css({"left":newOffset.left,"top":newOffset.top});
}this.getIVPopoverOptions=function(){return{localContent:"#IV-Main",width:(jQuery(window).width()-widthAdjustment),location:function(popover,settings){return{left:20,top:28};
},zIndex:999,paddingLeft:0,paddingRight:0,paddingBottom:0,closeText:ivStrings["close"],modal:true,group:"ImmersiveView",onShow:updateIV,onHide:resetDP};
};
this.createIVTrigger=function(){var options=this.getIVPopoverOptions();
amznJQ.available("popover",function(){var triggers="#see-x-more,.internal_image";
if(!isSupportedTablets){triggers+=",.prod_image_selector,#original_image,[id^=alt_image_],[id^=video_image_],.alt_image_selector,#prodVideoClick";
}jQuery(triggers).removeAmazonPopoverTrigger();
if(jQuery("#prodImageOverlay").css("visibility")=="visible"){triggers="#see-x-more,.internal_image";
if(!isSupportedTablets){triggers+=",#original_image,[id^=alt_image_],[id^=video_image_],.alt_image_selector,#prodVideoClick";
}}jQuery(triggers).amazonPopoverTrigger(options);
});
};
function constructLeftCol(){var imgContainer;
oLeftCol=jQuery('<div id="iv-first-column" style="float: left; width:'+(jQuery(window).width()-widthAdjustment-330)+'px;height:100%; margin-right: 15px;"/>');
var currentDetailImageUrl="";
if(oImageSet&&oImageSet[oCurrentImgSetID]){if(oCurrentImgSetID.charAt(0)=="x"){currentDetailImageUrl=oImageSet[oCurrentImgSetID].images.zoomImages[0];
}else{if(oCurrentImgID!=-1){currentDetailImageUrl=oImageSet[oCurrentImgSetID].images.zoomImages[oCurrentImgID];
}}imgContainer=jQuery('<div width="100%" id="iv-large-image" style="overflow: hidden; width: 100%; height: '+(jQuery(window).height()-heightAdjustment-15)+'px;align:center; position:relative; top:0px; left:0px;"/>');
oLeftCol.append(imgContainer);
oIV.append(oLeftCol);
}else{if(oCurrentVideoID!=-1){imgContainer=jQuery('<div width="100%" id="iv-large-image" style="overflow: hidden; width: 100%; height: '+(jQuery(window).height()-heightAdjustment-15)+'px;align:center; display:none;position:relative; top:0px; left:0px;"/>');
oLeftCol.append(imgContainer);
oIV.append(oLeftCol);
}}videoContainer=jQuery('<div id="iv-large-video" style="width: 1px; height: 1px; align:center;"/>');
oLeftCol.append(videoContainer);
}function constructRightCol(){var rightColHtml='<div style="float: left; width: 235px;" id="iv-sec-column"></div>';
oRightCol=jQuery(rightColHtml);
constructTitle();
constructVarSelection();
constructMediaSelection();
constructThumbs();
oIV.append(oRightCol);
}function constructTitle(){var style='<style type="text/css">a.iv-title-link:link {text-decoration: none;}a.iv-title-link:visited {text-decoration: none; color: #003399}a.iv-title-link:hover {text-decoration: underline; color: orange;}</style>';
jQuery(style).appendTo("head");
var titleHtml;
titleHtml='<div style="text-align: left; margin-top: 10px; font-family: verdana, arial, helvetica, sans-serif; font-size: 14px; font-weight: bold; '+'word-wrap: break-word; width: 235px;" id="iv-prod-title" title="'+oTitle+'">'+'<a class="ap_custom_close iv-title-link" href="">'+trimWithEllipsis(oTitle,45)+"</a></div>";
var titleBar=jQuery(titleHtml);
oRightCol.append(titleBar);
}function constructVarSelection(){if(!isTwisterDetailPage||oVisualKeys.length==0){return;
}var varSelectionHtml='<div style="text-align: left;"  id="iv-variation-selection">';
var pageState=DetailPage.StateController.getState();
var labels=pageState["variation_display_labels"];
var labelCount=0;
for(var i in labels){var index=getIndex(i,oVisualKeys);
if(index<0){continue;
}oDonsBoxes[labelCount++]=index;
if(oMasterDim==-1){oMasterDim=i;
}var label=labels[i];
var selIndex=pageState["selected_variation_values"][i];
oSelectionVariations[i]=selIndex;
varSelectionHtml+='<div style="padding-top:10px; padding-bottom:3px; font-family: verdana, arial, helvetica, sans-serif; font-size:11px; color:#666">'+label+':</div><div style="margin:0px 10px;" id="'+i+'IVDonsBoxParent">';
varSelectionHtml+='</div><br clear="both">';
}varSelectionHtml+="</div>";
var variationSelection=jQuery(varSelectionHtml);
oRightCol.append(variationSelection);
}function constructThumbs(){var style='<style type="text/css">.iv_thumbs { border:1px solid #C9E1F4;width:220px;height:200px;padding-left:15px;padding-top:15px;padding-bottom:15px; overflow-y:auto; border-top:0px;position:relative; top:0px; left:0px; }.iv_thumb_videos {  border:1px solid #C9E1F4;width:235px;height:230px;padding:0px; overflow-y:auto; border-top:0px; }.iv_thumb_video_outer { float:left; width:100%; padding-top:5px; padding-bottom:5px;cursor:pointer}.iv_thumb_video_outer_hover { background-color: #EAF3FD }.iv_thumb_video { border: 1px solid #ddd;float:left; margin-left:10px;margin-right:10px;cursor:pointer; }.iv_thumb { border: 1px solid #ddd;float:left; margin-right:12px; margin-bottom:20px; cursor:pointer; }.iv_thumb_selected { border: 2px solid #E47911; }.iv_thumb_hover { border: 2px solid #004B91; }.iv_thumb_inner { padding: 1px;float:left; }.iv_thumb_inner_selected { padding: 0px; }.iv_thumb_image { float:left;position:relative;width:50px; height:50px; background-color:#ffffff}.iv_thumb_text { float:left; word-wrap:break-word; width:130px; margin-top:10px; font-family:verdana, arial, helvetica, sans-serif; font-size:11px }.iv_thumb_text_popover { font-family: verdana, arial, helvetica, sans-serif; font-size:11px }.iv_thumb_text_hover { background-color: #EAF3FD }</style>';
jQuery(style).appendTo("head");
var thumbHtml="<div class='iv_thumbs'>";
thumbHtml+="</div>";
thumbHtml+="<div class='iv_thumb_videos'>";
thumbHtml+="</div>";
var thumbs=jQuery(thumbHtml);
oRightCol.append(thumbs);
}function constructThumbnails(){var thumbnails;
if(oImageSet&&oImageSet[oCurrentImgSetID]){thumbnails=oImageSet[oCurrentImgSetID].images.thumbnails;
}var thumbHtml="";
var thumbnailNumPerRow=3;
var thumbnailIndex=0;
var thumbnailCount=(thumbnails)?thumbnails.length:0;
thumbnailCount+=availableVideos?availableVideos.length:0;
if(thumbnails){var length=thumbnails.length;
for(var i=0;
i<length;
i++){if(thumbnailIndex%thumbnailNumPerRow==0){thumbHtml+="<div style='height:75px;'>";
}if(i!=oCurrentImgID||useThisDPImage){thumbHtml+="<div class='iv_thumb' id='ivimage_"+i+"'>";
thumbHtml+="<div class='iv_thumb_inner'>";
}else{thumbHtml+="<div class='iv_thumb iv_thumb_selected' id='ivimage_"+i+"'>";
thumbHtml+="<div class='iv_thumb_inner iv_thumb_inner_selected'>";
}thumbHtml+="<div class='iv_thumb_image' style=\"background:url("+getResizedThumbnailURL(thumbnails[i])+') center no-repeat">';
thumbHtml+="</div>";
thumbHtml+="</div>";
thumbHtml+="</div>";
if((thumbnailIndex+1)%thumbnailNumPerRow==0||thumbnailIndex==thumbnailCount-1){thumbHtml+="</div>";
}thumbnailIndex++;
}}jQuery.each(availableVideos||[],function(index,videoHash){if(thumbnailIndex%thumbnailNumPerRow==0){thumbHtml+="<div style='height:75px;'>";
}if(index!=oCurrentVideoID){thumbHtml+="<div class='iv_thumb iv_type_video' id='ivvideo_"+index+"'>";
thumbHtml+="<div class='iv_thumb_inner'>";
}else{thumbHtml+="<div class='iv_thumb iv_thumb_selected iv_type_video' id='ivvideo_"+index+"'>";
thumbHtml+="<div class='iv_thumb_inner iv_thumb_inner_selected'>";
}thumbHtml+="<div class='iv_thumb_image' style=\"background:url("+getResizedVideoThumbURL(videoHash.thumbUrl)+') center no-repeat">';
thumbHtml+="</div>";
thumbHtml+="</div>";
thumbHtml+="</div>";
if((thumbnailIndex+1)%thumbnailNumPerRow===0||thumbnailIndex===thumbnailCount-1){thumbHtml+="</div>";
}thumbnailIndex++;
});
return thumbHtml;
}function constructVideoList(){var thumbHtml="";
jQuery.each(availableVideos||[],function(index,videoHash){thumbHtml+="<div class='iv_thumb_video_outer' id='ivvideolist_"+index+"'>";
thumbHtml+="<div class='iv_thumb_video'>";
thumbHtml+="<div class='iv_thumb_inner'>";
thumbHtml+="<div class='iv_thumb_image' style=\"background:url("+getResizedVideoThumbURL(videoHash.thumbUrl)+') center no-repeat">';
thumbHtml+="</div>";
thumbHtml+="</div>";
thumbHtml+="</div>";
thumbHtml+="<div class='iv_thumb_text'><b>"+videoHash.title+"</b><br>"+videoHash.durationTimestamp+"<div style='clear:both'></div></div>";
thumbHtml+="</div>";
});
return thumbHtml;
}function constructMediaSelection(){var tabHtml='<div style="width:235px; border:1px solid #C9E1F4; background-color:#EAF3FD; padding-top: 5px; padding-bottom: 5px; margin-top:15px; display: none" id="iv-tabbing">';
tabHtml+='<select id="iv_media_select" style="position:relative;left:65px">';
tabHtml+='<option id="all" value="all" selected>'+ivStrings["allMedia"]+"</option>";
tabHtml+='<option id="images" value="images">'+ivStrings["images"]+"</option>";
tabHtml+='<option id="videos" value="videos">'+ivStrings["videos"]+"</option>";
tabHtml+="</select>";
if(jQuery.browser.msie){tabHtml+='<span class="swSprite s_boxLeft" style="top: -14px; left: -102px; display: none;"> </span>  <span class="swSprite s_boxRight" style="top: -14px; left: 111px; display: none;"> </span>';
}else{tabHtml+='<span class="swSprite s_boxLeft" style="top: -12px; left: -102px; display: none;"> </span>  <span class="swSprite s_boxRight" style="top: -12px; left: 108px; display: none;"> </span>';
}tabHtml+="</div>";
var mediaSelection=jQuery(tabHtml);
oRightCol.append(mediaSelection);
}function updateIV(){isIVOpened=true;
jQuery(document.body).css("opacity","");
var bStyle=document.body.style;
if(jQuery.browser.msie&&bStyle&&bStyle.filter==""){bStyle.removeAttribute("filter");
}jQuery("#IV-Main").parents(".ap_popover").css({"top":(jQuery("body").scrollTop()+28)+"px"});
if(isTwisterDetailPage){setImmersiveViewContext();
jQuery(document).trigger("evdd_initialized");
updateVarSelection();
fetchVideoData();
}else{setImmersiveViewContext();
updateMediaSelection();
}resizeIV();
}function resetDP(){jQuery("#iv-large-image").empty();
jQuery(document.body).css("overflow","auto");
jQuery("#ap_container").unbind("keydown");
if(isTwisterDetailPage){EnhancedVariationsDropDown.prototype.hasMadeInitialSelections=0;
if(typeof(goTwisterCore)!="undefined"){for(var dimLabel in oSelectionVariations){goTwisterCore.performManualSelect(dimLabel,oSelectionVariations[dimLabel]);
}}else{if(typeof(twisterController)!="undefined"){for(var dimLabel in oSelectionVariations){twisterController.performManualSelect(dimLabel,oSelectionVariations[dimLabel]);
}}}}if(airyInstance&&!airyInstance.isDetached()){if(airyHelper&&airyHelper.config){airyHelper.config.volume=airyInstance.getVolume();
}airyInstance.detach();
videoContainer.css({width:"1px",height:"1px"});
if(!!document.all&&!window.atob&&!document.addEventListener){airyInstance=null;
}}isIVOpened=false;
jQuery(document).trigger("closed.IV");
}function updateVarSelection(){var pageState=DetailPage.StateController.getState();
var labels=pageState["variation_display_labels"];
for(var index in oVisualKeys){var label=oVisualKeys[index];
var selIndex=pageState["selected_variation_values"][label];
var selection=jQuery("#"+label+"DonsBox").val();
}}function updateMediaSelection(){var imageCount=(oImageSet&&oImageSet[oCurrentImgSetID])?oImageSet[oCurrentImgSetID].images.thumbnails.length:0;
var videoCount=availableVideos?availableVideos.length:0;
var ivThumbs=jQuery(".iv_thumbs");
var ivTabbing=jQuery("#iv-tabbing");
ivThumbs.html(constructThumbnails());
ivThumbs.css({"width":thumbSectionWidth+"px"});
jQuery(".iv_thumb_videos").html(constructVideoList());
addThumbHandlers();
jQuery(".iv_thumb_videos").hide();
var mediaSelection=jQuery("#iv_media_select");
mediaSelection.find("#all").text(ivStrings["allMedia"]+" ("+(imageCount+videoCount)+")");
mediaSelection.find("#videos").remove();
mediaSelection.find("#images").remove();
if(imageCount>0){mediaSelection.append('<option id="images" value="images">'+ivStrings["images"]+" ("+(imageCount)+")</option>");
}if(videoCount>0){mediaSelection.append('<option id="videos" value="videos">'+ivStrings["videos"]+" ("+(videoCount)+")</option>");
ivTabbing.show();
ivThumbs.css({"margin-top":"0px","border-top":"0px"});
}else{ivTabbing.hide();
ivThumbs.css({"margin-top":"15px","border-top":"1px solid #C9E1F4"});
}mediaSelection.val("all");
mediaSelection.change();
if(useThisDPImage){changeMainImage();
}}function fetchVideoData(){if(!isVideoDisabled&&airyHelper){availableVideos=airyHelper.getVideosBySetId(oCurrentVideoSetID)||[];
}updateMediaSelection();
}function prefetchImages(){for(var i=-3;
i<=3;
i++){var id=parseInt(oCurrentImgID)+i;
if(id<0){continue;
}var imgURL=(oImageSet&&oImageSet[oCurrentImgSetID])?oImageSet[oCurrentImgSetID].images.zoomImages[id]:"";
if(imgURL&&oImageLoadState[imgURL]==undefined){var imgObject=jQuery("<img>").attr("src",imgURL);
imgObject.load(function(){oImageLoadState[jQuery(this).attr("src")]=1;
});
}else{if(!imgURL){break;
}}}}var videoInfoPopover;
function addThumbHandlers(){jQuery(".iv_thumb").click(function(event){useThisDPImage=0;
jQuery(".iv_thumb").removeClass("iv_thumb_selected");
jQuery(".iv_thumb").removeClass("iv_thumb_hover");
jQuery(".iv_thumb").find(".iv_thumb_inner").removeClass("iv_thumb_inner_selected");
jQuery(this).addClass("iv_thumb_selected");
jQuery(this).find(".iv_thumb_inner").addClass("iv_thumb_inner_selected");
if(jQuery(this).hasClass("iv_type_video")){oCurrentVideoID=jQuery(this).attr("id").split("_")[1];
playVideo();
}else{oCurrentImgID=jQuery(this).attr("id").split("_")[1];
changeMainImage();
}});
jQuery(".iv_thumb_video_outer").click(function(event){jQuery(".iv_thumb_video").removeClass("iv_thumb_selected");
jQuery(".iv_thumb_video").removeClass("iv_thumb_hover");
jQuery(".iv_thumb_video").find(".iv_thumb_inner").removeClass("iv_thumb_inner_selected");
jQuery(this).find(".iv_thumb_video").addClass("iv_thumb_selected");
jQuery(this).find(".iv_thumb_inner").addClass("iv_thumb_inner_selected");
oCurrentVideoID=jQuery(this).attr("id").split("_")[1];
playVideo();
});
jQuery(".iv_thumb").mouseover(function(event){if(videoInfoPopover){videoInfoPopover.close();
}if(!jQuery(this).hasClass("iv_thumb_selected")){jQuery(this).addClass("iv_thumb_hover");
jQuery(this).find(".iv_thumb_inner").addClass("iv_thumb_inner_selected");
}if(jQuery(this).hasClass("iv_type_video")){var videoIndex=parseInt(jQuery(this).attr("id").split("_")[1]);
if(videoIndex>=availableVideos.length){return;
}var selectedVideo=availableVideos[videoIndex];
var videoContent="<span class='iv_thumb_text_popover'><b>"+selectedVideo.title+"</b><br>"+selectedVideo.durationTimestamp+"</span>";
var leftOffset=(oCurrentVideoID!=-1&&(jQuery(this).offset().left-jQuery(".iv_thumbs").offset().left)<=30)?-27:-50;
var topOffset=-11;
if(jQuery.browser.msie&&parseInt(jQuery.browser.version)==6){topOffset=-16;
}videoInfoPopover=jQuery.AmazonPopover.displayPopover({literalContent:videoContent,width:180,location:["top"],locationElement:this,locationAlign:"middle",locationOffset:[leftOffset,topOffset],zIndex:1000,hoverShowDelay:300,hoverHideDelay:300,showCloseButton:false,attached:true,modal:false});
if(jQuery.browser.msie&&parseInt(jQuery.browser.version)==6){videoInfoPopover.find(".ap_footer").find(".ap_middle").css({position:"relative",height:"30px",width:"112px",top:"-2px",background:"url("+oMediaUrls["arrow"]+") -343px -40px"});
}else{videoInfoPopover.find(".ap_footer").find(".ap_middle").css({position:"relative",height:"30px",width:"112px",top:"-3px",background:"url("+oMediaUrls["arrow"]+") -343px -43px"});
}}});
jQuery(".iv_thumb_video_outer").mouseover(function(event){jQuery(this).addClass("iv_thumb_video_outer_hover");
jQuery(this).find(".iv_thumb_text").addClass("iv_thumb_text_hover");
if(!jQuery(this).find(".iv_thumb_video").hasClass("iv_thumb_selected")){jQuery(this).find(".iv_thumb_video").addClass("iv_thumb_hover");
jQuery(this).find(".iv_thumb_inner").addClass("iv_thumb_inner_selected");
}});
jQuery(".iv_thumb").mouseout(function(event){if(!jQuery(this).hasClass("iv_thumb_selected")){jQuery(this).removeClass("iv_thumb_hover");
jQuery(this).find(".iv_thumb_inner").removeClass("iv_thumb_inner_selected");
}if(videoInfoPopover){videoInfoPopover.close();
}});
jQuery(".iv_thumb_video_outer").mouseout(function(event){jQuery(this).removeClass("iv_thumb_video_outer_hover");
jQuery(this).find(".iv_thumb_text").removeClass("iv_thumb_text_hover");
if(!jQuery(this).find(".iv_thumb_video").hasClass("iv_thumb_selected")){jQuery(this).find(".iv_thumb_video").removeClass("iv_thumb_hover");
jQuery(this).find(".iv_thumb_inner").removeClass("iv_thumb_inner_selected");
}});
jQuery("#ap_container").keydown(function(event){if(event.keyCode==37||event.keyCode==38||event.keyCode==39||event.keyCode==40||event.keyCode==33||event.keyCode==34){return false;
}});
}function addHandlers(){jQuery("#IV-Main").click(function(){jQuery(".DonsBoxRows").css("display","block").hide();
jQuery("#iv_media_select").css("visibility","visible");
});
jQuery(window).resize(function(){resizeIV();
});
jQuery("#iv_media_select").change(function(){if(jQuery(this).val()=="all"){jQuery(".iv_thumb_videos").hide();
jQuery(".iv_thumbs").show();
jQuery(".iv_type_video").show();
}else{if(jQuery(this).val()=="images"){jQuery(".iv_thumb_videos").hide();
jQuery(".iv_thumbs").show();
jQuery(".iv_type_video").hide();
}else{if(jQuery(this).val()=="videos"){jQuery(".iv_thumb_videos").show();
jQuery(".iv_thumbs").hide();
}}}clearAllSelections();
selectCurrentImage();
});
}function resizeIV(){var height=jQuery(window).height()-heightAdjustment;
var width=(jQuery(window).width()-widthAdjustment);
if(height>230){jQuery("#IV-Main").css({"height":(height)+"px"});
jQuery("#iv-large-image").css({"height":(height-15)+"px"});
var thumbsSecHeight=(height-thumbSectionHeightAdjustment);
jQuery(".iv_thumbs").css({"height":(thumbsSecHeight)+"px"});
jQuery(".iv_thumb_videos").css({"height":(thumbsSecHeight+videoListHeightAdjustment)+"px"});
}if(width>500){jQuery("#IV-Main").parents(".ap_popover").css({"width":(width)+"px"});
jQuery("#iv-first-column").css({"width":(width-330)+"px"});
}if(!isPlayingVideo){imageFit();
}}function changeMainImage(){if(airyInstance){airyInstance.hide();
}videoContainer.css({width:"1px",height:"1px"});
jQuery("#iv-large-image").css("display","block");
var currentDetailImageUrl="";
if(useThisDPImage){currentDetailImageUrl=oImageSet[useThisDPImage].images.zoomImages[oCurrentImgID];
if(!currentDetailImageUrl){playVideo();
return;
}}else{if(oImageSet&&oImageSet[oCurrentImgSetID]){currentDetailImageUrl=oImageSet[oCurrentImgSetID].images.zoomImages[oCurrentImgID];
}}if(!currentDetailImageUrl){return;
}oFullImageLarge="<img src='"+currentDetailImageUrl+"'class='fullScreen'/>";
var oFullImageFit=jQuery("<img>").attr("src",currentDetailImageUrl);
oFullImageFit.addClass("fullScreen");
var largeImage=jQuery("#iv-large-image");
largeImage.animate({opacity:0.4},200,function(){oFullImageFit.load(function(){loadImage();
});
jQuery(oFullImageLarge).load(function(){loadImage();
});
if(!oImageLoadState[oFullImageFit.attr("src")]){isImageLoading=true;
largeImage.empty();
var top=(oLeftCol.height()-nSpinnerLength)/2;
var left=(oLeftCol.width()-nSpinnerWidth)/2;
jQuery("#iv-large-image").append("<img src='"+oMediaUrls["spinner"]+"' style='position:relative;top:"+top+"px;left:"+left+"px;' />");
}else{loadImage();
}});
oFullImageFit.load(function(){oImageLoadState[oFullImageFit.attr("src")]=1;
prefetchImages();
});
jQuery(oFullImageLarge).load(function(){oImageLoadState[oFullImageFit.attr("src")]=1;
prefetchImages();
});
function loadImage(){isImageLoading=false;
if((useThisDPImage&&oImageSet[useThisDPImage].images.zoomImages[oCurrentImgID]!=oFullImageFit.attr("src"))||(!useThisDPImage&&oImageSet[oCurrentImgSetID].images.zoomImages[oCurrentImgID]!=oFullImageFit.attr("src"))){return;
}largeImage.css("visibility","hidden");
largeImage.empty();
largeImage.animate({opacity:1},200);
largeImage.append(oFullImageFit);
imageFit();
isPlayingVideo=false;
oImageLoadState[oFullImageFit.attr("src")]=1;
}}function playVideo(){if(!airyHelper||!videoContainer||!availableVideos||!availableVideos[oCurrentVideoID]){return;
}var videoHash=availableVideos[oCurrentVideoID];
jQuery("#iv-large-image").css("display","none").empty();
videoContainer.css({width:"100%",height:"100%"});
isPlayingVideo=true;
if(airyInstance){if(airyInstance.isDetached()){airyInstance.attach(videoContainer[0]);
}airyHelper.loadMedia(airyInstance,videoHash,airyHelper.config);
airyInstance.show();
airyInstance.play({isAsync:true});
return;
}airyInstance=airyHelper.embedChromeful(videoContainer,videoHash,airyHelper.config,"ImmersiveView");
if(airyConfig.enableContinuousPlay){airyInstance.bind("ended",selectNextVideo);
}airyInstance.play({isAsync:true});
}function selectNextVideo(){var nextVideoNum=parseInt(ivCurrentVideoSelected)+1;
if(nextVideoNum>=availableVideos.length){return;
}var nextVideoThumbId="#ivvideo_"+nextVideoNum;
$(nextVideoThumbId).click();
}function prefetchResources(){jQuery("<img>").attr("src",""+oMediaUrls["arrow"]+"");
jQuery("<img>").attr("src",""+oMediaUrls["zoomIn"]+"");
jQuery("<img>").attr("src",""+oMediaUrls["zoomOut"]+"");
}function doBrowserAdjustment(){if(jQuery.browser.msie){thumbSectionWidth=235;
heightAdjustment=123;
videoListHeightAdjustment=0;
thumbSectionHeightAdjustment=isTwisterDetailPage?115+(oVisualKeys.length*50):95;
}else{thumbSectionHeightAdjustment=isTwisterDetailPage?125+(oVisualKeys.length*50):125;
}}function imageFit(){isLargeMode=false;
var ww=oLeftCol.width();
var wh=oLeftCol.height();
var fullImageFit=oIV.find(".fullScreen");
fullImageFit.removeAttr("style");
oFullImageWidth=fullImageFit.width();
oFullImageHeight=fullImageFit.height();
oLeftCol.css({"cursor":"auto"});
if(((oFullImageWidth>=1000)||(oFullImageHeight>=1000))){if(jQuery.browser.mozilla){oLeftCol.css({"cursor":"-moz-zoom-in"});
}else{oLeftCol.css({"cursor":"url('"+oMediaUrls["zoomIn"]+"'), auto"});
}}oFullImageWidth=oFullImageWidth==0?1:oFullImageWidth;
oFullImageHeight=oFullImageHeight==0?1:oFullImageHeight;
var scale=Math.min(ww/oFullImageWidth,wh/oFullImageHeight);
var fitHeight=oFullImageHeight*scale;
var fitWidth=oFullImageWidth*scale;
var imgHeight;
if(fitHeight<oFullImageHeight){imgHeight=fitHeight-20;
}else{imgHeight=oFullImageHeight;
}fullImageFit.css("height",imgHeight);
fullImageFit.css("width",Math.min(fitWidth,oFullImageWidth));
var left=((ww-fullImageFit.width())/2);
var top=((wh-fullImageFit.height())/2);
fullImageFit.css("margin-top",top);
fullImageFit.css("margin-left",left);
jQuery("#iv-large-image").css("visibility","visible");
}function setupMaxOffset(){var fullImageFit=oIV.find(".fullScreen");
oFullImageWidth=fullImageFit.width();
oFullImageHeight=fullImageFit.height();
maxOffset.left=oLeftCol.width()-oFullImageWidth;
maxOffset.top=oLeftCol.height()-oFullImageHeight;
}function getIndex(label,obj){var length=obj.length;
for(var i=0;
i<length;
i++){if(obj[i]==label){return i;
}}return -1;
}function getReachableAsins(){var aAsinList=new Array();
var count=0;
var dpState=DetailPage.StateController.getState();
if(!dpState){return;
}var sLookup="";
if(typeof gIsNewTwister!="undefined"&&gIsNewTwister!=0){if(oPreferChildVideos){var val="";
for(var index in oVisualKeys){var label=oVisualKeys[index];
val+=(parseInt(oSelectionVariations[label])+1);
if(index<(oVisualKeys.length-1)){val+="-";
}}aAsinList.push(oIVRepresentativeAsin[val]);
return aAsinList;
}else{for(var color in oItemList){if(oItemList.hasOwnProperty(color)){if(oItemList[color]["asin"]){aAsinList.push(oItemList[color]["asin"]);
}}}return aAsinList;
}}else{for(var sVarKey in dpState["selected_variation_values"]){if(sVarKey in oSelectionVariations){if(oSelectionVariations[sVarKey]!=-1){sLookup+=(oSelectionVariations[sVarKey]+" ");
}else{sLookup=null;
break;
}}else{sLookup+="-1 ";
}}}if(sLookup!=null){var oItems=oItemList[sLookup];
for(var nVarValue in oItems){aAsinList[count]=oItems[nVarValue];
count++;
}}return aAsinList;
}function getCurrentAsin(dpState){if(!dpState){dpState=DetailPage.StateController.getState();
}var currentAsin=null;
if(dpState){currentAsin=dpState["current_asin"];
}return currentAsin;
}function getResizedThumbnailURL(url){url=url.replace(/'/g,"").replace("._SL75_","").replace(/\._(AA|SS)\d+_/,"").replace(/\._SX\d+_SY\d+_CR,0,0,\d+,\d+_/,"");
var index=url.lastIndexOf(".");
url=url.substring(0,index)+"._AA50_"+url.substring(index);
return url;
}function getResizedVideoThumbURL(url){return url.replace(/\._(SS|AA)\d+_PImini-player-shuttle-50px,BottomLeft,\-?\d,\-?\d_/,"._SS46_PImini-player-shuttle-50px,BottomLeft,-2,3_");
}function trimWithEllipsis(str,maxCharacters){str=new String(str);
var trimmedStr=str;
if(str.length>maxCharacters){try{var index=-1;
for(var i=0;
i<str.length;
i++){var c=str.charAt(i);
if(c==" "||c=="."||c=="?"||c==";"||c==","||c==":"){index=i;
}if(i==maxCharacters-4){var trimIndex=(index==-1?i:index);
trimmedStr=str.substring(0,trimIndex);
break;
}}}catch(e){trimmedStr=str.substring(0,maxCharacters-3);
}trimmedStr+="...";
}return trimmedStr;
}function clearAllSelections(){jQuery(".iv_thumb").removeClass("iv_thumb_selected");
jQuery(".iv_thumb").removeClass("iv_thumb_hover");
jQuery(".iv_thumb_video").removeClass("iv_thumb_selected");
jQuery(".iv_thumb_video").removeClass("iv_thumb_hover");
}function selectCurrentImage(){if(jQuery("#iv_media_select").val()=="videos"){oCurrentVideoID=(oCurrentVideoID!=-1)?oCurrentVideoID:0;
oCurrentImgID=-1;
jQuery(".iv_thumb_video_outer:eq("+(oCurrentVideoID)+")").click();
}else{if(jQuery("#iv_media_select").val()=="images"){oCurrentImgID=(oCurrentImgID!=-1)?oCurrentImgID:0;
}if(oCurrentImgID!=-1&&!useThisDPImage){jQuery(".iv_thumb:eq("+oCurrentImgID+")").click();
}else{if(oCurrentVideoID!=-1){var firstVideoID=jQuery("[id^=ivimage_]").length;
var vidID=parseInt(oCurrentVideoID)+firstVideoID;
jQuery(".iv_thumb:eq("+(vidID)+")").click();
}}}}function getFullScreenOffset(offset){var newOffset=offset;
if(maxOffset.left>0){newOffset.left=maxOffset.left/2;
}else{if(offset.left<maxOffset.left){newOffset.left=maxOffset.left;
}else{if(offset.left>0){newOffset.left=0;
}}}if(maxOffset.top>0){newOffset.top=maxOffset.top/2;
}else{if(offset.top<maxOffset.top){newOffset.top=maxOffset.top;
}else{if(offset.top>0){newOffset.top=0;
}}}return newOffset;
}function largeMode(){if(!((oFullImageWidth>=1000)||(oFullImageHeight>=1000))){return;
}if(jQuery.browser.mozilla){oLeftCol.css({"cursor":"-moz-zoom-out"});
}else{oLeftCol.css({"cursor":"url('"+oMediaUrls["zoomOut"]+"'), auto"});
}isLargeMode=true;
var largeImage=oLeftCol.find("#iv-large-image");
setupMaxOffset();
var centerHeight=oLeftCol.height()/2;
var centerWidth=oLeftCol.width()/2;
cursorStart=[largeImage.offset().left+centerWidth,largeImage.offset().top+centerHeight];
initialOffset.top=centerHeight-oFullImageHeight/2;
initialOffset.left=centerWidth-oFullImageWidth/2;
oLeftCol.find(".fullScreen").css({position:"relative",left:initialOffset.left,top:initialOffset.top});
fullScreenMoveFactor=Math.max(oFullImageHeight/oLeftCol.height(),oFullImageWidth/oLeftCol.width());
fullScreenMoveFactor=Math.max(fullScreenMoveFactor,DEFAULT_FULL_SCREEN_MOVE_FACTOR);
}function EnhancedVariationsDropDown(){EnhancedVariationsDropDown.prototype.DonsBoxes=new Object();
EnhancedVariationsDropDown.prototype.initialized=0;
EnhancedVariationsDropDown.prototype.initialize=function(){if(EnhancedVariationsDropDown.prototype.initialized){return;
}jQuery(document).bind("evdd_initialized",function(){if(!EnhancedVariationsDropDown.prototype.initialized){for(var i in oVisualKeys){var label=oVisualKeys[i];
var dropDownRows=EnhancedVariationsDropDown.prototype.getDropDownRowsMatrix(label,false);
var previewRows=EnhancedVariationsDropDown.prototype.getDropDownRowsMatrix(label,true);
oSingleton=(oVisualKeys.length==1&&dropDownRows.length==1);
var donsBoxArgs={defaultMessage:ivStrings["pleaseSelect"],id:label+"_IV_DonsBox",dropDownRowsMatrix:dropDownRows,previewRowsMatrix:previewRows,locationElement:"#"+label+"IVDonsBoxParent",onSelect:function(donsBox,index){var varKey=-1;
varKey=donsBox.getId().substring(0,donsBox.getId().lastIndexOf("_IV_DonsBox"));
EnhancedVariationsDropDown.prototype.onSelect(varKey,index);
},onOpen:function(donsBox,index){var isIE6=jQuery.browser.msie&&parseInt(jQuery.browser.version)==6&&!window["XMLHttpRequest"];
if(isIE6){jQuery("#iv_media_select").css("visibility","hidden");
}},onClose:function(donsBox,index){jQuery("#iv_media_select").css("visibility","visible");
},width:215,singleRowBehavior:(oVisualKeys.length>1)?"AUTO_SELECT":"LABEL"};
EnhancedVariationsDropDown.prototype.DonsBoxes[i]=new DonsBox(donsBoxArgs);
}}var initialSelection=oCurrentImgSetID.split("-");
if(initialSelection[0]=="x"){if(EnhancedVariationsDropDown.prototype.DonsBoxes[0]){EnhancedVariationsDropDown.prototype.DonsBoxes[0].selectRow(0);
}else{updateMediaSelection();
}}else{for(var box in oDonsBoxes){var i=oDonsBoxes[box];
var imageSetIndex=initialSelection[i]-1;
if(imageSetIndex>=0){EnhancedVariationsDropDown.prototype.DonsBoxes[i].selectRow(imageSetIndex);
}}}EnhancedVariationsDropDown.prototype.hasMadeInitialSelections=1;
EnhancedVariationsDropDown.prototype.initialized=1;
});
};
}this.initialize=function(){EnhancedVariationsDropDown.prototype.initialize();
};
EnhancedVariationsDropDown.prototype.getDropDownRowsMatrix=function(varKey,isPreview){var output=new Array();
var dimensionValues=DetailPage.StateController.getState()["variation_values"][varKey];
if(!dimensionValues){return output;
}var hasSwatches=false;
for(var i=0;
i<dimensionValues.length;
i++){if(oSwatchImages[varKey+"-"+dimensionValues[i]]){hasSwatches=true;
break;
}}var swatchSize=((isPreview||!hasSwatches)?"20px":"30px");
for(var i=0;
i<dimensionValues.length;
i++){var varValueDiv=new String('<div style="width: 190px; height: '+swatchSize+'; overflow:hidden" class="DonsBoxNotHighlighted" '+'title="'+dimensionValues[i]+'">'+dimensionValues[i]+"</div>");
output[i]=new Array();
if(hasSwatches){var swatchURL=oSwatchImages[varKey+"-"+dimensionValues[i]];
if(swatchURL){var index=swatchURL.indexOf("25px");
if(index>=0){if(isPreview){swatchURL=swatchURL.replace(/25px/g,swatchSize);
varValueDiv=varValueDiv.replace(/190px/g,"165px");
}else{swatchSize="25px";
varValueDiv=varValueDiv.replace(/190px/g,"160px");
varValueDiv=varValueDiv.replace(/30px/g,"25px");
}}else{varValueDiv=varValueDiv.replace(/190px/g,(isPreview)?"155px":"150px");
}swatchURL=swatchURL.replace(/20px/g,swatchSize);
}swatchURL=swatchURL||'<div style="margin: 0px 5px; width: '+swatchSize+"height: "+swatchSize+';"></div>';
output[i][0]=swatchURL;
output[i][1]=varValueDiv;
}else{output[i][0]=varValueDiv;
}}return output;
};
EnhancedVariationsDropDown.prototype.onSelect=function(varKey,nVarVal){var lastMasterFound=false;
var asinValues=DetailPage.StateController.getState()["asin_variation_values"];
if(noImageChidlASINs==undefined){noImageChidlASINs=new Array();
for(var childASIN in asinValues){var oCurrentImgSetIDTemp="";
for(var index in oVisualKeys){var key=oVisualKeys[index];
oCurrentImgSetIDTemp+=(+asinValues[childASIN][key]+1)+"-";
}oCurrentImgSetIDTemp=oCurrentImgSetIDTemp.substring(0,oCurrentImgSetIDTemp.length-1);
if(!oImageSet[oCurrentImgSetIDTemp]){noImageChidlASINs.push(childASIN);
}}}var invalidChildASINs=new Array();
jQuery.extend(invalidChildASINs,noImageChidlASINs);
for(var box in oDonsBoxes){var key=oVisualKeys[oDonsBoxes[box]];
var selID=key+"_IV_DonsBox";
var selection=jQuery("#"+selID).val();
jQuery("tr[id^='"+key+"_IV_DonsBox_DonsBoxRow_']").css("display","none");
if(lastMasterFound||oVisualKeys.length==1){var minIndex=-1;
for(var childASIN in asinValues){if(getIndex(childASIN,invalidChildASINs)>=0){continue;
}if(minIndex==-1||asinValues[childASIN][key]<minIndex){minIndex=asinValues[childASIN][key];
}jQuery("tr#"+key+"_IV_DonsBox_DonsBoxRow_"+asinValues[childASIN][key]).css("display","");
}if(minIndex!=-1&&varKey!=key&&minIndex!=selection){EnhancedVariationsDropDown.prototype.DonsBoxes[oDonsBoxes[box]].selectRow(minIndex);
}}else{for(var childASIN in asinValues){if(getIndex(childASIN,invalidChildASINs)>=0){continue;
}jQuery("tr#"+key+"_IV_DonsBox_DonsBoxRow_"+asinValues[childASIN][key]).css("display","");
if(asinValues[childASIN][key]!=selection){invalidChildASINs.push(childASIN);
}}if(key==varKey){lastMasterFound=true;
}}}oCurrentImgSetIDTemp="";
for(var index in oVisualKeys){var selID=oVisualKeys[index]+"_IV_DonsBox";
oSelectionVariations[oVisualKeys[index]]=jQuery("#"+selID).val();
oCurrentImgSetIDTemp+=(+jQuery("#"+selID).val()+1)+"-";
}oCurrentImgSetIDTemp=oCurrentImgSetIDTemp.substring(0,oCurrentImgSetIDTemp.length-1);
if(useThisDPImage){useThisDPImage=oCurrentImgID=0;
}if(oImageSet&&oImageSet[oCurrentImgSetIDTemp]&&oCurrentImgSetIDTemp!=oCurrentImgSetID){useThisDPImage=(oCurrentImgSetID.charAt(0)=="x"&&!oSingleton)?oCurrentImgSetID:0;
if(EnhancedVariationsDropDown.prototype.hasMadeInitialSelections||useThisDPImage){oCurrentVideoSetID=oCurrentImgSetID=new String(oCurrentImgSetIDTemp);
if(!useThisDPImage){oCurrentImgID=0;
}oCurrentVideoID=-1;
fetchVideoData();
}}};
EnhancedVariationsDropDown.prototype.initialize();
return this;
};
if(typeof(gIsNewTwister)!="undefined"&&gIsNewTwister){amznJQ.available("DonsBoxJS",function(){amznJQ.available("newTwister",function(){amznJQ.declareAvailable("immersiveView");
});
});
}else{if(typeof(isTwisterPage)=="undefined"||!isTwisterPage){amznJQ.declareAvailable("immersiveView");
}else{amznJQ.available("twister",function(){amznJQ.declareAvailable("immersiveView");
});
}}})();
