/*
 Copyright (c) 2013 Amazon.com, Inc.  All rights reserved.

 @see "http://g-ec2.images-amazon.com/images/G/01/vap/Airy_Video_Player_-_OSS_Attribution__2014.07.19_._V359054309_.docx"
*/
var j=void 0,q=null;function w(){return function(){}}
(function(o,r,D){function ea(){var a=c.g.lb("div",{backgroundColor:"black",position:"relative",width:"100%",height:"100%",fontSize:"0px",overflow:"hidden"});return c.g.Fd(a,"airy")}function fa(a){a=a||{};return c.compact({td:a.isEngineEnabled,Tq:a.networkId,profile:a.profile,Zq:a.sectionId,ar:a.serverUrl})||{}}function O(a){var a=a||{},b=a.rn||x.bb;this.Kl=this.$k(a.vc);this.Ci=[b];a.Gn||this.Ci.push(b===x.bb?x.Fc:x.bb)}function P(a){this.re=a;this.pm=new Q(a)}function Q(a){this.re=a;this.gm=new R(a)}
function R(a){this.re=a}function S(a,b){this.om=a;this.nl=b;this.Fl=c.g.Ym(b)}function T(a){var b=this.C=a.C||c.g.lb("div");b.unselectable="on";b.oncontextmenu=function(){return!1};this.id=a.id;this.Ta=a.Ta;var b=a.qn,e=a.fp;if(e){if(e&&!b)throw"State infos were provided, but no default state was specified for View: "+id;this.Re=b;this.cd=e;this.Ve=a.Ve;this.di=this.we(H.Kn,this.bl);this.vb={yd:this.we(H.Pn,this.gh),Bd:this.we(H.Rn,this.gh)};this.df=this.isEnabled=this.Da=!0}}function H(a,b,c,f){this.Qe=
a.join(" ");this.style=b;this.ci=c||{};this.vb=f||{}}function U(a){this.qm=a}function K(a,b){this.f=a;c.t(this,b);a.w.v(d.G.he,{j:this.j,h:c.m()});this.I(a)}function V(a,b){this.pa=a;this.xe=b}function W(a){this.fd=a.fd||ga}function L(a,b){this.f=a;c.t(this,b);this.I(a)}function X(){this.Hh={}}function Y(a){this.Uc=a;this.Rl={};this.th={};this.mh={};this.wh={}}function y(){this.Wc={}}function u(a,b){return c.map(b,function(b,c){return a+c})}var ha=o.console||{log:w(),info:w(),warn:w(),error:w()},
z=Array.prototype,A=z.slice,ia=z.push,ja=Object.prototype.toString,c={Sh:function(a,b,c){(a[b]||(a[b]=[])).push(c)},compact:function(a){if(a){var b=c.isArray(a),e=b?[]:{};c.l(a,function(a,c){c&&(b?e.push(c):e[a]=c)});return e}},m:function(){return(new Date).valueOf()},nn:function(a,b,e){return!c.jc(a)?j:c.map(a,function(a,d){c.jc(d)?d=c.nn(d,b,e):d&&(d=b.call(e||this,a,d));return d})},l:function(a,b,e){if(a){var f=0,d=a.length;if(c.isArray(a)||c.ko(a))for(;f<d;f++)b.call(e||a[f],f,a[f]);else for(f in a)c.Bb(a,
f)&&b.call(e||a[f],f,a[f]);return a}},error:function(a){throw Error(a);},every:function(a,b,e){var f=!1;c.l(a,function(a,c){f=f||!b.call(e,a,c)},e);return!f},filter:function(a,b,e){var e=e||this,f=[],d=0;c.l(a,function(a,c){b.call(e,a,c)&&(f[d++]=c)});return f},find:function(a,b,c){for(var f=0;f<a.length;f++){var d=a[f];if(b.call(c||this,f,d))return d}return q},md:function(a){return a&&a.length?a[0]:j},lm:0,Ab:function(){return this.lm++},Bb:function(a,b){return a.hasOwnProperty(b)},o:function(a,
b,e){function f(){this.constructor=d}var d=b&&c.Bb(b,"constructor")?b.constructor:function(){return a.apply(this,arguments)};c.t(d,a,e||{});f.prototype=a.prototype;d.prototype=new f;b&&c.t(d.prototype,b);d.prototype["super"]=a.prototype;return d},jc:function(a){return a===Object(a)},isArray:Array.isArray||function(a){return c.La(a,"Array")},Nq:function(a){return c.La(a,"Document")||c.La(a,"XMLDocument")},ff:function(a){return a&&a.nodeType===1},si:function(a){return c.La(a,"Function")},Oq:function(a){return c.ud(a)&&
a!=+a},ko:function(a){return c.La(a,"NodeList")},ud:function(a){return c.La(a,"Number")},vd:function(a){return c.La(a,"Object")},Pq:function(a){return c.La(a,"RegExp")},Ra:function(a){return c.La(a,"String")},La:function(a,b){return ja.call(a)==="[object "+b+"]"},join:function(a,b,e){var e=e||{},f=e.qo||this.Ad,d=e.Od||this.Ad,h=e.xd||"",i=c.isArray(a),k=[];c.l(a,function(a,b){var c=!i?f(a)+h:"";c+=d(b);ia.call(k,c)},this);return k.join(b||"")},keys:function(a){var b=[];c.l(a,function(a){b.push(a)});
return b},Sa:function(a){return a==q?[]:c.isArray(a)?a:[a]},map:function(a,b,e){if(a){var f=c.isArray(a)?[]:{};c.l(a,function(c,d){f[c]=b.call(e||a[c],c,d)});return f}},nf:function(a,b,e){if(!a)return{};var f={};c.l(a,function(a,c){var d=b.call(e,a,c);d&&(f[d]=c)});return f},Eb:function(a,b){var c;return function(){return c!=q?c:c=a.call(b)}},t:function(a){var b;c.l(A.call(arguments,1),function(c,f){if(f)for(b in f)try{a[b]=f[b]}catch(d){}});return a},M:w(),Ad:function(a){return a},Uq:function(a,
b){return function(){return!a.apply(b||this,arguments)}},Wq:function(a){return a==="true"},Lf:function(a){if(!c.isArray(a))return c.t({},a);var b=[];c.l(a,function(a,c){b.push(c)});return b},some:function(a,b,e){return c.find(a,b,e)!=q},Zo:function(a){var b=0;c.l(a,function(a,f){c.ud(f)&&(b+=f)});return b},unshift:function(a){var b=A.call(arguments,1);return b.length?b.concat(a):a},sa:function(a){var b=[];c.l(a,function(a,c){b.push(c)});return b},Qd:function(a,b,e){var f=A.call(arguments,3);return function(){var d=
f.concat(A.call(arguments));return b.apply(e||this,c.unshift(d,a))}}},B={ej:"Chrome",rj:"Firefox",xj:"MSIE",yj:"IEMobile",Vj:"Opera",Eg:"Safari",Jg:"Silk"},E={Uf:"Android",Wi:"ARM",Aj:"iPad",Bj:"iPhone",Cj:"iPod",Ak:"Windows"},k={Xi:"audioContainer",Yi:"audioElements",cj:"autoplayHint",Hb:"autoplayHintStage",Zi:"audioScrubber",$i:"audioScrubberBar",aj:"audioToggle",bj:"audioTrackBar",Wa:"controlsContainer",Hp:"contentTitle",hj:"currentTimeLabel",kj:"durationLabel",Hj:"loadingSpinner",Hc:"playToggle",
fe:"playToggleHint",eb:"playToggleHintStage",bk:"progressBar",fk:"replayHint",ie:"replayHintStage",tk:"trackBar",Pg:"trackBarContainer",Fg:"screenSizeToggle",jk:"scrubber",kk:"scrubberBar",hq:"stage",wk:"videoQualityToggle",kp:"adsAudioToggle",lp:"adsControlsContainer",mp:"adsPlayToggleHint",np:"adsPlayToggleHintStage",qp:"adsScreenSizeToggle",Dp:"clickThroughStage",Ej:"learnMore",nq:"timeRemainingLabel"},I={eg:"hd",Gg:"sd"},ga=I.Gg,z={sj:"flashbasic",Pp:"flashhls",bb:"html",Rp:"iframe"},Z={LINEAR:"linear",
rg:"nonlinear"},Z={LINEAR:"linear",rg:"nonlinear"},i={O:"ads",Lb:"default",k:"primary"},m={Ka:"start",Ob:"impression",Vd:"end"},d={O:{jq:"startadsplayback",qk:"stopadsplayback",Ag:"prepareforadsux",Lc:"showadsux",Nb:"hideadsux",hk:"retrieveadsresponse",pp:"adsresponsereceived",op:"adsresponseparsed",Uj:"noprerollsfound",Ui:u("adpod.",m),rp:u("adinstance.",m),Ip:u("creative.",m),J:{Bc:{Ga:"engagement",O:u("ad.",{Ej:"learnMoreCount"})},L:{Ga:"error",O:u("ad.",{aq:"response.loadCount",$p:"response.interpretCount",
Rg:"undefinedCount"})},K:{Ga:"qos",O:u("ad.",{Cg:"requestDuration",kq:"startDelayDuration",Bg:"rebufferingDuration",bq:"resumeContentDelayDuration",Vp:"playToPrerollStartDuration"})},qq:u("vast.",{ip:"acceptinvitation",jp:"acceptinvitationlinear",ya:"click",Ep:"close",Fp:"closelinear",Gp:"collapse",Jb:"complete",Xf:"creativeview",L:"error",Op:"expand",$f:"exitfullscreen",Cc:"firstquartile",cg:"fullscreen",Ob:"impression",Gc:"midpoint",Qb:"mute",F:"pause",Ic:"progress",tb:"resume",cq:"rewind",gq:"skip",
Ka:"start",Pc:"thirdquartile",Wb:"unmute"}),sq:u("vmap.",{Bp:"breakstart",Ap:"breakend",L:"error"})}},Kb:{Hc:{de:"pauseState",ee:"playState"},ne:"trackbarsetoffsets"},u:{zc:"bufferstart",Sd:"bufferend",Ea:"canplay",Ud:"durationchange",za:"ended",L:"error",og:"loadedmetadata",ng:"loadeddata",Xa:"playheadupdate",Ic:"progress",iq:"stalled",zk:"waiting"},L:{Yf:"decodeerror",qg:"networkerror",Rg:"undefinederror",oe:"videounsupported"},G:{Mb:"embed",Wd:"initstart",he:"rendererinit",Lg:"swfready",sb:"rendererready",
Kg:"sizecontrollerready",me:"skinfetchinit",Dg:"resourceadded",Ub:"skinloaded",Qg:"uiready"},J:{Bc:{Ga:"engagement.",k:u("primary.",{fj:"completeCount",uj:"fullScreenCount",Rj:"muteCount",Tj:"normalScreenCount",Xj:"pauseCount",gk:"resumeCount",nk:"skipBackwardCount",ok:"skipForwardCount",pk:"startCount",vk:"unmuteCount",yk:"viewedDuration"})},L:{Ga:"error.",k:u("primary.",{ae:"response.loadCount",Xd:"response.interpretCount",uk:"undefinedCount",xk:"videoUnsupportedCount"}),gb:u("skin.",{ae:"response.loadCount",
Xd:"response.interpretCount"})},K:{Ga:"qos.",INIT:u("init.",{oj:"embedToInitStartDuration",nj:"embedToInitCompleteDuration",pj:"embedToSkinLoadedDuration"}),k:u("primary.",{Kj:"loadVideoToLoadedMetadataDuration",Jj:"loadVideoToLoadedDataDuration",Ij:"loadVideoToCanPlayDuration",ak:"playToLoadedMetadataDuration",$j:"playToLoadedDataDuration",Zj:"playToCanPlayDuration",yg:"playToFirstFrameDuration",ek:"rebufferEventCount",Bg:"rebufferingDuration",gj:"createRendererDuration"}),gb:u("skin.",{Gj:"loadedToUiReadyDuration",
Cg:"requestDuration"})},Tg:u("video",{ya:"Click",Jb:"Complete",Xf:"CreativeView",$f:"ExitFullscreen",Cc:"FirstQuartile",cg:"Fullscreen",Ob:"Impression",Gc:"Midpoint",Qb:"Mute",F:"Pause",fa:"Replay",tb:"Resume",Mc:"SkipBackward",Nc:"SkipForward",Ka:"Start",Pc:"ThirdQuartile",Wb:"Unmute"})},b:{Gb:"attach",xc:"audiooff",yc:"audioon",pb:"changeactiverenderer",Va:"changevideoquality",da:"changevolume",Wf:"changedisplayadsmetriceventnamesuffix",CLOSED:"closed",Ac:"detatch",Aa:"fullscreen",Ec:"hideplayer",
fg:"hiderenderer",N:"loadvideo",na:"normalscreen",F:"pause",tg:"paused",B:"play",xg:"playing",vg:"playerhidden",wg:"playershown",ge:"prefetch",fa:"replay",Kc:"screenchange",Ha:"seek",le:"showplayer",Ig:"showrenderer",Ia:"seeked",Hg:"seeking",Ja:"shouldstartplayback",lk:"shouldresumeplayback",Oc:"stageclick",oa:"userinteraction"}},x={bb:"html",Fc:"hybrid"},p={ya:"click",Td:"mousedown",qb:"mousemove",ce:"mouseout",sg:"mouseover",Sg:"mouseup"},m={Cp:"touchcancel",Vd:"touchend",Fj:"touchleave",qb:"touchmove",
Ka:"touchstart"},F={};F[p.Td]=m.Ka;F[p.qb]=m.qb;F[p.ce]=m.Fj;F[p.sg]=m.Ka;F[p.Sg]=m.Vd;var m={bg:"video/x-flv",pg:"video/m3u8",ma:"video/mp4",be:"video/ogg",Vg:"video/webm"},ka={"3g2":m.ma,"3gp":m.ma,flv:m.bg,m3u8:m.pg,m4a:m.ma,m4p:m.ma,m4r:m.ma,m4v:m.ma,mp4:m.ma,mov:m.ma,ogg:m.be,ogv:m.be,webm:m.Vg};c.q={ji:c.Eb(function(){var a=c.q.A,b;for(b in a){var e=a[b]();if(e)return e}}),af:function(a,b){var a=a||this.ji(),c=this.Ji(a+(b||" ([\\d.]+);"));return c.length>1?parseFloat(c[1]):-1},A:{Ib:function(){return c.q.ia(E.Uf)},
dj:function(){return c.q.ia(E.Wi)},ij:function(){return c.q.ia(B.ej)},Qp:function(){return c.q.ia(B.rj)},Yd:function(){return this.jg()||this.Zd()||!this.hg()&&!this.ig()&&!this.$d()},jg:function(){return this.Ib()&&c.q.af(E.Uf)>3},Zd:function(){return this.Vb()&&c.q.af(B.Jg,"\\/([\\d\\.]+)")>=3.4},Pb:function(){return c.q.ia(B.xj)&&!this.$d()},Dj:function(){return this.Pb()&&this.dj()},lg:function(){return r.all&&!o.atob},kg:function(){return this.lg()&&!r.addEventListener},$d:function(){return c.q.ia(B.yj)},
zj:function(){return this.gg()||this.hg()||this.ig()},gg:function(){return c.q.ia(E.Aj)},hg:function(){return c.q.ia(E.Bj)},ig:function(){return c.q.ia(E.Cj)},Fa:function(){return this.Ib()||this.$d()||this.zj()||this.Vb()},Wj:function(){return c.q.ia(B.Vj)},Mg:function(){return c.q.A.ij()?"":c.q.ia(B.Eg)},rk:function(){return c.q.A.Mg()&&c.q.ia(B.Eg+"/534.59.8")},Vb:function(){return c.q.ia(B.Jg)},Bk:function(){return c.q.ia(E.Ak)}},ia:function(a){return this.Ji(a)[0]||""},Ji:function(a){return navigator.userAgent.match(RegExp(a,
"i"))||[]}};c.q.A=c.map(c.q.A,function(a,b){return c.Eb(b,c.q.A)});c.g={Oh:function(a,b,e){var f=c.nf(e,function(a,b){return b}),d=[];c.l((a||[]).concat(b||[]),function(a,b){f[b]||d.push(b)});return d},Na:function(a,b){a&&b&&c.t(a.style,b)},ib:function(a,b){b&&a&&b.appendChild(a)},bind:function(a,b,e,f){a&&(b=c.isArray(b)?b:b.split(" "),c.l(b,function(b,c){this.Yb(a,c,e,f)},this))},Yb:function(a,b,c,f){b&&(a.addEventListener?a.addEventListener(b,c,f||!1):a.attachEvent("on"+b,c))},Wh:function(a,b,
e){b=c.join(b," ",{xd:"=",Od:c.ga.Tf});return!b?j:["<"+a+" ",b,">",e||"","</"+a+">"].join("")},Ym:function(a){return c.some(c.sa(p),function(b,c){return c===a})},xb:function(a,b,c){function f(a){d-=a.offsetLeft-a.scrollLeft;h-=a.offsetTop-a.scrollTop}for(var d=a.clientX,h=a.clientY;b&&b!=c;)f(b),b=b.offsetParent;a=r.documentElement;!c&&a&&f(a);return{x:d,y:h}},gd:function(a){if(a){for(var b in a)c.si(a[b])&&(a[b]=q);c.g.Dd(a)}},ef:function(a,b){for(;a&&a!=b;)a=this.getParent(a);return!!a},Mq:function(a,
b){return this.getParent(a)===b},Da:function(a){return a.style.visibility!=="hidden"&&a.style.display!=="none"},Xe:function(a){return r.getElementById(a)},Fq:function(a){var b={};c.l(a,function(a,c){b[c]=this.Xe(c)},this);return b},Ye:function(a,b){for(var b=b||r.body,e=b.childNodes,d=e.length,g=0;g<d;g++){var h=e[g];if(c.ga.Rf(h.nodeName)===a)return h}},zb:function(a,b){if(a&&a.style&&b){if(c.Ra(b))return a.style[b];var e={};c.l(b,function(b,c){e[c]=a.style[c]});return e}},Nn:c.Eb(function(){var a=
r.getElementsByTagName("head");return a.length>0?a[0]:q}),Qn:function(a){var b=c.g.ii(),a=c.g.zb(a,b);return c.g.yl[b](a)},yl:{filter:function(a){if(!a)return 0;a=a.match(/[0-9\.]+/);return a.length?a[0]/100:0},opacity:c.Ad},ii:c.Eb(function(){return c.q.A.kg()?"filter":"opacity"}),getParent:function(a){return a.parentNode},qd:c.Eb(function(){return{height:"1px",width:"1px"}}),li:c.Eb(function(){return{height:"100%",width:"100%"}}),Kq:function(a){var b=c.g.getParent(a);return!c.ff(b)?j:c.filter(b.childNodes,
function(b,c){return c!=a})},Bi:function(a,b){var e=c.g.ii(),d=c.cb.bound(b,0,1);a[e]=c.g.Jl[e](d);return d},Jl:{filter:function(a){return"alpha(opacity="+a*100+")"},opacity:c.Ad},qf:function(a){return!c.q.A.Fa()?a:F[a]||a},lb:function(a,b){var e=r.createElement(a);c.g.Na(e,b);return e},Hi:function(a){a=a||o.event;a.preventDefault&&a.preventDefault()},removeChild:function(a,b){a.removeChild(b)},Xq:function(a){for(;a.hasChildNodes();)c.g.removeChild(a,a.lastChild)},Dd:function(a){var b=a.parentNode;
c.ff(b)&&c.g.removeChild(b,a)},Fd:function(a,b){a.className=c.isArray(b)?b.join(" "):b;return a},Oi:function(a,b){c.g.Na(a,{visibility:b})},Md:function(a){a=a||o.event;a.cancelBubble=!0;a.stopPropagation&&a.stopPropagation()}};c.Z={fb:{zn:function(a){a.ja=1;return this.ld(a)},An:function(a){a.ja=1;return this.We(a)},Bn:function(a){a.ja=0;return this.ld(a)},Cn:function(a){a.ja=0;return this.We(a)},We:function(a){a.Oe=function(){c.g.Oi(a.C,"hidden")};return this.ld(a)},ld:function(a){return new c.Z.vj(a)}}};
c.Z.Xo={fadeIn:c.Z.fb.zn,fadeOut:c.Z.fb.Bn,fadeTo:c.Z.fb.ld,fadeInAndHide:c.Z.fb.An,fadeOutAndHide:c.Z.fb.Cn,fadeToAndHide:c.Z.fb.We};c.Z.Rd=function(a){this.C=a.C;this.Gi=a.Pf;this.ja=a.ja;this.Db=q;this.Oe=a.Oe||c.M;this.scope=a.scope;this.hf=a.hf;this.yo=a.bi/60;this.gf=!0;this.bo="visible";this.Cb=!1;this.cc=c.H.ca(this.cc,this)};c.Z.Rd.prototype={Ue:function(a){return a&&a.ja===this.ja&&a.C===this.C},Xh:function(a){this.Pf=a;this.Qi=D.abs(this.ja-a)/this.yo},cc:function(){this.Cb=!0;if(this.Ih())return this;
if(this.hf)return this.Db=this.Pf,this.Ih(),this;this.Cb=!1;this.Oe.call(this.scope);return this},eo:function(){return this.fc()==this.ja},fc:c.M,Cd:c.M,Ih:function(){var a=this.Db;if(this.gf&&a<this.ja)this.Hd(a+this.Qi);else if(!this.gf&&a>this.ja)this.Hd(a-this.Qi);else return!1;this.bm();return!0},bm:function(){this.jm=setTimeout(this.cc,60)},stop:function(){this.Cb=!1;clearTimeout(this.jm);return this},Hd:c.M};c.Z.vj=c.o(c.Z.Rd,{Cd:function(){this.Gi&&this.Eh(this.Gi);var a=this.fc();this.Db=
a=a===""?1:Number(a);this.gf=a<=this.ja;this.bo=c.g.zb(this.C,"visibility")||"visible";c.g.Oi(this.C,"visible");this.Xh(a);return this},fc:function(){return c.g.Qn(this.C)},Hd:function(a){this.Db=this.Eh(a)},Eh:function(a){return c.g.Bi(this.C.style,a)}});c.Z.ik=c.o(c.Z.Rd,{Dh:["mozTransform","oTransform","webkitTransform","transform"],Cd:function(){var a=this.fc();this.Db=a;this.Xh(a);return this},fc:function(){return c.find(this.Dh,function(a,b){return this.Jn(b)},this)||0},Jn:function(a){a=a.match(/\([\-\w]+\)/i);
return!a||!a.length?0:a[0]},Hd:function(a){this.Db=a;var b="rotate("+a+"deg)";c.l(this.Dh,function(a,c){this.C.style[c]=b},this)}});c.Dc={gd:function(a){if(c.q.A.Pb()){a.style.display="none";var b=function(){a.readyState===4?c.g.gd(a):setTimeout(b,10)};setTimeout(b,10)}else c.g.gd(a)},hd:function(a,b,e){var a=e.url,d=e.id;c.q.A.lg()&&(a=c.ea.Ph(a));var g=this.rh(),d=this.al(d,a,g);e.style&&(d.style=c.join(e.style,"; ",{xd:":"}));var h=e.Ao||{};(e=c.ea.Nd(e.yb||{}))&&(h.flashvars=e);g&&(h.movie=a);
e=this.cl(h);e=c.g.Wh("object",d,e);b.innerHTML=e+b.innerHTML;b=c.g.Ye("object",b);c.q.A.rk()||c.g.Fd(b,"ap_never_hide");return b},al:function(a,b,e){a={id:a};e?a.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000":c.t(a,{type:"application/x-shockwave-flash",data:b});return a},cl:function(a){var b=[];c.l(a,function(a,d){b.push(c.g.Wh("param",{name:a,value:d}))});return b.join("")},fo:function(){return(this.Ln()||0)<"10"},Ln:function(){var a=this.ul();if(!a)return q;a=a.match(/[0-9.]+/);return a.length>
0?parseFloat(a[0]):q},ul:function(){var a=this.rh();return a?a.GetVariable("$version"):this.vl()},rh:function(){var a=o.ActiveXObject;if(!a)return q;try{return new a("ShockwaveFlash.ShockwaveFlash")}catch(b){return q}},vl:function(){var a=o.navigator||{},b=a["application/x-shockwave-flash"];if(!b||b.enabledPlugin)return((a.plugins||{})["Shockwave Flash"]||{}).description}};c.H={ec:function(a,b,e){return function(){c.H.Za(a,b,e,arguments)}},Za:function(a,b,c,d){d=d||[];setTimeout(function(){a.apply(c,
d)},b||0)},ca:function(a,b){return function(){return(a||c.M).apply(b,arguments)}}};c.ea={Ph:function(a){if(a!=q){var b="",e=a.indexOf("?");e===-1?b="?":e!==a.length-1&&(b="&");return a+b+"cacheBuster="+c.ea.Rm()}},Rm:function(){return D.random()*1.0E19},bn:function(a){if(o.Mp)return(new DOMParser).parseFromString(a,"text/xml");var b=new ActiveXObject("Microsoft.XMLDOM");b.async=!1;b.loadXML(a);return b.documentElement},Bq:function(a){return decodeURIComponent(a)},jd:function(a){return encodeURIComponent(a)},
getExtension:function(a){if(!a)return q;a=a.match(/\.([0-9a-z]+)(?:[\?#]|$)/i);return!a.length?q:a[1]},On:function(a){return!a?q:/(?:[^:]+:\/\/)?([^\/]+)/.exec(a)[1]},Wn:function(a){return c.q.A.Pb()&&c.q.af()<10&&a.indexOf(o.location.protocol)==0&&c.ea.On(a).indexOf(o.location.host)==-1?new XDomainRequest:new XMLHttpRequest},po:function(a){return o.XDomainRequest&&a instanceof XDomainRequest},Ei:function(a){a=c.ea.Ph(a);return(new Image).src=a},$q:function(a,b){b=b||{};b.error=b.error||c.M;b.rd=
b.rd!=q?b.rd:!0;if(XMLHttpRequest){var e=this.Wn(a),d=c.ea.po(e);e.open(b.type||"GET",a,b.rd);c.l(b.headers,e.setRequestHeader);e.withCredentials=!0;b.rd&&(e.timeout=b.cr||0);e.onload=function(){if(!d&&e.status!==200)b.error(e.statusText,e);else if(b.uc){try{var a=d?c.ea.bn(e.responseText):e.responseText}catch(h){c.H.Za(b.error,0,this);return}b.uc(e.responseXML||a,e.statusText,e)}};e.onerror=function(){b.error&&b.error(e.statusText,e)};e.ontimeout=function(){b.timeout&&b.timeout(e.readyState===4?
e.statusText:"",e)};e.send(q)}else ha.warn("XML Http Requests are not supported"),c.H.Za(b.error,0,this)},Nd:function(a){return c.join(a,"&",{xd:"=",Od:function(a){a=c.jc(a)?c.mg.jd(a):a;return c.ea.jd(a)}})}};var s=o.JSON||{};c.mg={jd:s.stringify||function(a){return a==q?j:c.isArray(a)?this.Rk(a):this.Il(a)},mn:s.parse||function(a){if(a&&!(a.indexOf("{")!==0||a.lastIndexOf("}")!==a.length-1))if(a=a.match(/[\w\"\.\s]+\:[\w\"\.\s]+/gi),a.length!==0){var b={};c.l(a,function(a,d){var g=d.match(/[\w\"\.]+/gi);
if(g.length===2){var h=c.ga.Ii(g[1],'"');b[c.ga.Ii(g[0],'"')]=h===g[1]?parseFloat(h):h}});return b}},Rk:function(a){return"["+c.join(a,",",{Od:c.H.ca(this.Kh,this)})+"]"},Il:function(a){return"{"+c.join(a,",",{xd:":",qo:c.ga.Tf,Od:c.H.ca(this.Kh,this)})+"}"},Kh:function(a){return c.jc(a)?this.jd(a):c.Ra(a)?c.ga.Tf(a):a}};c.cb={bound:function(a,b,c){return D.max(D.min(a,c),b)}};c.je={open:function(a,b){return new this.Tb(a,b,!1,!1)},closed:function(a,b){return new this.Tb(a,b,!0,!0)},zq:function(a,
b){return new this.Tb(a,b,!0,!1)},Vq:function(a,b){return new this.Tb(a,b,!1,!0)}};c.je.Tb=function(a,b,c,d){var g=a<=b;this.uo=g?a:b;this.dp=g?b:a;this.jo=c;this.no=d};c.je.Tb.prototype={contains:function(a){return this.io(a)&&this.mo(a)},io:function(a){var b=this.uo,c=this.jo;return c&&a>=b||!c&&a>b},mo:function(a){var b=this.dp,c=this.no;return c&&a<=b||!c&&a<b}};c.Ng={Dn:function(a,b){var b=b||{},e=b.uc||c.M,d=b.error||c.M,g=c.g.lb("script"),h=!1;g.async=!0;g.src=a;c.g.bind(g,"load readystatechange",
function(a){h||(h=!0,e(a))});c.g.bind(g,"error",function(a){c.g.Dd(g);d(a)});c.g.ib(g,c.g.Nn())},Eq:function(a,b){var b=b||{},e=a.length,d=0,g=b.uc||c.M,h={uc:function(a){++d==e&&success&&g(a)},error:b.error||c.M};c.l(a,function(a,b){c.Ng.Jq(b,h)})}};c.ga={Um:function(a){return!a?"":c.ga.Rf(a.replace(/([a-z])([A-Z])/g,"$1-$2"))},contains:function(a,b){return a.indexOf(b)!==-1},ti:function(a){return!!a&&c.Ra(a)&&a.indexOf("%")===a.length-1},Rq:function(a){return c.ga.Rf(a.charAt(0))+a.slice(1)},Eo:function(a,
b,c){for(;a.length<c;)a=b+a;return a},Ii:function(a,b){return!a?a:a.indexOf(b)!==0||a.lastIndexOf(b)!==a.length-1?a:a.substr(1,a.length-2)},Rf:function(a){return a.toLowerCase()},ap:function(a){return a.toUpperCase()},Tf:function(a){return'"'+a+'"'}};c.Qc={Aq:function(a){a=c.Qc.im[a]||a;return c.ga.ti(a)||c.ud(a)?a:c.Qc.an(a)},im:{start:"0%",end:"100%"},an:function(a){if(a){for(var a=a.split(":"),b=0,c=1,d=a.length-1;d>=0;d--,c*=60)b+=parseFloat(a[d],10)*c;return b}},Ki:function(a,b,e){if(!(a<0)){var d=
D.floor(a/3600);a%=3600;var g=D.floor(a/60),h=D.round(a%60),a=c.ga.Eo;if(e||b||d)g=a(String(g),"0",2);h=a(String(h),"0",2);g=g+":"+h;if(d!=0||b)e&&(d=a(String(d),"0",2)),g=d+":"+g;return g}}};c.Wg={l:function(a,b,c){for(var d=0;d<a.length;d++){var g=a.item(d);b.call(c,g.nodeName,g)}},Gq:function(a){var b={};c.Wg.l(a.attributes,function(a,c){b[a]=c.nodeValue},this);return b},Iq:function(a){if(a.childNodes&&a.childNodes.length)return c.Wg.Ho(a.childNodes[0].nodeValue)},Ho:function(a){if(!a)return a;
var b=a.match(/<!\[CDATA\[(.*?)\]\]>/);return!b||!b.length?a:b[1]}};y.wi=function(a){a=a||{};return{adInstance:a.sm,adPod:a.Nh,adPods:a.tm,adsResponse:a.Fm,contentId:a.Ya,contentTitle:a.Ba,controlId:a.s,creative:a.kn,durationSeconds:a.$,errorCode:a.yn,eventScopes:a.j,eventTimestamp:a.h,metricDurationMillis:a.of,metricEventNameSuffix:a.Fb,parentEl:a.sf,playheadTimeSeconds:a.Q,renderer:a.ha,resource:a.Bf,resourceType:a.Cf,startTimeSeconds:a.Of,targetVolume:a.aa,targetSeconds:a.ab,videoHeight:a.videoHeight,
videoLoadedPercent:a.ob,videoQuality:a.ta,videoSourceInfo:a.R,videoWidth:a.videoWidth,volume:a.volume}};y.vo=function(a){a=a||{};return{sm:a.adInstance,Nh:a.adPod,tm:a.adPods,Fm:a.adsResponse,Ya:a.contentId,Ba:a.contentTitle,s:a.controlId,kn:a.creative,$:a.durationSeconds,yn:a.errorCode,j:a.eventScopes,h:a.eventTimestamp,of:a.metricDurationMillis,Fb:a.metricEventNameSuffix,sf:a.parentEl,Q:a.playheadTimeSeconds,ha:a.renderer,Bf:a.resource,Cf:a.resourceType,Of:a.startTimeSeconds,aa:a.targetVolume,ab:a.targetSeconds,
videoHeight:a.videoHeight,ob:a.videoLoadedPercent,ta:a.videoQuality,R:a.videoSourceInfo,videoWidth:a.videoWidth,volume:a.volume}};y.prototype={Vh:function(a,b,e){var d=A.call(arguments);d[1]=c.Qd(b,this.Mk,e);d[1]=c.H.ec(d[1],0);this.bind.apply(this,d);return this},Mk:function(a,b,c){return a.call(this,b,y.wi(c))},bind:function(a,b,e){if(!a||!b)return this;var d=arguments;c.l(c.Sa(a),function(a,b){d[0]=b;this.Yb.apply(this,d)},this);return this},Yb:function(a,b,e){c.Sh(this.Wc,a,{type:a,W:b,xq:c.H.ec(b,
0,e||this),scope:e||this});return this},Bb:function(a,b){if(!a||!b)return!1;var e=this.Wc[a];if(!e)return!1;var d=!1;c.l(e,function(a,c){d=d||c.W===b});return d},Si:function(a,b){if(!a||!b)return this;var c=this.Wc[a];if(!c)return this;for(var d=0,g=c.length;d<g;d++)if(c[d].W===b){c.splice(d,1);break}return this},v:function(a,b){if(!a)return this;c.l(c.Sa(a),function(a,c){this.He(c,b)},this);return this},He:function(a,b){c.l(this.Wc[a],function(a,c){c.W.call(c.scope,c,b)});return this}};var la=c.o(y,
{constructor:function(a){this.Vc={};c.l(c.unshift(a,i.Lb),function(a,c){this.Vc[c]||(this.Vc[c]=new y)},this)},Yb:function(a,b,c,d){this.ze(this["super"].Yb,d,a,b,c);return this},Bb:function(a,b,c){return this.ze(this["super"].Bb,c,a,b)},Si:function(a,b,c){this.ze(this["super"].Si,c,a,b);return this},ze:function(a,b){var c=A.call(arguments,2),d=q;this.jh(b,function(b){d==q&&(d=!0);d=a.apply(b,c)&&d});return!!d},He:function(a,b){this.jh(b.j,function(c){c.He(a,b)});return this},jh:function(a,b){c.l(this.Bl(a),
function(a,c){b.call(this,this.Vc[c])},this)},Bl:function(a){return c.filter(c.Sa(a||i.Lb),this.El,this)},El:function(a,b){return!!this.Vc[b]}});Y.prototype={add:function(a,b,e,d,g){var h=this.Rl;h[e]||(h[e]=b,h=c.Ab(),b=this.wh[h]={$h:{},Te:0,W:b,type:e,scope:d||this},this.Zg(e,g),this.Yg(b,h,c.Sa(a)),b.Te===0&&this.nh(b))},xm:function(a,b){b.length&&this.oh(a,function(a,c){this.Yg(a,c,b)},this)},Yg:function(a,b,e){c.l(e,function(e,d){if(c.jc(d))var h=d.ei,k=d.j;else h=d,k=i.Lb;h&&!a.$h[h]&&(a.$h[h]=
!0,this.th[h]||(this.Zg(h,k),this.wl(h).push(b),++a.Te))},this)},wl:function(a){var b=this.mh;return b[a]||(b[a]=[])},oh:function(a,b,e){(a=this.mh[a])&&c.l(a,function(a,c){var d=this.wh[c];d!=q&&b.call(e,d,c)},this)},Zg:function(a,b){var c=this.Uc;c.Bb(a,this.lh)||c.bind(a,this.lh,this,b)},lh:function(a,b){var c=a.type;this.th[c]=!0;this.oh(c,function(a){--a.Te===0&&this.nh(a,b)},this)},nh:function(a,b){var e=a.W.call(a.scope||this,a,b);this.Uc.v(a.type,{h:c.m(),result:e})}};X.prototype={$m:function(a){c.l(this.Hh,
function(b,e){a.add(e.oc,e.W,b,q,e.dd);e.yf&&a.xm(b,c.Sa(e.yf))})},nc:function(a){if(a.name==q||!a.W)return this;this.Hh[a.name]={W:c.H.ca(a.W,a.scope||this.hh),oc:a.oc||d.G.Wd,yf:a.yf,dd:(this.sh||[]).concat(a.dd||[])};return this},Mo:function(a){this.hh=a;this.sh=A.call(arguments,1);return this},Zm:function(){this.sh=this.hh=q;return this}};L.prototype={I:c.M,z:w(),X:w(),j:q,rc:function(a){this.j=a;return this},bind:function(){this.va(this.z,this.j);this.va(this.X);this.ba(this.f);return this},
ba:c.M,va:function(a,b){this.sc(a,function(a,c){a!=q&&c&&this.f.w.bind(a,c,this,b)})},sc:function(a,b,e,d){d=d||{};a.call(this,d,this);c.l(d,b,e||this)},r:function(a,b){b.j=b.j||this.j;this.f.w.v(a,b);return this}};var M={Yj:"percent",zg:"position"},ma=c.o(L,{I:function(){this.reset()},z:function(a){a[d.u.Xa]=this.$o},Th:function(a){var b=c.Qd(a.callback,this.Tm,a.scope);this.add({type:a.type,sa:a.values,lf:a.isSkipBackEnabled,W:b})},Tm:function(a,b,c,d){return a.call(this,b,c,y.wi(d))},add:function(a){var b=
a.sa,e=a.W;if(e&&b!=q){var d=a.type;c.l(c.Sa(b),function(b,h){this.ue.push({type:d||(c.ga.ti(h)?M.Yj:M.zg),value:h,zo:parseFloat(h,10),lf:a.lf,W:e,scope:a.scope})},this)}},$o:function(a,b){if(this.ue.length){var e=b.$,d=b.Q/e*100;if(this.Zc!==d)e=this.ql(c.je.closed(this.Zc,d),e,this.Zc>d),c.l(e,function(a,c){this.ol(c,b)},this),this.Zc=d}},ql:function(a,b,e){return c.filter(this.ue,function(c,d){if(d.lf||!e){var h=d.zo;d.type===M.zg&&(h=h/b*100);return a.contains(h)}})},ol:function(a,b){a.W.call(a.scope,
a.value,a.type,b)},reset:function(){this.Zc=-1;this.ue=[]}}),s=c.o(L,{Ff:w(),bind:function(){this.sc(this.Ff,this.Rh,this,[]);this.va(this.z,this.j);this.va(this.X);this.ba(this.f);return this},Rh:function(a,b){b.scope=this;this.f.Zh.add(b)}}),na=c.o(s,{j:i.k,I:function(){this.co=this.f;this.jf=!1;this.wf=[]},z:function(a){a[d.G.sb]=this.Io},X:function(a){a[d.b.Ac]=this.detach},Io:function(){for(this.jf=!0;this.wf.length;){var a=this.wf.shift();a.method.apply(a.scope,a.dd)}},detach:function(){this.jf=
!1},Le:function(){var a=this.Gm;return c.map(a,function(b,e){return c.Qd(e,this.hp,this,a,b,this.co)},this)},hp:function(a,b,c,f){var g=A.call(arguments,3);if(this.jf||c===d.b.Gb)return a.apply(b,g);this.wf.push({method:a,scope:b,dd:g})},Gm:{addCuePoint:function(a,b){a.Zh.Th(b)},attach:function(a,b,e){a.w.v(d.b.Gb,c.t({h:c.m(),sf:c.Ra(b)?c.g.Xe(b):b},e))},audioOff:function(a,b){a.w.v(d.b.da,c.t({j:i.k,h:c.m(),aa:0,volume:a.p.volume},b))},audioOn:function(a,b){a.w.v(d.b.da,c.t({j:i.k,h:c.m(),aa:a.p.tf||
1,volume:a.p.volume},b))},bind:function(a,b,c,d){a.w.Vh(b,c,d,[i.Lb,i.k])},detach:function(a,b){a.w.v(d.b.Ac,c.t({h:c.m()},b))},enterFullScreen:function(a,b){a.w.v(d.b.Aa,c.t({j:i.k,h:c.m()},b))},enterNormalScreen:function(a,b){a.w.v(d.b.na,c.t({j:i.k,h:c.m()},b))},getDurationSeconds:function(a){return a.p.$},getPlayheadTimeSeconds:function(a){return a.p.Q},getVideoLoadedPercent:function(a){return a.p.ob},getVolume:function(a){return a.p.volume},hide:function(a,b){a.w.v(d.b.Ec,c.t({h:c.m()},b))},
isAudioOn:function(a){return a.p.sd},isPlaying:function(a){return a.p.qa},isFullScreen:function(a){return a.p.$a()},loadVideo:function(a,b,e,f,g){a.w.v(d.b.N,c.t({Ya:f,Ba:e,j:i.k,h:c.m(),R:b},g))},pause:function(a,b){a.w.v(d.b.F,c.t({j:i.k,h:c.m()},b))},play:function(a,b){a.w.v(a.p.Qa?d.b.Ja:d.b.B,c.t({j:i.k,h:c.m()},b))},prefetch:function(a,b,e){a.w.v(d.b.ge,c.t({j:i.k,h:c.m(),R:b},e))},replay:function(a,b){a.w.v(d.b.fa,c.t({j:i.k,h:c.m()},b))},seek:function(a,b,e){var f=a.p;a.w.v(d.b.Ha,c.t({$:f.$,
j:i.k,h:c.m(),Q:f.Q,ab:b},e))},show:function(a,b){a.w.v(d.b.le,c.t({h:c.m()},b))},setDisplayAdsMetricEventNameSuffix:function(a,b,e){a.w.v(d.b.Wf,c.t({j:i.k,h:c.m(),Fb:b},e))},setVideoQuality:function(a,b,e){a.w.v(d.b.Va,c.t({j:i.k,h:c.m(),ta:b},e))},setVolume:function(a,b,e){a.w.v(d.b.da,c.t({j:i.k,h:c.m(),aa:b,volume:a.p.volume},e))}}});W.prototype={select:function(a){var b=a[this.fd];return b?this.Yh(this.fd,b):this.Lo(a)},Lo:function(a){var b=c.md(c.keys(a));return!b?j:this.Yh(b,a[b])},Yh:function(a,
b){return{Sf:b,ta:a}}};var $=c.o(s,{I:function(a){this.nm=a},z:function(a){a[d.b.fg]=this.cf;a[d.b.Ig]=this.Ld;a[d.u.Ea]=this.dc;a[d.b.Va]=this.Ti;a[d.b.N]=this.V},X:function(a){a[d.b.pb]=this.Me;a[d.b.Gb]=this.ha.Ri},cf:function(){c.g.Na(this.D,c.g.qd())},Ld:function(){this.f.w.v(d.b.pb,{h:c.m(),ha:this.ha});c.g.Na(this.D,c.g.li())},Me:function(a,b){this.ha.qi=b.ha===this.ha},dc:function(){this.f.p.Ie===this.ha&&this.Ld()},Ti:function(a,b){var c=this.f.p,d=c.qa;this.V(a,{j:this.j,R:c.R[b.ta],Of:c.Q});
d&&this.play()},V:function(a,b){this.cf();var e=b.R;this.No(c.vd(e)?this.Xn(e):e,b.Of||-1)},Xn:function(a){var b=c.m(),a=this.f.zi.select(a);c.H.Za(this.r,0,this,[d.b.Va,{h:b,ta:a.ta}]);return a.Sf},No:function(a,b){var e=c.Ra(a)?a:this.Vn(a);e&&this.Jf(this.pl(e),b)},pl:function(a){return c.Ra(a)?a:a.url},Vn:function(a){return this.nm.select(a)},Jf:c.M}),oa=c.o(s,{j:[i.O,i.k],X:function(a){a[d.b.Gb]=this.Ke;a[d.b.Ac]=this.detach},Ke:function(a,b){c.g.ib(this.f.xa,b.sf)},detach:function(){c.g.getParent(this.f.xa)&&
(this.r([d.b.F,d.b.na],{h:c.m()}),c.H.Za(c.g.Dd,0,c.g,[this.f.xa]))}}),pa=c.o(s,{I:function(){c.t(this,{Ie:j,Ya:q,Ba:q,$:0,sd:!0,Qa:!0,$a:!1,kc:!1,qa:!1,mf:!1,vi:!1,kf:!1,tf:1,Q:0,ob:0,volume:1})},z:function(a){var b=d.u,c=d.b;a[c.Ec]=this.Xc;a[c.vg]=this.Pl;a[c.le]=this.dm;a[c.wg]=this.Ql;a[c.N]=this.Hl;a[b.Ea]=this.Nk;a[c.Va]=this.Ok;a[b.Ud]=this.Fe;a[b.Xa]=this.Fe;a[b.Ic]=this.Fe;a[c.Ha]=this.Wl;a[c.Ia]=this.Xl;a[c.da]=this.Pk;a[b.za]=this.Ce;a[c.F]=this.Ce;a[c.B]=this.zh;a[c.fa]=this.zh},X:function(a){a[d.b.pb]=
this.qe;a[d.b.Kc]=this.Vl;a[d.b.jj]=this.Ce},qe:function(a,b){this.Ie=b.ha},Xc:function(){this.mf=!0},Pl:function(){this.mf=!1},dm:function(){this.vi=!0},Ql:function(){this.vi=!1},Hl:function(a,b){this.Ya=b.Ya;this.R=b.R;this.Ba=b.Ba;this.kc=!1;this.Qa=!0;this.qa=!1},Nk:function(){this.kc=!0},Ok:function(a,b){this.ta=b.ta},Fe:function(a,b){this.Q=b.Q;this.$=b.$;this.ob=b.ob},Wl:function(){this.kf=!0},Xl:function(a,b){this.kf=!1;this.Q=b.Q},Pk:function(a,b){this.tf=this.volume;this.volume=b.aa;this.sd=
!!b.aa},zh:function(){this.qa=!0;this.Qa=!1},Ce:function(){this.qa=!1},Vl:function(){this.$a=!this.$a}}),qa=c.o(s,{z:function(a){a[d.b.ge]=this.Co},Co:function(a,b){var e=b.R,e=c.vd(e)?this.f.zi.select(e).Sf:e,e=this.f.mode===x.bb?l.Hq(e):t.Lq(e);(new Image).src=e}});K.prototype={type:q,I:c.M,j:q,D:q,qi:!1,Nm:function(a,b){var e=this;c.g.bind(this.D,a,function(){e.ra(b)})},Ri:function(){var a=this.f.w;c.H.Za(a.v,0,a,[d.G.sb,{j:this.j,h:c.m()}])},ra:function(a,b){this.f.w.v(a,c.t({j:this.j,h:c.m(),
$:this.gi(),Q:this.ki(),ob:this.mi()},b))},gi:c.M,ki:c.M,mi:c.M};var ra=c.o(s,{I:function(){var a=c.q.A;this.Qq=a.Mg()&&a.Bk()},X:function(a){a[d.b.Ec]=this.Zn;a[d.b.le]=this.So;a[d.b.pb]=this.Me;a[d.b.Kc]=this.Df},Me:function(a,b){this.j=b.ha.j},Zn:function(){var a={h:c.m()},b=this.f.p;b.qa&&this.r(d.b.F,a);b.$a?this.r(d.b.na,a):this.Xc()},Df:function(){this.f.p.mf&&this.Xc()},Xc:function(){c.g.Na(this.f.xa,c.g.qd());this.r(d.b.vg,{h:c.m()})},So:function(){c.g.Na(this.f.xa,c.g.li());this.r(d.b.wg,
{h:c.m()})}}),J=c.M;J.prototype={pd:function(a){return!a?j:c.Ra(a)?ka[c.ea.getExtension(a)]:a.mimeType},ic:c.M,select:j};U.prototype={create:w()};var v=c.o(s,{s:q,er:q,Li:function(){return{}},Id:function(){return{}},hi:function(){return(this.n()||{}).C},n:function(){return this.f.S.n(this.s)},Sn:function(){var a=this.n();return c.filter(this.f.S.hb,function(b,c){return!c?j:c.Ta===a.Ta&&b!==a.id})},bind:function(){if(!this.hi())return this;if(this.Ca(this.f))return this.f.S.remove(this.s),this;this.va(this.z,
this.j);this.va(this.X);this.sc(this.Ff,this.Rh,this,[]);this.sc(this.Li,this.Mm);this.sc(this.Id,this.Om);this.ba(this.f);return this},Ca:function(){return!1},Mm:function(a,b){this.Uh(this.f.xa,a,b)},Om:function(a,b){this.Uh(this.hi(),a,b)},Uh:function(a,b,e){e=c.H.ca(e,this);c.g.bind(a,c.g.qf(b),e,this.dr)},xb:function(a,b){return c.g.xb(c.md(a.touches)||a,b,this.f.p.$a?this.f.xa:q)}}),C=c.o(v,{Id:function(a){a[p.ya]=this.click},click:c.M}),aa=c.o(v,{Id:function(a){a[p.Td]=this.Ll},Li:function(a){a[p.ce]=
this.Nl;a[p.Sg]=this.Ol;a[p.qb]=this.Ml},mc:c.M,wo:c.M,rf:c.M,zd:c.M,hc:!1,Ll:function(a){c.g.Md(a);c.g.Hi(a);this.hc=!0;this.mc(a)},Nl:function(a){if(!c.g.ef(a.relatedTarget||a.toElement,this.f.xa))this.hc=!1,this.wo(a)},Ol:function(a){if(this.hc)c.g.Md(a),this.hc=!1,this.rf(a)},Ml:function(a){this.hc&&this.zd(a)}});c.t(H,{Kn:function(a){return a.ci},Pn:function(a){return a.vb.yd},Rn:function(a){return a.vb.Bd}});T.prototype={we:function(a,b){var e=c.map(this.cd,function(e,d){return c.map(a.call(this,
d),b,this)},this);return c.t.apply(c,c.sa(e))},bl:function(a){var b=this;return function(){var e=b.od().ci[a];e&&(c.g.Fd(b.C,e.Qe),c.g.Na(b.C,e.style))}},gh:function(a){return(new S(this,a)).Le()},bind:function(a,b,e){var d=this;c.g.bind(this.C,a,function(){d.isEnabled&&b.apply(this,arguments)},e||!1);return this},remove:function(){c.g.Dd(this.C);return this},tc:function(a){this.C.innerHTML=a;return this},bc:function(a){return this.Xg(this.od(),a)},od:function(){return this.cd[this.Re]},Qh:function(a){c.l(this.cd,
function(b,c){this.Xg(c,a)},this);return this},Xg:function(a,b){c.t(a.style,b);c.g.Na(this.C,b);this.Jh();return this},Y:function(a){if(this.isEnabled&&this.Re!==a&&this.cd[a])return this.Re=a,this.refresh()},refresh:function(){var a=this.od();c.g.Fd(this.C,a.Qe);c.g.Na(this.C,a.style);this.Jh();return this},Jh:function(){this.Da=c.g.Da(this.C)},show:function(a,b){this.Gh(b,"block","visible",a);this.Da=!0;this.wn();return this},U:function(a,b){this.Gh(b,"none","hidden",a);this.Da=!1;this.ai();return this},
Gh:function(a,b,c,d){var g={};a?this.Ck(g,b):this.Ek(g,c);this.Dk(g,d);this.Qh(g)},Ek:function(a,b){a.visibility=b},Ck:function(a,b){a.display=b},Dk:function(a,b){b!=q&&c.g.Bi(a,b)},wn:function(){this.df=!0;return this},ai:function(){this.df=!1;return this},Sm:function(){var a=this.C,b=c.map(this.$n,function(b,d){return parseFloat(c.g.zb(a,d))||0});return c.Zo(b)},$n:["width","marginLeft","marginRight","paddingLeft","paddingRight"]};var sa=c.o(s,{j:i.k,mm:c.q.A.Zd()||c.q.A.Ib()||c.q.A.Dj(),z:function(a){a[d.b.Ja]=
this.Qo;a[d.b.lk]=this.Kd},X:function(a){a[d.O.Ag]=this.Fi;a[d.O.Uj]=this.Kd;a[d.O.Ui.Vd]=this.Kd;a[d.O.qk]=this.Kd},Qo:function(a,b){this.f.wa.Pd.td&&!this.mm?(this.Fi(a,b),this.f.w.v(d.O.hk,{h:b.h})):this.r(d.b.B,b)},Fi:function(a,b){this.f.S.U(k.eb).U(k.fe).U(k.Wa,q,!0);this.r(d.b.fg,b)},Kd:function(a,b){var e=c.m(),f=b.Nh||{},g=this.f.p;g.qa||f.yq===Z.rg||(c.q.A.Fa()&&this.r(d.b.N,{h:e,R:g.R}),this.f.S.show(k.eb).show(k.fe).show(k.Wa,0,!0),this.r([d.b.Ig,d.b.B],{h:e}))}}),G=o.Airy=G||{};G.VERSION=
"2.0";var ba={},ca=new y;G.addResource=function(a,b){(ba[a]||(ba[a]=[])).push(b);ca.v(d.G.Dg,{h:c.m(),Cf:a,Bf:b})};var t={};t.Xb=c.o(J,{constructor:function(a){a&&c.t(this,c.ga.contains(a,"AiryHlsRenderer.swf")?new t.wj:new t.Vf)}});t.Vf=c.o(J,{hm:[m.ma,m.bg],uf:m.ma,select:function(a){if(c.Ra(a))return a;a=c.filter(a,this.oo,this);return c.find(a,this.Gl,this)||c.md(a)},Gl:function(a,b){return this.pd(b)===this.uf},oo:function(a,b){return this.ic(this.pd(b))},ic:function(a){return a===this.uf||c.some(this.hm,
function(b,c){return a===c})}});t.wj=c.o(t.Vf,{uf:m.pg});G.flashEventCallbacks={};t.ag=function(a){this.Uc=a;this.vh=c.Ab();this.$g=G.flashEventCallbacks[this.vh]={}};t.ag.prototype={dn:function(a){var b=this.gn(a);if(this.$g[a])return b;this.$g[a]=this.Zk(a);return b},Zk:function(){var a=this.Uc;return function(b,e){var d=c.mg.mn(e),d=y.vo(d);a.v(b,d)}},gn:function(a){return"Airy.flashEventCallbacks['"+this.vh+"']['"+a+"']"}};t.ke=c.o(K,{type:z.sj,I:function(a){var b=this.nd=c.t({},this.on,this.nd),
e=this.yb=c.t({},this.pn,this.yb);e.bindings=this.Yk(a);var f=this.id=this.id||c.Ab();(this.D=c.g.Ye("object",a.Ed))?c.H.Za(this.te,0,this):(a.w.bind(d.G.Lg,this.te,this),c.g.bind(o,"unload",function(){a.w.v(d.b.jj,{h:c.m()})}),this.il=[c.H.ec(this.te,0,this),a.Ed,{url:this.vc,id:f,yb:e,Ao:b,style:c.t({position:"absolute",top:"0px",left:"0px",overflow:"hidden"},c.g.qd())}],this.hd())},hd:function(){return this.D=c.Dc.hd.apply(c.Dc,this.il)},on:{allowscriptaccess:"always",quality:"autohigh",wmode:"opaque"},
pn:{hostname:o.location.hostname},Yk:function(a){function b(a,b){f[b]=e.dn(b)}var e=new t.ag(a.w),f={};c.l(d.u,b);c.l(d.L,b);c.l([d.G.Lg,d.G.sb,d.b.tg,d.b.xg,d.b.Ia],b);return f},te:function(){this.D._createScopedWrapper(this.j)}});t.Jc=c.o($,{I:function(){this["super"].I(new t.Xb(this.f.wa.vc))},z:function(a){this["super"].z.call(this,a);var b=d.b;a[b.F]=this.pause;a[b.B]=this.play;a[b.fa]=this.mb;a[b.Ha]=this.seek;a[b.Va]=this.Ti;a[b.N]=this.V;a[b.da]=this.Kf},X:function(a){a[d.b.Gb]=this.Ke;a[d.b.Ac]=
this.detach},Ke:function(){this.D=this.ha.hd()},detach:function(){this.D._cleanUp(this.j);c.Dc.gd(this.D);this.D=q},cf:function(){this.D._hide(this.j)},Ld:function(){this.D._show(this.j);this["super"].Ld.call(this)},pause:function(){this.D._pause(this.j)},play:function(){this.D._play(this.j)},mb:function(){this.D._replay(this.j)},seek:function(a,b){this.D._seek(this.j,b.ab)},Jf:function(a,b){this.D._setVideoUrl(this.j,a,b)},Kf:function(a,b){this.D._setVolume(this.j,c.cb.bound(b.aa,0,1))}});var l=
{T:{}};l.Xb=c.o(J,{constructor:function(a){this.Lh=a||c.g.lb("video")},Jk:{Chrome:m.Vg,MSIE:m.ma,Safari:m.ma,Firefox:m.be},select:function(a){if(c.Ra(a))return a;var a=this.xl(a),b=this.Jk[c.q.ji()];if(b=a[b])return b;b=c.md(c.keys(a));return a[b]},xl:function(a){var b={};c.l(a,function(a,c){var d=this.pd(c);this.ic(d)&&(b[d]=c)},this);return b},ic:function(a){return this.Lh.canPlayType?this.Lh.canPlayType(a):!1}});l.Ug=function(){this.hb={}};l.Ug.prototype={um:function(a){var b=[];c.l(this.hb,function(a,
d){if(d){var g=d.C,h=this.bf(d.Ta);c.ff(h)?c.g.ib(g,h):d.Ta||b.push(g)}},this);c.l(b,function(b,d){c.g.ib(d,a)})},Lm:function(){c.l(this.hb,function(a,b){b&&(c.l(c.nf(b.di,c.g.qf),b.bind,b),c.l(b.Ve,function(a,d){var g=this.n(d);g&&c.l(b.di,g.bind,g)},this))},this);return this},Fo:function(a){c.l(a,function(a,c){c&&(this.hb[a]=c)},this);return this},bind:function(a,b,c,d){a=this.n(a);if(!a)return this;a.bind(b,c,d);return this},remove:function(a){var b=this.n(a);this.hb[a]=q;if(!b)return this;b.remove();
return this},bf:function(a){if(a=this.n(a))return a.C},n:function(a){if(this.hb)return a=this.hb[a],!a?j:a},Y:function(a,b){var c=this.n(a);if(!c)return this;c.Y(b);return this},show:function(a,b,c){a=this.n(a);if(!a)return this;a.show(b,c);return this},U:function(a,b,c){a=this.n(a);if(!a)return this;a.U(b,c);return this}};var ta=c.o(s,{view:q,Oo:function(a){this.view=a;return this},z:function(a){c.t(a,c.map(this.view.vb.Bd,this.Wk,this));return this},Wk:function(a,b){return this.se(b,b.Nf)},bind:function(){if(!this.view)return this;
this.va(this.z,c.sa(i));var a=c.nf(this.view.vb.yd,c.g.qf);c.l(a,this.Gk,this);return this},Gk:function(a,b){c.l(this.Al(b.Un()),function(c,d){this.Hk(a,b,d)},this)},Al:function(a){a=c.map(a,this.tl,this);a=c.compact(a)||[];if(a.length)return a;a.push(this.f.xa);return a},tl:function(a,b){return this.f.S.bf(b)},Hk:function(a,b,d){c.g.bind(d,a,this.se(b,b.Wo,d));b.Yn()&&c.g.bind(d,p.qb,this.se(b,b.Vm,d))},se:function(a,b,d){var f=this.view;return c.H.ec(function(g){f.df&&b.call(a,c.Lf(g),d)},0,this)}}),
da=c.o(v,{Gd:function(a,b,d){var f=b.inactivity||{},d=d||{};d.Yo=d.Yo||c.M;c.t(this,{hl:a,km:c.Sa(b.triggerIds),ye:!!b.type,Zb:!!f.type,Fk:b.delay||0,Dl:f.delay||0,Cl:f.exception,wq:!1,De:0,Rc:d,fl:b.disablingPlayerEvents,kl:b.enablingPlayerEvents,ac:!0});this.Sc=this.eh(a,b);this.$b=this.eh(a,f);return this},Un:function(a){this.gl=a;return this.km},Yn:function(a){this.gl=a;return this.Zb},bind:function(){this.va(this.$l,c.sa(i));this.va(this.am,c.sa(i));return this},$l:function(a){this.dh(a,this.fm,
this.fl)},am:function(a){this.dh(a,this.jl,this.kl)},dh:function(a,b,d){var f=c.H.ca(b,this);c.l(d,function(b,c){a[c]=f},this)},fm:function(){this.ac=!1;this.ye&&(this.Sc.stop(),this.Zb&&this.$b.stop())},jl:function(){this.ac=!0},eh:function(a,b){var d=c.Z.Xo[b.type];return!d?j:d.call(c.Z.fb,{C:a,bi:b.duration||0,Pf:b.startValue,ja:b.targetValue})},Wo:function(a,b){this.ac&&this.ye&&this.Fh(a,b)&&this.Nf()},Nf:function(){var a=this.Rc,b=a.Mh,d=this.Sc,f=this.$b;if((d.eo()||d.Cb)&&this.Zb&&a.gc&&f.Ue(b))this.De=
c.m();else{if(b&&(b.Cb||a.gc))b.stop(),clearTimeout(a.Se);this.$c(this.Sc,this.Fk,function(){if(this.Zb)this.Pi?this.Pi=!1:(this.De=c.m(),this.$c(this.$b,this.Dl,q,this.cm))})}},$c:function(a,b,d,f){var g=arguments,h=this.Rc,i=this;c.t(h,{gc:!0,Mh:a,Se:setTimeout(function(){if(i.ac){if(!f||f.apply(i,g))a.Cd().cc(),h.gc=!1,d&&d.call(i)}else h.gc=!1},b)})},cm:function(a,b,d,f){b=this.De+b-c.m();if(b<=0)return!0;clearTimeout(this.Rc.Se);this.$c(a,b,d,f);return!1},Vm:function(a){if(this.ac&&this.ye&&
this.Zb){var b=this.Rc,c=this.Sc,d=b.Mh;this.Cl&&this.Fh(a,this.hl)?c.Ue(d)&&b.gc?this.Pi=!0:this.$b.Ue(d)&&(this.$b.stop(),clearTimeout(b.Se),this.$c(c,0)):this.Nf()}},Fh:function(a,b){var d=a.relatedTarget;switch(a.type){case p.qb:case p.ya:return d=a.target||a.srcElement,c.g.ef(d,b);case p.ce:d=d||a.toElement;break;case p.sg:d=d||a.fromElement}return!c.g.ef(d,b)}});S.prototype={Le:function(){return c.map(da.prototype,function(a,b){return!c.si(b)?b:c.Qd(b,this.rm,this)},this)},rm:function(a){var b=
this.sl();return!b?j:a.apply(b,A.call(arguments,1))},sl:function(){var a=this.om.od().vb;if(a)return a=this.Fl?a.yd:a.Bd,(a||{})[this.nl]}};R.prototype={parse:function(a,b,d,f,g,h){var d=this.Bh(c.t({},d,a.style)),b=this.bh(a,b),i=this.Xk(a.mouseEvents,b,d),a=c.map(this.Tk(a.animations||{},g||{}),this.Sk(f,h),this);return new H(b,d,i,a)},Tk:function(a,b){return{yd:this.ah(a,b,"mouseEvents"),Bd:this.ah(a,b,"playerEvents")}},ah:function(a,b,d){return c.t({},b[d]||{},a[d]||{})},Sk:function(a,b){return function(d,
f){return c.map(f,this.Uk(a,b),this)}},Uk:function(a,b){return function(c,d){return(new da(this.re)).Gd(a,d,b).bind()}},Xk:function(a,b,d){return c.map(a,function(a,g){var h=g.style;return this.Bh({Qe:this.bh(g,b).join(" "),style:h?c.t({},d,h):{}})},this)},bh:function(a,b){return c.g.Oh(a.classNames||b,a.addClassNames,a.removeClassNames)},Bh:function(a){if(c.q.A.kg())return a;a.filter=j;return a}};Q.prototype={parse:function(a,b,d){var f=c.g.lb("div"),d=c.t({},d,a.style),b=a.classNames||b||[],b=c.Lf(b);
b.push(c.ga.Um(a.id));b=c.g.Oh(b,a.addClassNames,a.removeClassNames);b=this.el(a.states||{view:{}},b,d,f,a.animations);return new T({C:f,id:a.id,Ta:a.parentId,Ve:a.eventLinkedViewIds||[],qn:a.defaultStateId||"view",fp:b})},el:function(a,b,d,f,g){if(a){var h={};return c.map(a,function(a,c){return this.gm.parse(c,b,d,f,g,h)},this)}}};P.prototype={parse:function(a){var b={};c.l(a.views,function(c,d){var g=this.pm.parse(d,a.classNames,a.style).refresh();b[g.id]=g},this);return b}};l.T.up=c.o(v,{s:k.Xi,
j:i.k,Ca:function(){return c.q.A.Fa()},X:function(a){a[d.O.Lc]=this.nb;a[d.O.Nb]=this.Pa},nb:function(){this.n().U()},Pa:function(){this.n().show()}});l.T.vp=c.o(v,{s:k.Yi,Ca:function(){return c.q.A.Fa()}});l.T.wp=c.o(aa,{s:k.Zi,j:i.k,I:function(){this.qc=this.f.S.n(k.$i)},z:function(a){a[d.b.da]=this.wb},ba:function(){this.wb(q,{aa:this.f.p.volume})},wb:function(a,b){var d=this.n(),f=this.f.S.bf(d.Ta),d=parseInt(c.g.zb(d.C,"height"));(f=parseInt(c.g.zb(f,"height")))&&this.Em(b.aa*(1-d/f)*100+"%")},
Em:function(a){this.n().bc({bottom:a});this.qc&&this.qc.bc({height:a})},mc:function(){this.f.w.v(d.b.oa,{s:this.s,h:c.m()})},zd:function(a){var b=c.m(),e=c.g.getParent(this.n().C),f=e.offsetHeight;f&&(a=this.xb(a,e),f=c.cb.bound(1-a.y/f,0,1),this.r(d.b.da,{h:b,aa:f,volume:this.f.p.volume}))}});l.T.xp=c.o(C,{s:k.aj,j:i.k,xc:d.b.xc,yc:d.b.yc,Ca:function(){return c.q.A.Fa()},z:function(a){a[d.b.da]=this.wb},ba:function(){this.n().Y(this.f.p.sd?this.yc:this.xc)},click:function(){var a=c.m(),b=this.f.p;
this.r(d.b.da,{h:a,aa:b.sd?0:b.tf||1,volume:this.f.p.volume}).r(d.b.oa,{h:a,s:this.s})},wb:function(a,b){this.n().Y(b.aa>0?this.yc:this.xc)}});l.T.yp=c.o(C,{s:k.bj,j:i.k,click:function(a){var b=c.m(),e=this.n().C,f=e.offsetHeight;f&&(a=this.xb(a,e).y/f,a=1-c.cb.bound(a,0,1),this.r(d.b.da,{h:b,aa:a,volume:this.f.p.volume}).r(d.b.oa,{h:b,s:this.s}))}});l.T.zp=c.o(C,{s:k.cj,j:i.k,ed:15,kb:!1,wd:!1,I:function(){this.ed=this.f.wa.Jm||this.ed},Ca:function(){return c.q.A.Fa()||!this.f.wa.ri},z:function(a){a[d.u.Ea]=
this.dc;a[d.b.N]=this.V;a[d.u.Xa]=this.Bo;a[d.u.za]=this.oi;a[d.b.oa]=this.oi},X:function(a){a[d.O.Lc]=this.nb;a[d.O.Nb]=this.Pa},ba:function(){this.f.S.U(k.Wa);c.H.Za(this.Im,0,this);this.f.p.kc&&this.Gd()},Im:function(){var a=c.m();this.r(d.b.da,{h:a,aa:0,volume:this.f.p.volume}).r(d.b.B,{h:a})},dc:function(){this.kb||this.Gd()},Gd:function(){this.n().show();this.f.S.U(k.eb).show(k.Hb).bind(k.Hb,p.ya,c.H.ca(this.click,this)).U(k.Wa);this.wd=!0},V:function(){if(this.wd)this.kb=!0,this.jb()},Bo:function(){this.wd&&
!this.kb&&this.ui(this.f.p)&&(this.r(d.b.F,{h:c.m()}),this.n().Y("play"))},oi:function(){if(this.wd&&!this.kb&&!this.ui(this.f.p))this.kb=!0,this.jb()},ui:function(a){return this.ed<0?!1:a.Q>=this.ed},click:function(){if(!this.kb){this.kb=!0;var a=c.m();this.jb();this.r(d.b.da,{h:a,aa:1}).r(d.b.F,{h:a}).r(d.b.Ha,{h:a,ab:0}).r(d.b.Ja,{h:a}).r([d.b.oa,d.b.Oc],{s:this.s,h:a})}},jb:function(){this.f.S.remove(k.Hb).show(k.eb);var a=this.f.S.n(k.Wa);a.Da||a.show()},nb:function(){this.n().U();this.f.S.U(k.Hb)},
Pa:function(){this.n().show();this.f.S.show(k.Hb)}});l.T.Jp=c.o(v,{s:k.rq,j:i.k,z:function(a){a[d.b.N]=this.V},ba:function(){this.Mi(this.f.p.Ba)},V:function(a,b){this.Mi(b.Ba)},Mi:function(a){if(a)this.n().C.innerHTML=a}});l.T.Kp=c.o(C,{s:k.Wa,j:i.k,Ca:function(){return!c.q.A.Yd()},X:function(a){a[d.O.Lc]=this.nb;a[d.O.Nb]=this.Pa},nb:function(){this.n().U()},Pa:function(){this.n().show()},click:function(a){c.g.Md(a)}});l.T.Lp=c.o(v,{s:k.hj,j:i.k,z:function(a){a[d.b.N]=this.pc;a[d.b.Ia]=this.update;
a[d.b.Hg]=this.update;a[d.u.Xa]=this.update},ba:function(){this.pc()},pc:function(){this.n().tc("00:00")},update:function(a,b){this.n().tc(c.Qc.Ki(b.Q))}});l.T.Np=c.o(v,{s:k.kj,j:i.k,z:function(a){a[d.b.N]=this.pc;a[d.u.Ud]=this.vn},ba:function(){this.pc()},pc:function(){this.n().tc("00:00")},vn:function(a,b){this.n().tc(c.Qc.Ki(b.$))}});l.T.Sp=c.o(v,{s:k.Hj,j:[i.k,i.O],pe:i.k,xh:{},ad:q,Vi:2E3,mk:100,Ca:function(){return c.q.A.Pb()},z:function(a){var b=this.ve(this.reset),e=this.ve(this.seek),f=
this.ih(this.U),g=this.ih(this.show);a[d.u.za]=this.ve(this.ended);a[d.b.N]=b;a[d.b.B]=b;a[d.b.fa]=b;a[d.b.Ha]=e;a[d.b.Ia]=f;a[d.b.N]=g;a[d.u.Ea]=f;a[d.u.zc]=g;a[d.u.Sd]=f;c.l(c.sa(d.L),function(b,c){a[c]=f})},X:function(a){a[d.O.Ag]=this.Do;a[d.O.Nb]=this.Pa},ba:function(){this.Je=(new c.Z.ik({C:this.n().C,ja:360,bi:this.Vi,hf:!0})).Cd();this.Ee=c.H.ca(this.Ee,this);!this.f.p.kc&&!c.q.A.Fa()&&this.show()},Do:function(){this.pe=i.O;this.show()},Pa:function(){var a=this.xh[i.k];a&&a.call(this);this.pe=
i.k},ve:function(a){var b=this;return function(c,d){var g=d.j;(g||!b.qh(g))&&a.call(b,c,d)}},ih:function(a){var b=this;return function(c,d){var g=d.j;if(g&&(g=b.qh(g),b.xh[g]=a,g!==q))return;a.call(b,c,d)}},qh:function(a){a=c.Sa(a);return c.find(a,function(a,c){return c!==this.pe},this)},ended:function(){this.la=!0;this.U()},seek:function(){if(!this.la)this.la=!1,this.show()},reset:function(){this.la=!1},show:function(){if(!this.la&&!this.n().Da&&!this.Je.Cb)clearTimeout(this.ad),this.ad=setTimeout(this.Ee,
this.mk)},Ee:function(){this.n().show();this.Je.cc()},U:function(){clearTimeout(this.ad);this.ad=q;this.n().U();this.Je.stop()}});l.T.Xp=c.o(C,{s:k.fe,j:i.k,B:d.b.B,F:d.b.F,Ja:d.b.Ja,A:c.q.A,Mf:c.q.A.gg()||c.q.A.Ib()||c.q.A.Vb(),Jd:c.q.A.Ib()&&!c.q.A.jg()||c.q.A.Vb()&&!c.q.A.Zd(),z:function(a){a[d.b.N]=this.V;a[d.b.Ia]=this.Ef;a[d.u.za]=this.ended;a[this.F]=this.pause;a[this.B]=this.play;a[d.b.fa]=this.play},X:function(a){a[d.O.Lc]=this.nb;a[d.O.Nb]=this.Pa},ba:function(){var a=this.f.p.qa;this.n().Y(a?
this.F:this.B);this.f.S.bind(k.eb,p.ya,c.H.ca(this.click,this));this.Mf&&!a&&this.n().show(1).Y(this.F);this.Jd&&this.n().ai()},V:function(){this.la=!1;this.Y(this.B)},Ef:function(){this.la=!1},ended:function(){this.la=!0;this.n().Y(this.F)},click:function(a){c.g.Md(a);a=c.m();if(this.la)this.r(d.b.fa,{h:a});else{!this.Jd&&this.Mf&&this.n().show(0);var b=this.f.p,e=b.Qa?this.Ja:this.B;this.r(b.qa?this.F:e,{h:a});this.r([d.b.oa,d.b.Oc],{s:this.s,h:a})}},play:function(){this.la=!1;!this.Jd&&this.Mf&&
this.n().show(0);this.Y(this.F)},pause:function(){this.Y(this.B)},Y:function(a){this.Jd||this.n().Y(a)},nb:function(){this.f.S.U(k.eb)},Pa:function(){this.f.S.show(k.eb)}});l.T.Wp=c.o(C,{s:k.Hc,j:i.k,B:d.b.B,F:d.b.F,Ja:d.b.Ja,de:d.Kb.Hc.de,ee:d.Kb.Hc.ee,z:function(a){a[d.b.N]=this.V;a[d.u.za]=this.pause;a[this.F]=this.pause;a[this.B]=this.play;a[d.b.fa]=this.play},ba:function(){this.n().Y(this.f.p.qa?this.F:this.B)},V:function(){this.n().Y(this.B)},click:function(){var a=c.m(),b=this.f.p.Qa?this.Ja:
[this.ee,this.B];this.r(this.f.p.qa?[this.de,this.F]:b,{h:a}).r(d.b.oa,{s:this.s,h:a})},play:function(){this.n().Y(this.F)},pause:function(){this.n().Y(this.B)}});l.T.Yp=c.o(v,{s:k.bk,j:i.k,z:function(a){a[d.b.N]=this.V;a[d.u.Xa]=this.update;a[d.u.Ic]=this.update},V:function(){this.Ni(0)},update:function(){var a=this.f.p,b=a.$;if(b)b=a.Q/b*100,a=a.ob,this.Ni(b>a?b:a)},Ni:function(a){this.n().bc({width:c.cb.bound(a,0,100)+"%"})}});l.T.dq=c.o(C,{s:k.fk,j:i.k,Ca:function(){return!c.q.A.Yd()},z:function(a){a[d.b.N]=
this.jb;a[d.b.Ia]=this.jb;a[d.u.za]=this.ended},ba:function(){this.f.S.bind(k.ie,p.ya,c.H.ca(this.click,this))},ended:function(){this.la=!0;this.n().show();this.f.S.show(k.ie).U(k.Wa);this.f.p.$a&&this.f.S.show(k.Fg)},click:function(){if(this.la){var a=c.m();this.r(d.b.fa,{h:a}).r([d.b.oa,d.b.Oc],{s:this.s,h:a});this.jb()}},jb:function(){if(this.la)this.la=!1,this.n().U(),this.f.S.U(k.ie).show(k.Wa)}});l.T.lq=c.o(C,{s:k.Fg,j:i.k,Aa:d.b.Aa,na:d.b.na,Ca:function(){var a=c.q.A;return a.Pb()||a.Wj()||
!a.Yd()||a.Vb()},X:function(a){a[d.b.Kc]=this.Df},click:function(){var a=c.m();this.r(this.f.p.$a?this.na:this.Aa,{h:a}).r(d.b.oa,{s:this.s,h:a})},Df:function(){this.n().Y(this.f.p.$a?this.na:this.Aa)}});l.T.mq=c.o(aa,{s:k.jk,j:i.k,Ae:!0,Yc:!1,Be:q,I:function(){this.qc=this.f.S.n(k.kk);c.g.bind(r,"mousemove",c.H.ca(this.zd,this));c.g.bind(r,"mouseup",c.H.ca(this.rf,this))},z:function(a){a[d.b.N]=this.V;a[d.u.Xa]=this.update;a[d.b.Ia]=this.update},V:function(){this.Hf(0)},update:function(a,b){if(!this.f.p.kf){var c=
b.$;if(c)c=b.Q/c*100+"%",this.lc=q,this.Hf(c)}},mc:function(){var a=this;this.Yc=!0;this.Be=setTimeout(function(){a.yh(c.m())},N/2)},rf:function(){if(this.Yc){this.Yc=!1;var a=c.m();this.Ae=!0;clearTimeout(this.Be);var b=this.f.p,e=b.$;if(e&&this.lc!=q){var f=(this.lc||0)*e/100;this.r(d.b.Ha,{$:e,h:a,Q:b.Q,ab:f});this.gp&&!(f>=e)&&this.r(d.b.B,{h:a})}}},zd:function(a){if(this.Yc){var b=c.m();clearTimeout(this.Be);this.yh(b);var e=c.g.getParent(this.n().C),f=e.offsetWidth;if(f)a=this.xb(a,e),this.lc=
c.cb.bound(a.x/f*100,0,100),this.Hf(this.lc+"%"),this.r(d.b.Hg,{h:b,Q:this.lc*this.f.p.$/100})}},yh:function(a){a=a||c.m();if(this.Ae)this.Ae=!1,this.gp=this.f.p.qa,this.r(d.b.F,{h:a}).r(d.b.oa,{s:this.s,h:a})},Hf:function(a){this.n().bc({marginLeft:a});this.qc&&this.qc.bc({width:a})}});l.T.oq=c.o(v,{s:k.tk,j:i.k,z:function(a){a[d.Kb.ne]=this.Gf},Id:function(a){a[p.Td]=this.mc},mc:function(a){var b=c.m(),e=this.f.p,f=e.$;if(f){var g=this.n().C,h=g.offsetWidth;h&&(g=(this.xb(a,g).x/h||0)*f,c.g.Hi(a),
this.r(d.b.oa,{s:this.s,h:b}).r(d.b.Ha,{$:f,h:b,Q:e.Q,ab:g}))}}});l.T.pq=c.o(v,{s:k.Pg,j:i.k,z:function(a){a[d.Kb.ne]=this.Gf},Gf:function(){var a=this.n(),b=0,d=0;c.l(this.Sn(),function(a,g){if(g.Da){var h=c.g.zb(g.C,"float"),i=g.Sm();h==="right"?d+=i:b+=i}});a.Qh({marginLeft:b+"px",marginRight:d+"px"})}});l.T.uq=c.o(C,{s:k.wk,j:i.k,Ca:function(){return c.q.A.Fa()},z:function(a){a[d.b.Va]=this.Xm;a[d.b.N]=this.V},ba:function(){var a=this.f.p.ta;a?this.If(a):this.ni()},Xm:function(a,b){this.Ro();
this.If(b.ta)},V:function(a,b){c.vd(b.R)||this.ni()},ni:function(){var a=this.n();a.Da&&(a.U(q,!0),this.pi())},Ro:function(){var a=this.n();a.Da||(a.show(q,!0),this.pi())},pi:function(){this.r(d.Kb.ne,{h:c.m()})},click:function(){var a=c.m(),b=this.f.p,e=b.R;c.vd(e)&&(b=b.ta===I.eg?I.Gg:I.eg,e[b]&&(this.r(d.b.Va,{h:a,ta:b}).r(d.b.oa,{h:a,s:this.s}),this.If(b)))},If:function(a){this.n().tc(c.ga.ap(a))}});l.Jc=c.o($,{I:function(){this["super"].I(new l.Xb)},z:function(a){this["super"].z.call(this,a);
var b=d.b;a[b.F]=this.pause;a[b.B]=this.play;a[b.fa]=this.mb;a[b.Ha]=this.seek;a[b.da]=this.Kf},pause:function(){var a=this.D;!a.paused&&a.src&&a.pause()},play:function(){var a=this.D;a.paused&&a.src&&a.play()},mb:function(a){this.D.src&&(this.seek(a,{ab:0}),this.play())},seek:function(a,b){var c=this.D;if(c.src){var d=c.duration,g=b.ab;g>=d&&(g=d-0.5);c.currentTime=g}},Jf:function(a,b){var c=this.D;if(b||c.src!==a)b>=0&&(a+="#t="+b),c.pause(),c.src=a,c.load()},Kf:function(a,b){this.D.volume=c.cb.bound(b.aa,
0,1)}});var N=500;l.ke=c.o(K,{type:z.bb,I:function(a){function b(){e.paused||f.ra(d.u.Xa);setTimeout(b,N)}if(c.q.A.Fa())this.D=c.g.Ye("video",a.Ed);var e=this.D=this.D||this.cn(a.Ed),a=a.w,f=this;c.g.bind(e,d.u.L,function(){var a=e.error;if(a)switch(a.code){case 2:f.ra(d.L.qg);break;case 3:f.ra(d.L.Yf);break;case 4:f.ra(d.L.oe)}});var g=q;c.g.bind(e,d.u.Ea,function(){var a=g===e.src?d.u.Sd:d.u.Ea;g=e.src;f.ra(a)});c.g.bind(e,d.u.zk,function(){f.ra(d.u.zc)});c.g.bind(e,[d.u.Ud,d.u.za,d.u.ng,d.u.Ic,
d.b.Ia],function(a){f.ra(a.type)});c.g.bind(e,d.u.og,function(a){f.ra(a.type,{videoHeight:e.videoHeight,videoWidth:e.videoWidth})});setTimeout(b,N);a.bind(d.u.za,function(){f.ra(d.u.Xa)});a={};a[d.b.B]=d.b.xg;a[d.b.F]=d.b.tg;c.l(a,this.Nm,this);this.Ri()},cn:function(a){var b=c.g.lb("video",c.t({position:"absolute",left:"0px",top:"0px",overflow:"hidden"},c.g.qd()));this.id=b.id=this.id||c.Ab();b.preload="auto";c.g.ib(b,a);return b},ra:function(a,b){this.qi&&this["super"].ra.call(this,a,b)},gi:function(){return this.D.duration},
ki:function(){return this.D.currentTime},mi:function(){var a=this.D;if(!a.src)return 0;var b=a.buffered;if(b==q)return 0;var c=b.length,a=a.duration;return!c||!a?0:b.end(c-1)/a*100}});l.sk=c.o(s,{j:c.sa(i),z:function(a){a[d.b.Aa]=this.fullScreen;a[d.b.na]=this.xo},ba:function(){var a=this.f.w;c.g.bind(r,["fullscreenchange","webkitfullscreenchange","mozfullscreenchange"],function(){a.v(d.b.Kc,{h:c.m()})})},fullScreen:function(){var a=this.f.xa,b=this.f.p.Ie.D;a.requestFullScreen?a.requestFullScreen():
a.webkitRequestFullScreen?a.webkitRequestFullScreen():a.mozRequestFullScreen?a.mozRequestFullScreen():b.webkitRequestFullScreen?b.webkitRequestFullScreen():b.webkitEnterFullScreen&&b.webkitEnterFullScreen()},xo:function(){r.cancelFullScreen?r.cancelFullScreen():r.webkitCancelFullScreen?r.webkitCancelFullScreen():r.mozCancelFullScreen&&r.mozCancelFullScreen()}});var n={};n.rb=c.o(s,{I:function(){this.Ge={}},Ne:function(){this.Ge={}},Ua:function(a,b){this.Ge[a.type]=b.h},Oa:function(a){return!a?j:function(b,
c){this.r(a,c)}},Pe:function(a,b,c){return!b?j:function(d,g){this.ka(g,a,b,c)}},ka:function(a,b,c,d){b=this.Ge[b];b!=q&&(b=a.h-b,d&&(b=D.abs(b)),this.r(c,{h:a.h,of:b}))}});n.Og={ml:{prod:"prod",gamma:"preprod",beta:"beta",local:"beta"},ep:function(a){return a.i&&a.a&&a.c},Mn:function(a,b,c){var c=c||{},c=this.Tn(this.ml[c.kd||"prod"],c.xf||"na"),d=location.protocol,a=this.Lk(a,b);return d+"//"+c+"/iu3?"+a},Lk:function(a,b){return c.ea.Nd({d:"forester-did","ex-fargs":"?"+c.ea.Nd(a),"ex-fch":b})},Tn:function(a,
b){return[this.zl(a,b),".amazon-adsystem.com",b==="na"?"":"/s"].join("")},zl:function(a,b){b==="na"&&(b="");var c=[b?"aax":"s"];b&&c.push(b);a!=="prod"&&c.push(a);return c.join("-")}};n.ua={};n.ua.rb=c.o(n.rb,{I:function(a){this["super"].I();this.Af();c.t(this,a)},z:function(a){var b=d.b;a[b.Aa]=this.Oa(this.Aa);a[b.na]=this.Oa(this.na);a[b.F]=this.Oa(this.F);a[b.B]=this.Oa(this.tb);a[b.Oc]=this.Oa(this.ya);a[b.N]=this.Af;a[b.fa]=this.zf;a[d.u.Ea]=this.ao;a[b.B]=this.play;a[b.Ha]=this.seek;a[b.Ia]=
this.Ef;a[b.da]=this.wb},Ff:function(a){function b(a,b){a&&(d[a]=b)}var d={};b(this.Ka,0.2);b(this.Cc,25);b(this.Gc,50);b(this.Pc,75);b(this.Jb,100);var f=this;c.l(d,function(b,c){a.push({sa:c,W:f.en(b)})})},en:function(a){return function(b,c,d){this.f.p.R&&this.cp(b)&&this.r(a,d)}},cp:function(a){if(a<=this.xi)return!1;this.xi=a;return!0},Af:function(){this.Fn=!0;this.zf()},zf:function(){this.xi=-1},mb:function(){this.zf()},ao:function(a,b){this.f.p.R&&this.Fn&&this.r(this.Ob,b)},play:function(a,
b){this.f.p.R&&this.r(this.tb,b)},seek:function(a,b){this.Di=b.Q},Ef:function(a,b){if(this.f.p.R){var c=b.Q;c!==this.Di&&this.r(c>this.Di?this.Nc:this.Mc,b)}},wb:function(a,b){if(this.f.p.R){var c=b.volume,d=b.aa,g;if(c===0&&d)g=this.Wb;else if(c&&d===0)g=this.Qb;g!=q&&this.r(g,b)}}});n.ua.Sj=c.o(n.ua.rb,{J:d.J.Bc.k,I:function(){var a=this.J;this["super"].I.call(this,{Jb:a.fj,Aa:this.J.uj,Qb:a.Rj,na:this.J.Tj,F:a.Xj,tb:a.gk,Mc:a.nk,Nc:a.ok,Ka:a.pk,Wb:a.vk});c.g.bind(o,"beforeunload",c.H.ca(this.Km,
this))},z:function(a){this["super"].z.call(this,a);a[d.b.B]=this.play;a[d.b.F]=this.pause;a[d.b.fa]=this.mb;a[d.b.N]=this.V;a[d.u.za]=this.wc},play:function(a,b){this.f.p.R&&(this["super"].play.apply(this,arguments),this.Ua(a,b))},pause:function(a,b){this.f.p.R&&(this.f.w.v(this.F,b),this.wc(a,b))},mb:function(a,b){this.f.p.R&&(this["super"].mb.apply(this,arguments),this.wc(a,b),this.Ua({type:d.b.B},b))},V:function(a,b){this.Af();this.wc(a,b)},Km:function(a){this.wc(a,{h:c.m()})},wc:function(a,b){this.ka(b,
d.b.B,this.J.yk);this.Ne()}});n.ua.lj=c.o(n.ua.rb,{I:function(){var a=d.J.Tg;this["super"].I.call(this,{ya:a.ya,Jb:a.Jb,Cc:a.Cc,Aa:a.cg,Ob:a.Ob,Gc:a.Gc,Qb:a.Qb,na:a.$f,F:a.F,fa:a.fa,tb:a.tb,Mc:a.Mc,Nc:a.Nc,Ka:a.Ka,Pc:a.Pc,Wb:a.Wb});this.f.w.v(a.Xf,{h:c.m()})}});n.mj=c.o(s,{ug:"__EVENT_NAME__",tj:416719,I:function(){var a=this.f.wa,b=c.Lf(this.f.wa.tn);if(b&&n.Og.ep(b))b.e=this.ug,this.fi=n.Og.Mn(b,this.tj,{kd:a.kd,xf:a.xf}),this.Fb=a.un},z:function(a){if(this.fi)c.l(d.J.Tg,function(b,c){a[c]=this.Ko},
this),a[d.b.Wf]=this.Wm},Wm:function(a,b){this.Fb=b.Fb},Ko:function(a){a=this.fi.replace(this.ug,a.type+this.Fb);c.ea.Ei(a)}});n.dg=function(a){this.Ai=c.t({},this.Zf.Ze,a.Ze);if(!a.ho)this.ub={},this.bd={},this.ph=["//",this.ll[a.kd||"prod"],"/1/action-impressions/1/OP/",a.$e||this.Zf.$e,"/action"].join(""),c.g.bind(o,"beforeunload",c.H.ca(this.Yq,this)),this.rl=a.In||60,a.Cq||this.Ah()};n.dg.prototype={Zf:{$e:"vap-metrics",Ze:{marketplaceId:"ATVPDKIKX0DER",requestId:"ABCDEFGHIJKLMNOPQRST",service:"Airy",
session:"123-1234567-1234567"}},Mj:d.J.K.Ga+":",Nj:d.J.Bc.Ga+":",Oj:d.J.L.Ga+":",Pj:d.J.K.Ga+":",Qj:":u=ms",ll:{prod:"fls-na.amazon.com",gamma:"fls-gamma-na.amazon.com",beta:"fls-gamma-na.amazon.com",local:"localhost"},wm:function(a){return this.Tc(this.ub,this.Mj,a)},ym:function(a){return this.Tc(this.ub,this.Nj,a)},zm:function(a){return this.Tc(this.ub,this.Oj,a)},Bm:function(a,b){return!c.ud(b)?this:this.Tc(this.bd,this.Pj,a+"@v="+b)},Tc:function(a,b,d){if(!a)return this;c.Sh(a,b,d);return this},
Kk:function(){if(c.every(this.ub,this.kh,this)&&c.every(this.bd,this.kh,this))return q;var a=[this.ph];c.l(this.ub,function(b,c){c.length&&a.push(b+c.join(","))});c.l(this.bd,function(b,c){c.length&&a.push(b+c.join(",")+this.Qj)},this);this.Qk();return a.join("/")+"?"+c.ea.Nd(this.Ai)},kh:function(a,b){return b.length==0},Qk:function(){this.ub={};this.bd={}},vf:function(){if(this.ph){var a=this.Kk();a&&c.ea.Ei(a)}},Ah:function(){o.setTimeout(c.H.ca(this.Ah,this),this.rl*1E3);this.vf()}};n.dk=c.o(s,
{qj:100,pf:{Go:c.t({},d.J.K.INIT,d.J.K.k,d.J.K.gb),xn:d.J.Bc.k,error:c.t({},d.J.L.k,d.J.L.gb)},I:function(){this.Ma=this.f.Hn},bind:function(){this.va(this.z,c.sa(i));this.va(this.X);this.ba(this.f);return this},z:function(a){this.Ik(a);var b=c.H.ec(this.Ma.vf,this.qj,this.Ma);a[d.u.Ea]=b;a[d.u.za]=b},Ik:function(a){this.Ma&&(c.l(this.pf.Go,function(b,c){a[c]=this.Yl(c)},this),c.l(this.pf.xn,function(b,c){a[c]=this.Zl(c)},this),c.l(this.pf.error,function(b,c){a[c]=this.Ul},this))},X:function(a){a[d.b.pb]=
this.qe},Yl:function(a){return/Duration$/.test(a)?this.Ch:this.Sl},Zl:function(a){return/Duration$/.test(a)?this.Ch:this.Tl},Sl:function(a){this.Ma.wm(a.type)},Tl:function(a){this.Ma.ym(a.type)},Ul:function(a){this.Ma.zm(a.type);this.Ma.vf()},Ch:function(a,b){this.Ma.Bm(a.type,b.of)},qe:function(a,b){c.t(this.Ma.Ai,{"class":b.ha.type})}});n.Sb={};n.Sb.Lj=c.o(n.rb,{K:d.J.K,j:i.k,z:function(a){a[d.L.Yf]=this.Oa(d.J.L.k.Xd);a[d.L.qg]=this.Oa(d.J.L.k.ae);a[d.L.Rg]=this.Oa(d.J.L.k.uk);a[d.L.oe]=this.Oa(d.J.L.k.xk);
a[d.G.he]=this.Ua;a[d.G.sb]=this.Pe(d.G.he,this.K.k.gj)},X:function(a){var b=d.G;a[b.Mb]=this.Ua;a[b.Wd]=this.Pe(d.G.Mb,this.K.INIT.oj);a[b.me]=this.Ua;a[b.Ub]=this.Uo;a[b.Qg]=this.bp},Uo:function(a,b){this.Ua(a,b);this.ka(b,d.G.Mb,this.K.INIT.pj);this.ka(b,d.G.me,this.K.gb.Cg)},bp:function(a,b){this.ka(b,d.G.Mb,this.K.INIT.nj);this.ka(b,d.G.Ub,this.K.gb.Gj)}});n.Sb.ck=c.o(n.rb,{K:d.J.K,I:function(){this["super"].I();this.Qa=!0},z:function(a){a[d.b.N]=this.V;a[d.b.Va]=this.Ne;a[d.b.B]=this.play;a[d.u.og]=
this.to;a[d.u.ng]=this.so;a[d.u.Ea]=this.dc;a[d.u.zc]=this.Qm;a[d.u.Sd]=this.Pe(d.u.zc,this.K.k.Bg)},play:function(a,b){this.Ua(a,b);var e=this.Qa;this.Qa=!1;this.f.p.kc&&e&&this.ka({h:c.m()},d.b.B,this.K.k.yg)},V:function(a,b){this.Qa=!0;this.Ne();this.Ua(a,b)},to:function(a,b){this.ka(b,d.b.N,this.K.k.Kj);this.ka(b,d.b.B,this.K.k.ak)},so:function(a,b){this.ka(b,d.b.N,this.K.k.Jj);this.ka(b,d.b.B,this.K.k.$j)},dc:function(a,b){this.ka(b,d.b.N,this.K.k.Ij);this.ka(b,d.b.B,this.K.k.Zj);this.ka(b,d.b.B,
this.K.k.yg)},Qm:function(a,b){this.Ua(a,b);this.f.w.v(this.K.k.ek,b)}});var ua=c.o(V,{fn:function(){var a=this.pa.wa;this.fh(new t.ke(this.pa,{j:this.xe,yb:a.yb,nd:a.nd,vc:a.vc}),t.Jc)},hn:function(){this.fh(new l.ke(this.pa,{j:this.xe}),l.Jc)},fh:function(a,b,e){var f=this.pa;(new b(f,{ha:a,D:a.D})).rc(this.xe).bind();f.Jo[a.id]=a;e!==!1&&f.w.v(d.b.pb,{h:c.m(),ha:a})}}),va=c.o(V,{jn:function(){(new l.sk(this.pa)).bind()},En:function(){var a=this.pa.wa.Vo,b=this.pa.w;a?(ca.bind(d.G.Dg,this.em,this),
c.Ng.Dn(a,{uc:w(),error:function(){b.v(d.J.L.gb.ae,{h:c.m()})}})):b.v(d.G.Ub,{h:c.m()})},uh:!1,em:function(a,b){if(!this.uh&&(this.uh=!0,b.Cf==="skin"))this.pa.To=b.Bf,this.pa.w.v(d.G.Ub,{h:c.m()})},ro:function(){var a=this.pa,b=a.To;if(b){try{var e=(new P(a)).parse(b)}catch(f){a.w.v(d.J.L.gb.Xd,{h:c.m()});return}c.l(a.wa.sn,function(a,b){e[b]=q});var b=a.S.Fo(e),g=this.dl()[k.Pg];g&&g.Gf();c.l(e,this.Vk,this);b.Lm().um(a.xa)}},dl:function(){var a={};c.l(l.T,function(b,c){var d=(new c(this.pa)).bind();
a[d.s]=d},this);return a},Vk:function(a,b){(new ta(this.pa)).Oo(b).bind()}});O.prototype={$k:function(a){var b={};b[x.bb]=new l.Xb;b[x.Fc]=new t.Xb(a);return b},evaluate:function(a){a=c.Sa(a);return c.find(this.Ci,function(b,d){var f=this.Kl[d];if(f)return d===x.Fc&&c.Dc.fo()?j:this.Hm(a,f)},this)},Hm:function(a,b){return c.some(a,function(a,c){var d=b.pd(c);return b.ic(d)})}};var wa=c.o(X,{Cm:function(a,b){return this.nc({name:c.Ab(),W:b?a.fn:a.hn,scope:a})},vm:function(a){return this.nc({name:d.G.Kg,
oc:{ei:d.G.sb,j:i.k},W:a.jn,scope:a})},Dm:function(a){return this.Mo(a).nc({name:d.G.me,W:a.En}).nc({name:d.G.Qg,oc:[d.G.Kg,d.G.Ub],W:a.ro})},Am:function(a){return this.Zm().nc({name:c.Ab(),oc:{ei:d.G.sb,j:i.k},W:function(){var b=a.wa;a.w.v(d.b.N,{Ya:b.Ya,Ba:b.Ba,j:i.k,h:c.m(),R:b.yi||b.Qf})}})}}),xa=c.o(U,{create:function(){var a=this.qm,b=a.wa,e=a.w,f=a.Sq=new O(b),g=a.zi=new W(b),h=b.yi,g=h?g.select(h).Sf:b.Qf,f=a.mode=f.evaluate(g);if(!f)throw e.v(d.L.oe,{h:c.m()}),"Video is unsupported for the supplied configuration";
a.Jo={};(new qa(a)).bind();b.lo&&e.v(d.b.ge,{h:c.m(),R:h||b.Qf});b=f===x.Fc;e=a.br=new Y(e);h=new va(a);f=new ua(a,i.k);(new wa).Cm(f,b).vm(h).Am(a).Dm(h).$m(e)}});G.embed=function(a){var b=c.m(),e={},a=e.wa=c.compact({Ta:a.parentId,parentElement:a.parentElement,rn:a.desiredMode,Gn:a.forceMode,Po:a.shouldStartHidden,Ya:a.contentId,fd:a.desiredVideoQuality,yi:a.mediaInfo,Qf:a.streamingUrls,lo:a.isPrefetchEnabled,Vo:a.skinUrl,nd:a.flashParams,yb:a.flashVars,vc:a.swfUrl,Pm:a.bindings,ln:a.cuePoints,
sn:a.disabledViewIds,Jm:a.autoplayCutOffTimeSeconds,ri:a.isAutoplayEnabled,Ba:a.contentTitle,tn:a.displayAdsForesterParams,un:a.displayAdsMetricEventNameSuffix,Pd:fa(a.videoAds),kd:a.environmentStage,xf:a.regionCode,ho:a.isForesterTrackingDisabled,In:a.foresterPublishingInterval,$e:a.foresterProgramGroupName,Ze:a.foresterMetadataParams})||{},f=a.parentElement||c.g.Xe(a.Ta),g=e.xa=ea(),h=e.Ed=c.g.lb("div",{position:"relative",height:"100%",width:"100%"});c.g.ib(h,g);var k=e.w=new la(c.sa(i));c.l(a.Pm,
function(a,b){k.Vh(a,b,q,[i.Lb,i.k])});var m=e.Zh=(new ma(e)).rc(i.k).bind();c.l(a.ln,function(a,b){m.Th(b)});e.Dq=(new oa(e)).bind();e.p=(new pa(e)).rc(i.k).bind();e.S=new l.Ug;(new ra(e)).bind();if(a.Po)a.ri=!1,k.v(d.b.Ec,{timestamp:c.m()});e.Hn=new n.dg(a);(new n.dk(e)).bind();c.l([n.mj,n.ua.lj,n.ua.Sj,n.Sb.Lj,n.Sb.ck],function(a,b){(new b(e)).rc(i.k).bind()});(new sa(e)).bind();try{if(c.l([Ads.Rb.ua.Tp,Ads.Rb.ua.Zp,Ads.Rb.ua.tq,Ads.Rb.ua.vq,Ads.Rb.tp,Ads.Rb.Sb.sp],function(a,b){(new b(e)).rc(i.O).bind()}),
(new Ads.Up(e)).bind(),(new Ads.Jc(e)).bind(),(new Ads.eq(e)).bind(),(new Ads.fq(e)).bind(),a.Pd.td==q)a.Pd.td=!0}catch(o){a.Pd.td=!1}try{(new xa(e)).create()}catch(p){return}a=(new na(e)).bind().Le();c.g.ib(g,f);k.v(d.G.Mb,{h:b}).v(d.G.Wd,{h:c.m()});return a};(z=o.amznJQ)&&z.declareAvailable("Airy");(z=o.P)&&z.register("Airy",function(){return o.Airy})})(window,document,Math);